### ISSUE TITLE
 Rewards not dispensed

### ISSUE THREAD

**Issue by nagadau** [Sifchain/Support-Tickets#186]
I claimed the rewards day before yesterday(that is early Monday) and it showed as pending dispensation. Out of which 30% was dispensed and i was able to see on my wallet but 70% of the amount still shows as pending dispensation. The expected rewards were approximately 3200 and dispensed amout was around 1000. the pending dispensation is 2123.79. 
I can see that as total pending dispensation also in the Pools of the People(v2) — 997 and Sif’s Expansion - 1126.59

approved by telegram user: : @Karan8798

requested by telegram user: @evolution4good
associated sifchain address: sif1lspy7yu506jz2qa0npwuut22qayde49uaqwf77

**Comment by daechoi** [comment]
Please check the slack message on the list of tables to track reward program.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lufa23** [comment]
so my understanding is that the user is referring to [this claim transaction](https://www.mintscan.io/sifchain/txs/A16FE29A5ABF2590C5429239B900D6F7C4EBEF563010330B350CDE1DC8B4FA91) right?

Running:
```
select * from snapshots_reward where address = 'sif1lspy7yu506jz2qa0npwuut22qayde49uaqwf77'

select * from post_distribution where recipient = 'sif1lspy7yu506jz2qa0npwuut22qayde49uaqwf77'

select * from pre_distribution_v2 where address = 'sif1lspy7yu506jz2qa0npwuut22qayde49uaqwf77'

select * from snapshots_claims_v2 where address = 'sif1lspy7yu506jz2qa0npwuut22qayde49uaqwf77'
```
i can see that he received 1138.355 Rowan.
I can also see that the snapshot was taken on 2021-12-28 at 00:42:41 (which corresponds to the time in which the claim was made)
<img width="792" alt="Screenshot 2021-12-30 at 16 38 08" src="https://user-images.githubusercontent.com/67415638/147766679-bd8bf0f3-f330-4737-a9b4-6130a217bbca.png">
<img width="707" alt="Screenshot 2021-12-30 at 16 39 31" src="https://user-images.githubusercontent.com/67415638/147766677-07bd738e-c65e-4066-a13a-72227a5ef7b8.png">
<img width="961" alt="Screenshot 2021-12-30 at 16 40 29" src="https://user-images.githubusercontent.com/67415638/147766674-9d512d10-9b11-464b-b28a-cec2e852b6f4.png">
<img width="1298" alt="Screenshot 2021-12-30 at 16 42 10" src="https://user-images.githubusercontent.com/67415638/147766664-5d0a2898-8b33-4cca-929c-34f2f0ef427c.png">

i assume that the pending amount will be distributed on Monday. 
@daechoi is there a way for me to check his pending amount directly from the tables? Or should i manually calculate it from his liquidity adds and declared APY?

**Comment by lufa23** [comment]
hey @karan-sifchain  please let me know if at the end of the day rewards have been correctly distributed

**Comment by ivorychristine** [comment]
As per the user: Hi Kym, i have got most of the rewards dispensed just few is pending. But thanks a lot for your help. You are always very helpful.

I will close this ticket now. Thanks for the assistance well appreciated! :)
