### ISSUE TITLE
 Rewards not received

### ISSUE THREAD

**Issue by nagadau** [Sifchain/Support-Tickets#190]
Hi, I claimed rewards on 2021-12-28 05:57:41 GMT+1 paris timzone, but on 2021-12-29 18:00:00 paris timezone I still have not received my rewards, why ? I'm on ROWAN/ETH pool, and sif chain expension and pools of people programs. I claimed 4189.06 ROWAN. Thanks for helping.

approved by telegram user: : @ladycryptoniteph

requested by telegram user: @john_boo
associated sifchain address: sif10elr4uj4ragn4d00sgf630ypjf948t72jpdp8l

**Comment by ivorychristine** [comment]
I approved this, for @Saerithrael cant approve pending issue on bot.

**Comment by lufa23** [comment]
running 
`select * from snapshots_claims_v2 where address = 'sif10elr4uj4ragn4d00sgf630ypjf948t72jpdp8l' `i can see that he claimed rewards on 2021-12-28 05:57:41 GMT+1 
As far as i know distribution should happen on monday right?

running 
`select * from pre_distribution_v2 where address = 'sif10elr4uj4ragn4d00sgf630ypjf948t72jpdp8l' i can see that his last received distribution was 454 Rowan from Sif Harvest on 2021-12-27 17:00:02
`

**Comment by lufa23** [comment]
hey @ivorychristine , let me know if at the end of the day rewards have been correctly distributed

**Comment by lufa23** [comment]
<img width="1030" alt="Screenshot 2022-01-04 at 17 29 59" src="https://user-images.githubusercontent.com/67415638/148091511-9d3790a7-8bd7-4014-83b4-694a575efaf1.png">

Because I can see that he received rewards yesterday..

**Comment by lufa23** [comment]
@ivorychristine i assume that this issue has been fixed. I will close it for now
