### ISSUE TITLE
User sent considerable amount to voting address

### ISSUE THREAD

**Issue by lufa23** [Sifchain/Support-Tickets#192]
**Describe the bug**

User accidentally sent 12638 ROWAN to the address handling stablecoins voting [sif1seftxu8l6v7d50ltm3v7hl55jlyxrps53rmjl8](https://www.mintscan.io/sifchain/account/sif1seftxu8l6v7d50ltm3v7hl55jlyxrps53rmjl8)

TX HASH:
https://www.mintscan.io/sifchain/txs/56302A57C80C43499BDD5BE9B9D645F3BC9EC45CFC72CFD52B0A43079A72D3AD

**Required action**
Can we give back the amount to the user?

**Comment by lufa23** [comment]
cc @caseyturnerarrington @mccallofthewild

**Comment by mccallofthewild** [comment]
I think @marshsif controls this address

**Comment by marshsif** [comment]
@lufa23 can you please verify with the user that funds need to be returned to the following address:
sif1laltj5cthhe8z2jkwjf2acage7s8g6klwehukp

**Comment by mccallofthewild** [comment]
@marshsif 12,638 ROWAN were sent. 

Please return 12,637.9 rowan (including the 0.1 they intended to send)

**Comment by marshsif** [comment]
slimtrim#4865

**Comment by marshsif** [comment]
@mccallofthewild and @lufa23 the funds have been sent. This is the user's handle if you can reach out to them: slimtrim#4865

**Comment by lufa23** [comment]
i guess that we can consider this case closed user has been reached out by @dana-nomad
