### ISSUE TITLE
During the last distribution, not all rewards were received

### ISSUE THREAD

**Issue by OlegEnthusiast** [Sifchain/Support-Tickets#194]
Some users reported that they did not receive all the rewards they claimed. Here are examples:
- sif1xkwr77r5aq367t0hq3ce2n0mvlmq2qgs28j95h
- sif1t6qmcazp9kgdx6a7qurvtqhzxscd6sf35u98gh

(I will update this as new reports come in.)

**Comment by dana-nomad** [comment]
User's hypothesis is that.

rewards are being calculated as 300% - the pool APR, as pool APR ranges around 5-10%
average pool APR is 7%.
293% rewards is distributed
remaining 7% goes into the liquidity pool increase

**Comment by dana-nomad** [comment]
DreamCatcher#7490 is his discord for more information

**Comment by ivorychristine** [comment]
Adding more information from user @libert8410 
Sif Address: sif1t6qmcazp9kgdx6a7qurvtqhzxscd6sf35u98gh
Transaction Hash: https://www.mintscan.io/sifchain/txs/49611A61798D4C8E99DA047BBAE08808BD187867DDADD4A2EF42ADE7FFED8E6F

Report:
I claim 840 Rowan on Monday, and only receive 586 ROWANS
![2022-01-05 11 21 03](https://user-images.githubusercontent.com/94232457/148155690-22580baa-ccac-4231-a180-01dae5162ad2.jpg)
![2022-01-05 11 21 11](https://user-images.githubusercontent.com/94232457/148155697-8f11d0bb-1d3b-45d6-b5bf-082869467f88.jpg)

@OlegEnthusiast FYI too

**Comment by lufa23** [comment]
hey guys, as discussed in the Reward retrospective meeting the issue here depends on the fact that:
- Rewards are calculated in Rowan's value.
- From the moment in which rewards are claimed until the moment on which rewards are distributed, price fluctuations change Rowan's value
- The amount of Rowan that is distributed as reward, changes depending on the fluctuation of Rowan price
- There may be discrepancies between the amount of rewards "claimed" and the amount of reward "distributed"
- We are currently working on documenting in detail how rewards are calculated, and on providing a platform that can be used as a rough extimation for rewards

**Comment by libert8410** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/30039311/148240409-b77c749e-d150-4233-88ff-9f1104ea8dfe.png)

**Comment by libert8410** [comment]
"From the moment in which rewards are claimed until the moment on which rewards are distributed, price fluctuations change"
I think there must be a bug. I claimed on Monday (18:20PM). The timeframe between claim and distribution is only several hours, the price fluctuates not so great. The rewards amount I received is less 30%+, which is totally absurd.

**Comment by libert8410** [comment]
"There may be discrepancies between the amount of rewards "claimed" and the amount of reward "distributed""
Could you tell what discrepancies may be regarded as "Normal"?

**Comment by lufa23** [comment]
hey @libert8410 i expressed myself inaccurately..
So your pending rewards will be distributed on next distribution (on Monday) 168.94 + 84.4749

Those rewards are the difference between 840 and 586 ROWAN

**Comment by Sleepy7676** [comment]
Need help with stuck rewards.

**Comment by dana-nomad** [comment]
@lufa23 can you tag me

**Comment by lufa23** [comment]
@dana-nomad

**Comment by mccallofthewild** [comment]
All rewards have been paid out.
