### ISSUE TITLE
Discrepancy in reported rewards due and actual rewards received the next day

### ISSUE THREAD

**Issue by vonnegut2018** [Sifchain/Support-Tickets#195]
Hello, 

I tried to claim my rewards at 7:59 am PT this Monday 3rd Jan, the claim button had indicated I would receive around 20.4k Rowan, but instead I received 14347 Rowan. This was from the ETH-Rowan pool. I am confused what happened to the 6k I was expecting to receive, 20k+ is what I typically receive each week... 

## Sif address
sif1kfvdwtd6p9z4h0ufuezqguc7fqdes302my9kx8

## Expected Reward amount / Received amount
Expected 20.4k, received 14347

## Reward Program title
ETH-ROWAN Pool

Thanks!

**Comment by emperorjm** [comment]
Can you post a screenshot of your rewards screen?

**Comment by vonnegut2018** [comment]
Here it is. I see now that my claimed pending rewards is where my missing
6k is. I guess as I was claiming the rewards somehow the transaction passed
into 8am PT and some but not all of it was sent? I did not know that was
possible. Thought it was an all or nothing situation

**Comment by vonnegut2018** [comment]
![Screen Shot 2022-01-05 at 5 50 14 PM](https://user-images.githubusercontent.com/43797141/148269217-54059c53-8686-428a-9bd2-0b11c8d851a7.png)

**Comment by emperorjm** [comment]
Based on my checks the rewards from the Pools of the People of 14,346.72296314267 were distributed but for some weird reason the amount from Sif Expansion of 6,091.22 got stuck in pending. This seems to be the same case for issue https://github.com/Sifchain/Support-Tickets/issues/194. Your pending rewards should be distributed in the next dispensation but I will have the Devs look into why this happened in the first place.

**Comment by vonnegut2018** [comment]
Thank you so much for explaining, Adrian.

Do you have a sense of how long these 300% rewards might last if the voting
continues to support ETH-Rowan? I read in the discord that it would go
until the margin trading is introduced - do you know how many months away
that might be? Your answer would help me a lot with managing my risk.

Best wishes,

**Comment by emperorjm** [comment]
@vonnegut2018 the Devs looked into the issue and they found that our system was calculating the final dispensation amount at the cut-off time of 8:00 a.m. PST and because you made the claim close to the processing cut off time the system was only able to process and commit partial reward amount.  The remaining amount of 6,091 rowan will be dispensed next week.  We have identified this edge case and rectified the process since to prevent recurrence.

**Comment by emperorjm** [comment]
Every month until Margin Trading is released, the community will vote to extend, modify, or end this inflationary liquidity mining program. I can't say when margin will be released but these questions are best asked on discord. I will close this issue now based on the response above.
