### ISSUE TITLE
Rewards Pending Dispensation Pool of the people V1

### ISSUE THREAD

**Issue by longinus88** [Sifchain/Support-Tickets#197]
# Liquidity Mining / Rewards issue![Rewards](https://user-images.githubusercontent.com/97160822/148197189-c7e6476e-8a94-4085-9dd1-ef2361533d3d.PNG)
## Describe the bug
Hello Team, I have some rewards stucked (Pending Dispensation). The rewards are old oneS (From the first 4 weeks of Sif Expansion and Pool of the people V1). Please see screenshot. The latest rewards have been already dispensed on Tuesday the 4th.

## Pool(s) affected
JUNO-ROWAN; ATOM-ROWAN

## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.

## Claim transaction(s)
The latest claim has been done on Monday the 3rd at around 7am PST.

## Sif address
sif1smknl4uf89ef84kg020ff7ask7l0sxz3s93gva

## Expected Reward amount / Received amount
Please write here details on the rewards amounts you were expecting

## Reward Program title
Sif Expansion and Pool of the people V1

## Error logs/Screenshots
Please add here error logs you are receiving/ screenshots>
![Rewards](https://user-images.githubusercontent.com/97160822/148197189-c7e6476e-8a94-4085-9dd1-ef2361533d3d.PNG)**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
The Devs are looking into this.

**Comment by longinus88** [comment]
Rewards pending dispensation received, thanks Team!
