### ISSUE TITLE
Stuck rewards

### ISSUE THREAD

**Issue by Sleepy7676** [Sifchain/Support-Tickets#198]
# Liquidity Mining / Rewards issue

## Describe the bug
Part of my rewards are stuck/still pending

## Pool(s) affected
ROWAN/ATOM

## Liquidity Add transaction(s)
I claimed my rewards well before the cut off time and have received some but not all rewards.

## Claim transaction(s)
I claimed 443.2514 ROWAN and received them all. Another 203.30 ROWAN are showing in the Claimed - Pending Dispensation and will not show up in the balances.
![image](https://user-images.githubusercontent.com/97203894/148369076-323e4eb4-dba4-4f77-9471-a8eb78e99766.jpeg)

## Sif address
sif1l0qj6grcp2dghpy0rrf20zmvsguxz4tvzsn6u0 

## Expected Reward amount / Received amount = 443.2514
203.30 still pending

## Reward Program title
Please write here the name of the reward program you are having issues with. Not sure

## Error logs/Screenshots
Please add here error logs you are receiving/ screenshots>

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by lufa23** [comment]
hey, we're looking into it..

**Comment by Sleepy7676** [comment]
Thank you, appreciate your help

**Comment by marshsif** [comment]
This should be resolved and the user should be able to verify it in the DEX UI.

**Comment by Sleepy7676** [comment]
Thank you!

**Comment by mccallofthewild** [comment]
These funds have now been dispensed. Thank you for your patience!

**Comment by Sleepy7676** [comment]
Thank you!
