### ISSUE TITLE
Sifchain sent to contract address

### ISSUE THREAD

**Issue by iss7777** [Sifchain/Support-Tickets#200]
On November 30, I tried to send 24,558 sifchain to another wallet and instead it went to the contract address.  I don't know how this happened because it's never happened to me before.  I would appreciate it very much if the sifchain could be returned/reimbursed.  Thank you very much!  

The hash is here:  https://polygonscan.com/tx/0xf11f537940f64c0a6686756990e294da416c23e38a05191d88caeecec05fa41

**Comment by lufa23** [comment]
hey, unfortunately we are not able to retrieve the funds..
The reason is that the smart contract is not upgradable, and there is no way for the team to retrieve the amount
