### ISSUE TITLE
Rewards: Claimed - Pending dispensation

### ISSUE THREAD

**Issue by xtrip15** [Sifchain/Support-Tickets#201]
On reward screen it shows rewards as pending dispensation. I'm unsure however, i thought I had received but couldn't locate transaction for it so maybe did not.

Here is claim transaction.

https://www.mintscan.io/sifchain/txs/474E0A28456D69760A9B382DBA893A72ACF2F96767D5F98F74A1A736E19F3EA5

And screenshot.

![Screen Shot 2022-01-06 at 7 18 23 PM](https://user-images.githubusercontent.com/37472873/148470836-9715d394-59b3-4c08-b4ba-f240c52cced7.png)

**Comment by lufa23** [comment]
hey, we're looking into it

**Comment by xtrip15** [comment]
Cool, thanks. Would you also let me know if I should claim rewards this Monday or wait for this to be resolved?

**Comment by xtrip15** [comment]
Got previous week and this week rewards together.  So all good. Closing issue.
