### ISSUE TITLE
JUNO fails to import

### ISSUE THREAD

**Issue by simonguenther** [Sifchain/Support-Tickets#202]
## Describe the bug

A Detailed description of the issue (what happened, token affected and token amount)

I want to import JUNO from JUNO chain. When I click through the dialog and finally send it via Keplr. It just says "There was an unknown failure". The transaction does not even get broadcasted. 
To me it looks like the IBC channel is wrong. On mintscan JUNO has channel-14 while keplr constructs the import message with channel-5.
This is NOT an issue of fees. I leave enough JUNO in my account to cover the fees.

## How to Reproduce

1. Go to Balances -> JUNO
2. Click on 'import'
3. Enter amount to be imported and click "confirm"
4. Click approve in Keplr wallet
5. See "There was an unknown failure" above the "close" button without a time delay

## Expected behaviour
I expect to see a transaction getting broadcasted on chain and afterwards the JUNO in my account

## TX Hashes
There is no tx hash.
The transaction JSON from Keplr looks like this

` {
  "chain_id": "juno-1",
  "account_number": "58633",
  "sequence": "0",
  "fee": {
    "gas": "500000",
    "amount": [
      {
        "denom": "ujuno",
        "amount": "12500"
      }
    ]
  },
  "msgs": [
    {
      "type": "cosmos-sdk/MsgTransfer",
      "value": {
        "source_port": "transfer",
        "source_channel": "channel-5",
        "sender": "junoaddress",
        "receiver": "sifaddress",
        "token": {
          "denom": "ujuno",
          "amount": "10000000"
        },
        "timeout_height": {
          "revision_number": "1",
          "revision_height": "5028545"
        }
      }
    }
  ],
  "memo": ""
}`

## Addresses
Not relevant as this is likely a front-end/IBC issue

## Error logs
There are no logs

## Screenshots
![unknown](https://user-images.githubusercontent.com/29353326/148676154-a7d138b6-bfa7-468a-ac56-66bd736b7b4b.png)

**Providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
@simonguenther make sure to use the average of high fee option and also leave enough JUNO to pay the transaction fee.

**Comment by simonguenther** [comment]
@emperorjm as mentioned in my ticket, there is enough JUNO left on the account for the fees. using high fee doesn't change the behaviour described.

**Comment by lufa23** [comment]
@simonguenther can you use the google chrome developer tools to show us which error logs appears on the console?
<img width="1086" alt="Screenshot 2022-01-11 at 13 32 51" src="https://user-images.githubusercontent.com/67415638/148943449-556bbe03-2cfa-46c8-a98a-0cfde4cf0797.png">

**Comment by emperorjm** [comment]
@simonguenther I did a test import and export and the import failed with the same error you posted above if I didn't leave an extra amount of JUNO for fees. Otherwise I had no issues importing JUNO. Try clearing your cache and trying again.
