### ISSUE TITLE
pool reward collection issue

### ISSUE THREAD

**Issue by Bearoutofthewoods** [Sifchain/Support-Tickets#203]
# Liquidity Mining / Rewards issue

## Describe the bug
My weekly rewards seem to be stuck as "claimed - Pending Dispensation. I claimed my rewards on Monday 3rd January. I have been able to see the rewards on the reward page as 'pending dispensation but nothing has been dispensed to my wallet as of yet. Also, none of this weeks rewards are visible and we are approaching claiming deadline. I have tried clearing  browser data and then restart browser, but to no avail.

## Pool(s) affected
ROWAN/ATOM

## Claim transaction(s)
Please write here details on the claim transactions (amount, pairs and date) and the links to those transactions

## Sif address
sif1tj8yqd86ukjmxxfrh4udjw2vw78v04tlu5em6k

## Expected Reward amount / Received amount
329.63 ROWAN

## Error logs/Screenshots

![Screen Shot 2022-01-09 at 13 11 51](https://user-images.githubusercontent.com/97404455/148694848-6f685100-ce2f-422b-9974-206b6034a438.png)

Thanks!

**Comment by emperorjm** [comment]
@Bearoutofthewoods was the pending amount paid out between the 10-11th?

**Comment by Bearoutofthewoods** [comment]
Hi, yes it was. However, my rewards after could not be claimed until today, January 18. I now have to wait for the l dispensation until next week Tuesday. At this rate I receive my rewards around once every two to three weeks. They also don’t seem to accumulate and are only the rewards from one weeks accumulation. Please can you look whether I am owed any rewards? 

Many thanks in advance ,

**Comment by emperorjm** [comment]
@Bearoutofthewoods I'm not sure I understand what you mean by you not being able to claim your rewards until today but the claim process will be automated going forward so you won't need to execute a claim anymore as your rewards will be automatically claimed each week.

See announcement here https://discord.com/channels/769209144515100693/773772812019564574/932734099788030002

**Comment by mccallofthewild** [comment]
@Bearoutofthewoods it looks like the rewards for the week in question were successfully paid out. Thank you for your patience! (you have a pending amount right now but it is for this week, and the claim was made after the dispensation)
