### ISSUE TITLE
Field of Gold Competition

### ISSUE THREAD

**Issue by Cosmosvalentine** [Sifchain/Support-Tickets#204]
# Liquidity Mining / Rewards issue

Hi there, sorry to bother. I haven’t gotten any confirmation on the Field of Gold competition standing— the reason I’m concerned is because I burned a large amount of $ swapping, but after it's abrupt termination I couldn’t see where I was-- also I continued to swap for hours if not days after the competition had ended. 

Trying to calculate my losses; but I don't know where I was. From what I remember, the amount I've been rewarded is significantly less than what was shown. I'd just like confirmation of where I finished and how much was to be dispersed to me, as these transactions don't show up on the blockchain (to my knowledge) it's hard to keep track. 

Appreciate the help, CV

**Comment by lufa23** [comment]
hey, the rewards for the Fields of Gold trading competition has been distributed already.
About your expectations of rewards, i guess that the change in Rowan's price played a role

**Comment by Cosmosvalentine** [comment]
I see, is there any way to confirm the amount I was allotted?

**Comment by lufa23** [comment]
distribution happened smoothly, so what you received is the correct amount

**Comment by Cosmosvalentine** [comment]
> distribution happened smoothly, so what you received is the correct amount

Sus but ok
