### ISSUE TITLE
Incorrect rewards per hour in few wallets

### ISSUE THREAD

**Issue by haroondilshad** [Sifchain/Support-Tickets#205]
# Liquidity Mining / Rewards issue

## Describe the bug
I have an account where I'm certain I suffered IL but the rewards I am getting are even lesser than what I should get for my liquidity pooled alone. I am certain I'm getting wrong rewards in this wallet per hour. The rewards I am getting in the problematic wallet are 22.951ROWAN/hour whereas according to the liquidity pooled I should be getting 32.2069ROWAN/hour. When I moved my liquidity to a new wallet viola I'm getting 32.2069ROWAN/hour in rewards as expected. 

## Pool(s) affected
ATOM, JUNO, ETH

## Sif address
sif185etkk0w5djgdy9lt4aa4d8aak6c9y9dh3ch23

## Expected Reward amount / Received amount
Expected:
32.2069
Received
22.951 ROWAN/hour

## Reward Program title
Sif's Expansion, Pools of the people

**Comment by lufa23** [comment]
hey, so reward amounts are calculated based on the price of ROWAN and your overall liquidity position in each respective pool.
Hourly reward amount = (APR / 365 days / 24 hours) x (Pool Value in ROWAN)
The value of your Liquidity Position (valued in Rowan) changes depending on the fluctuation of Rowan price.
When calculating rewards, both assets within your pool value are converted to ROWAN and the pool APR is applied to that total value. This happens on an hourly basis to capture and determine rewards for any given pool.
