### ISSUE TITLE
Exporting ATOM: error "insufficient balance"

### ISSUE THREAD

**Issue by thotbott** [Sifchain/Support-Tickets#206]
## Describe the bug

When attempting to export ATOM, I receive the error "Insufficient available balance for transaction fee" even though I have over 1 ROWAN available in my wallet.

If relevant, the 1 ROWAN was recently received through community faucet on discord.

## How to Reproduce

1. Go to "Balances"
2. Click on "Export" next to ATOM
3. Enter MAX on the amount (other amounts reproduce same error)
4. Error occurs when attempting to confirm transaction.

## Addresses
Sifchain Address: sif1ktfzafu9w6ysx6e35rgg597k4uhqyy4zstffe4
Cosmos Address: cosmos1ktfzafu9w6ysx6e35rgg597k4uhqyy4z4kxlk7

## Error logs
Please provide links to your addresses (both of Sifchain and external chain)

## Screenshots
![image](https://user-images.githubusercontent.com/84833257/149261505-02e00804-8802-49a1-8baa-3f586b2b3361.png)
![image](https://user-images.githubusercontent.com/84833257/149261514-0d595a0f-3dc2-403e-868f-f468e3d9319c.png)

**Providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
@thotbott you also need 0.99 ROWAN which is shown on the Export screen which is a separate fee to the transaction fee shown above.

**Comment by thotbott** [comment]
Ah, of course. How embarrassing. Thank you!
