### ISSUE TITLE
My rewards did not get released.

### ISSUE THREAD

**Issue by LeoLondon22** [Sifchain/Support-Tickets#209]
# Liquidity Mining / Rewards issue

## Describe the bug
Write here a clear and detailed description of what the bug is.
I cannot claim rewards, i actually tried to claim the rewards on Sunday as i am new to the platform, its states they are claimable on tuesday, but they never got released

## Pool(s) affected
<Please write here the pool(s)you are having issues with>.
LGCY / Rowan LP 

## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.

7362B5C09149F3A6D774F7289D83557573F0A4CC64A53BC8D49EF937F61F5376

## Claim transaction(s)
Please write here details on the claim transactions (amount, pairs and date) and the links to those transactions
can
the original claim was 258.97 Rowan, but now there is 984 rowan sitting to be claimed from the pools
A07C59A6E925332581C9D3A4BFA36F0E1C3EC53C2223599103EE8555F50715BB

## Sif address
Please write here your sif address
sif1cjc6ymdchtrd2egplaynrfnh4n6jer5uss7mtj

## Expected Reward amount / Received amount
Please write here details on the rewards amounts you were expecting
Expecting 984 Rowan
Received none, it seems locked still

## Reward Program title
Please write here the name of the reward program you are having issues with
LGCY / ROWAN LP - 300% APR

## Error logs/Screenshots
Please add here error logs you are receiving/ screenshots>
no error logs occurring, just unclaimable rewards 

[Sifchain.pdf](https://github.com/Sifchain/Support-Tickets/files/7886304/Sifchain.pdf)
[Sifchain.pdf](https://github.com/Sifchain/Support-Tickets/files/7886316/Sifchain.pdf)

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
Hi @LeoLondon22. The rewards distribution process takes some time to complete. Approximately 6 hours ago 258.9726027402082 ROWAN were distributed to your account. You did another claim 3 hours ago which is after the cutoff time for this week's distribution and therefore that new claim will be paid out next week. Please check your wallet account to see the tokens received.

**Comment by LeoLondon22** [comment]
Hey Adrian
Thanks for getting back to me

Can you only claim once per week, for example if my rewards reset today and
I claimed tomorrow I will only get 1 days rewards and have to wait till
next Tuesday, and the next 6 days rewards accrued will have to be claimed
the following week Tuesday?

Best regards
Leon

**Comment by emperorjm** [comment]
You can only claim once per week and the recommendation was to claim right before the cutoff time but now the Devs have implemented an auto claim feature so you will not need to create a claim anymore as the system will claim all your accumulated rewards each week. You can find this announcement here https://discord.com/channels/769209144515100693/773772812019564574/932734099788030002

**Comment by LeoLondon22** [comment]
Hey Adrian
i hope all is well

if you dont mind, i would like your help in establishing how many rewards I
have earned since entering the pool for 3 days, so i can asses moving
forward. the rewards page confuses me lol, abit messy.

[image: image.png]

your help would be much appreciated

reagrds
Leon



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by emperorjm** [comment]
It will be the sum of your Pending and Claimable amount.
