### ISSUE TITLE
Rewards

### ISSUE THREAD

**Issue by Kalabus** [Sifchain/Support-Tickets#211]
# Liquidity Mining / Rewards issue
Rewards

**Comment by emperorjm** [comment]
Hi @Kalabus. We are looking into this.

**Comment by Kalabus** [comment]
Awesome!  Thanks so much! :)

**Comment by Kalabus** [comment]
Good morning!  Just wondering if there is any update perhaps?  Sorry, just checking here every 5 minutes...a little antsy as that is a lot of money in Rewards that I would love to throw back into the pool.  Thanks again!

**Comment by Kalabus** [comment]
I had claimed my father's rewards 5 minutes later (8:42am EST Monday, 2.25 hours before cutoff), and he received his rewards around 8am Tuesday.  I still haven't received mine however, still showing as Pending Disposition.  Thanks!

https://www.mintscan.io/sifchain/txs/06FE2EEF6A2EC2A2607F363B94D34390DA3EC74816A4A8819EC1BEF960C62A74

![Father'sClaim](https://user-images.githubusercontent.com/97975820/150192778-785a04f5-c3aa-40ab-b078-28a141313ba8.jpg)

**Comment by emperorjm** [comment]
Hi @Kalabus. The Devs are looking into this issue and they'll post an update with their findings.

**Comment by Kalabus** [comment]
@emperorjm, thanks for the reply!

**Comment by Kalabus** [comment]
Good afternoon!  Is there any news about this ticket?  Thanks!

**Comment by emperorjm** [comment]
Hi @Kalabus. There was an issue that did not include your claim in the last distribution but your rewards will be paid out next week. Going forward claims will be automatically done so this issue will not happen again.

**Comment by Kalabus** [comment]
That’s very unfortunate.  That roughly $65000 of weekly rewards would have generated me over $4000 during this one week had I been able to compound them.  Will this current week’s rewards (that I do not have to manually claim) that are accumulating ALSO be released this coming Tuesday in addition the the Rewards that should have been released to me this past Tuesday?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mccallofthewild** [comment]
Hi @Kalabus thank you for your concern. It seems there may be a lag in the processing of claims. This will be fixed next week when auto-claims are enabled across all reward programs. Thank you for your patience

**Comment by Kalabus** [comment]
Will this current week’s rewards (that I do not have to manually claim) that are accumulating ALSO be released this coming Tuesday in addition to the Rewards that should have been released to me this past Tuesday?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mccallofthewild** [comment]
@Kalabus yes!
