### ISSUE TITLE
Didn't get rewards for Luna/Rowan LP

### ISSUE THREAD

**Issue by MikeCosmos** [Sifchain/Support-Tickets#214]
# Liquidity Mining / Rewards issue
Added lp Luna/Erowan don't see any rewards pending (2weeks)
## Describe the bug
Write here a clear and detailed description of what the bug is.

## Pool(s) affected
<Please write here the pool(s)you are having issues with>.
Luna/Erowan
## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.
150.81 Luna / 73952 Rowan Luna/Rowan 12.01.2022
https://www.mintscan.io/sifchain/txs/588D1FE8D97854F18D9071D8392534877721E96A954698537D65FE4B3F2E9496
## Claim transaction(s)
Please write here details on the claim transactions (amount, pairs and date) and the links to those transactions
link for my claim transaction from today 18.01
https://www.mintscan.io/sifchain/txs/B6AEF9A6C510162BF10C6266AD633B3D0CDF2C701653839B25BAE977ABE1D230
is exactly the same rewards as week ago without Luna/Rowan
Here is the link for claim transaction from last week 
https://www.mintscan.io/sifchain/txs/6A71B4718F7071B137EB8A0B6CB6A635ED63D6410E372EDFE95A5A3801EE1314
## Sif address
Please write here your sif address
sif1qldqp9qshgz3z6q8ekfp7h5yejlgrp3efraagc
## Expected Reward amount / Received amount
Please write here details on the rewards amounts you were expecting
Rewards i have i recived before added luna/erowan 18,876.49
With luna/rowan pool should be 32000
## Reward Program title
Please write here the name of the reward program you are having issues with
Sif's Luna bonus (shows nothing)
## Error logs/Screenshots
Please add here error logs you are receiving/ screenshots>
<img width="1440" alt="Zrzut ekranu 2022-01-18 o 18 50 31" src="https://user-images.githubusercontent.com/97977100/149991967-c137b6c1-9527-4e34-a4a9-e49bc9fd5518.png">
<img width="1440" alt="Zrzut ekranu 2022-01-18 o 18 54 16" src="https://user-images.githubusercontent.com/97977100/149992054-a7cdac94-54d6-4094-8b18-a014e70ef084.png">

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
Hi @MikeCosmos. The amount paid out today was 18,447.752854118138 ROWAN from your claim done 6 days ago https://www.mintscan.io/sifchain/txs/6A71B4718F7071B137EB8A0B6CB6A635ED63D6410E372EDFE95A5A3801EE1314. You received these tokens and swapped for ATOM. You made another claim 13 hours ago https://www.mintscan.io/sifchain/txs/B6AEF9A6C510162BF10C6266AD633B3D0CDF2C701653839B25BAE977ABE1D230 which is beyond the cutoff time and therefore those rewards will be paid out next week.

**Comment by MikeCosmos** [comment]
Yes,true,but amount paid 7days ago 18447 Rowan is the same what i'll recive in the next week.I recive rewards for 2 pools atom/rowan and juno/rowan. The different is that i added luna/rowan.In total pool's is around 30% more value and rewards stay the same.
<img width="1440" alt="Zrzut ekranu 2022-01-19 o 11 02 24" src="https://user-images.githubusercontent.com/97977100/150109518-26c30e05-12b2-4694-88cb-415f16048022.png">
<img width="859" alt="Zrzut ekranu 2022-01-19 o 11 09 46" src="https://user-images.githubusercontent.com/97977100/150110239-167c8b04-2ba6-4f71-8280-a2c79329dc8b.png">

**Comment by emperorjm** [comment]
Sif LUNA Bonus is an inactive program. Uncheck inactive and look only at the Sif Expansion (Which your LUNA amount will calculate under) and the Pools of the People (v3).

**Comment by MikeCosmos** [comment]
Understand sir,but can you explain rewards the same a week ago without added luna/rowan pool and now WITH luna/erowan pool. Rewards are calculated the same as week ago and the value of all pools is aprox 30%+ $ more. Is it solution to remove luna/rowan pool?
<img width="1440" alt="Zrzut ekranu 2022-01-20 o 11 19 06" src="https://user-images.githubusercontent.com/97977100/150319777-c614bafd-b548-49b6-934b-e8ec39ef2802.png">
<img width="1440" alt="Zrzut ekranu 2022-01-20 o 11 19 16" src="https://user-images.githubusercontent.com/97977100/150319806-9fd07835-da0c-4c56-815c-dace5398d739.png">

**Comment by mccallofthewild** [comment]
Hi @MikeCosmos  thank you for your concern. It seems there may be a lag in the processing of claims. This will be fixed next week when auto-claims are enabled across all reward programs. Thank you for your patience
