### ISSUE TITLE
Incorrect Hourly Rewards

### ISSUE THREAD

**Issue by cryptomasterflex** [Sifchain/Support-Tickets#215]
# Liquidity Mining / Rewards issue

## Describe the bug
Write here a clear and detailed description of what the bug is.
I monitor my hourly rewards multiple times per day. Added to ZCX/ROWAN pool twice today. After the second liquidity add, my hourly rate is now lower than prior to adding to the pools. Went from 232.94 ROWAN/hour @ 4:19 PM EST to 216.37 ROWAN/hour @ 5:18PM EST

## Pool(s) affected
<Please write here the pool(s)you are having issues with>.
ZCX/ROWAN

## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.
Added 1586.441 ZCX and 0 ROWAN (Pool was out of balance so I added more ZCX)

## Claim transaction(s)
Please write here details on the claim transactions (amount, pairs and date) and the links to those transactions

## Sif address
Please write here your sif address

## Expected Reward amount / Received amount
Please write here details on the rewards amounts you were expecting
Expecting 242.64 ROWAN/hour

## Reward Program title
Please write here the name of the reward program you are having issues with

## Error logs/Screenshots
Please add here error logs you are receiving/ screenshots>

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**
Thanks for your help!

Thanks!

**Comment by emperorjm** [comment]
Your rewards are calculated on the ROWAN value of your liquidity positions which means the price of ROWAN will affect the amount of rewards your earn. It would be difficult for you to calculate your rewards on your own without adding various variables to the mix. Rest assured your rewards are being calculated correctly.

See the "**Important notes on this program**" section of the following document https://docs.sifchain.finance/resources/rewards-programs to get a better picture of how your rewards are being calculated.

**Comment by cryptomasterflex** [comment]
Hi empororjm,

Thanks for the quick reply. I would like to respectfully disagree.
I calculate the rewards from one hour to the next to determine my hourly rate. That rate stays steady until I add or remove liquidity.

At 4:19PM I was earning 232.94/hour with 6725.2881 in accumulated ROWAN rewards so far this week
At 4:38PM I added liquidity with 1,586.41 ZCX (roughly $3,350).
At 5:02 PM Accumulated ROWAN rewards = 6941.57

1 hour difference (hourly rate) = 216.2819

7:08 PM Accumulated ROWAN rewards = 7374.4029

7374.4029 - 6941.57 = 432.8329
432.8329/2 hours = 216.2819

How could adding $3,350 in liquidity decrease the hourly rowan? It wouldn't make much sense to add liquidity if I lose out on rewards. Wouldn't Impermanent loss take place here, where I'm not losing rewards based on the value of ROWAN or the paired token? 

Other thing to note. Prior to adding to the pool at 4:38 PM, my % of the pool was 1.04%. After was 1.18%. 

As I've mentioned, I've monitored the hourly rate multiple times a day. It is a consistent rate every single hour unless liquidity is added/removed, regardless of the price of ROWAN. I have a log that I can list here if needed that shows my hour rate throughout my time using Sifchain.

Thanks again for your quick response and look forward to your reply.

**Comment by cryptomasterflex** [comment]
See attached log of my ROWAN rewards and you'll see highlighted in red where something went awry. 
[SifLog.xlsx](https://github.com/Sifchain/Support-Tickets/files/7893999/SifLog.xlsx)

**Comment by emperorjm** [comment]
Rewards for additional liquidity are not shown immediately. It usually takes over an hour to start showing on the screen. The change in price of ROEAN affects rewards earned so if the price decreases the rewards earned will decrease.

**Comment by cryptomasterflex** [comment]
**"Rewards for additional liquidity are not shown immediately. It usually takes over an hour to start showing on the screen."**
Had you reviewed the log I provided, you would clearly see this is not how the REWARDS have been calculated for the past 2 months. You can see the hourly rate remains unchanged regardless of ROWAN price until each time I added to the liquidity pools. The change in ROWAN rewards was reflected immediately the following hour each time liquidity was added.

**"The change in price of ROEAN affects rewards earned so if the price decreases the rewards earned will decrease."**
Again, had you reviewed the log you would see this is not the case. 

The price of ROWAN has decreased pretty consistently since I started pooling with sifchain 2 months ago. It has gone from about $0.17 to now around $0.13. In that timespan, my hourly rate in ROWAN rewards has never decreased until yesterday. 

I kindly request to have another set of eyes review this issue and specifically review the Excel log I provided.

**Comment by mccallofthewild** [comment]
hi @cryptomasterflex. A new sif's expansion bonus program started on the same day that your hourly earnings changed. When new bonus programs are launched, pooled amounts are reset to the true state of liquidity on the blockchain and triggers a fresh start for IL mitigation in the bonus program while continuing the IL mitigation as is for sif's expansion (all pools) as it was. Thank you for your concern and for the comprehensive details provided. Please let me know if you have any questions.

**Comment by mccallofthewild** [comment]
Otherwise closing for now.
