### ISSUE TITLE
Claimed rewards weren't distributed.

### ISSUE THREAD

**Issue by george-aj** [Sifchain/Support-Tickets#216]
# Liquidity Mining / Rewards issue
I didn't receive my rewards payout on Tuesday, just checked again and still not there, I did claim it on Monday a couple hours before the deadline.

## Claim transaction(s)
I'd rather not share publicly, please DM me for it.

## Sif address
I'd rather not share publicly, please DM me for it.

## Expected Reward amount / Received amount
I'd rather not share publicly, please DM me for it.

## Reward Program title
LUNA and JUNO pools.

## Error logs/Screenshots
I'd rather not share publicly, please DM me for it.

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
Hi @george-aj. As multiple members of the team might need collaborate to rectify an issue we use these tickets as a reference for all the details of the problems you are experiencing and therefore need as much information as possible posted to the ticket including your sif address and screenshots where possible.

**Comment by george-aj** [comment]
I don't feel comfortable with publicly disclosing my details, please come up with a better system.

**Comment by emperorjm** [comment]
@george-aj you can send me the details of the issue via discord. My username is sif_baldr.

**Comment by george-aj** [comment]
DM sent, thank you!

**Comment by mccallofthewild** [comment]
Hi @george-aj thank you for your concern. There may be a lag in the processing of claims. This will be fixed next week when auto-claims are enabled across all reward programs. Thank you for your patience
