### ISSUE TITLE
Rewards are not accurate per hour

### ISSUE THREAD

**Issue by cryptoliquid** [Sifchain/Support-Tickets#217]
# Liquidity Mining / Rewards issue
I have been compounding rewards on a weekly basis. Each week my total liquidity has increased except for this week as both ZCX and Rowan price dropped. I repool with a 50/50 split of ZCX and rowan. IL is not working as I am earning less per hour this week than last week when it should be significantly more

## Describe the bug
see above

## Pool(s) affected
ZCX

## Liquidity Add transaction(s)
Will provide via DM not public

## Claim transaction(s)
Will provide via DM not public

## Sif address
Will provide via DM not public

## Expected Reward amount / Received amount
expected should be at least 150 rowan per hour. Currently getting 130 per hour. I have tracked it in detail with excel on an hourly and daily basis

## Reward Program title
Pool of the People ZCX

## Error logs/Screenshots
Can send excel document privately 

Providing wallet info should not be public

Thanks!

**Comment by emperorjm** [comment]
Hi @cryptoliquid . As multiple members of the team might need collaborate to rectify an issue we use these tickets as a reference for all the details of the problems you are experiencing and therefore need as much information as possible posted to the ticket including your sif address and screenshots where possible

**Comment by cryptoliquid** [comment]
I am happy to send them to you via DM in discord or telegram. Post your username and platform and I'll send.
I feel it is not necessary for me to make it public. It is also not good practice for a team to only have a public platform for this sensitive information

**Comment by emperorjm** [comment]
You can send me the details of the issue via discord. My username is sif_baldr.

**Comment by emperorjm** [comment]
Will close this issue.
