### ISSUE TITLE
Claim rewards issue

### ISSUE THREAD

**Issue by mikemaiaZ** [Sifchain/Support-Tickets#218]
# Liquidity Mining / Rewards issue
**Claim rewards issue**
## Describe the bug

Write here a clear and detailed description of what the bug is.

## Pool(s) affected
<Please write here the pool(s)you are having issues with>.

## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.

## Claim transaction(s)
Please write here details on the claim transactions (amount, pairs and date) and the links to those transactions

I have claimed the rewards on pools ROWAN/ATOM at 5h PST January 17, 2022. Currently the claim is still pending. 
please help me for check this issue.

## Sif address
Please write here your sif address
sif1yx532scmxe0ggk7ry3lqfe6akw766nst0k6gd3

## Expected Reward amount / Received amount
Please write here details on the rewards amounts you were expecting
the rewards amounts: 4,291.51 ROWAN

## Reward Program title
Please write here the name of the reward program you are having issues with

## Error logs/Screenshots
Please add here error logs you are receiving/ screenshots>

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
Hi @mikemaiaZ. I have checked the records and there seems to be an anomaly and I have passed it off to the Devs to look into the issue.

**Comment by mccallofthewild** [comment]
@emperorjm there seems to be some delay between the claim being captured on the blockchain & being processed on the CE server. Starting next monday, we will be enabling universal auto-claims so this users' funds will be paid out and they will never have to worry about claiming again for the forseeable future

**Comment by mccallofthewild** [comment]
Have also asked @daechoi to add database timestamping for first entries of sifnode events

**Comment by mccallofthewild** [comment]
closing for now. will circle back if any problems arise next week
