### ISSUE TITLE
Pending Claim rewards (not yet release)

### ISSUE THREAD

**Issue by mikemaiaZ** [Sifchain/Support-Tickets#219]
# **Liquidity Mining / Rewards issu**e

## **Describe the bug**
My rewards are stuck/still pending

## Pool(s) affected
ROWAN/ATOM

## Liquidity Add transaction(s)
I claimed my rewards well before the cut off time and have received some but not all rewards.

## Claim transaction(s) 
TxHash:  9A14948385202261DD67B0D283698122676AE3473CEAB17819208B1F38CA4D15
I claimed 4,291.51 ROWAN are showing in the Claimed - Pending Dispensation and will not show up in the balances.
![image](https://user-images.githubusercontent.com/95913604/150460825-17dae637-329e-4233-9a1d-d7a566cc5f6f.png)

## Sif address
sif1yx532scmxe0ggk7ry3lqfe6akw766nst0k6gd3

## Expected Reward amount / Received amount
4,291.51 ROWAN still pending

## Reward Program title
Please write here the name of the reward program you are having issues with

## Error logs/Screenshots
Please add here error logs you are receiving/ screenshots>

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by mikemaiaZ** [comment]
Please kindly help me for check this issue.

**Comment by emperorjm** [comment]
Hi @mikemaiaZ. There was an issue with the distribution process for a few users. Your rewards will be distributed next week. Sorry for the inconvenience. Going forward you will not have this issue as all claims will be done automatically.

**Comment by mikemaiaZ** [comment]
Thanks support team, I'll wait until next week and see how it goes before I close this case.
