### ISSUE TITLE
Snapshot URL for validator setup returning 404 not found

### ISSUE THREAD

**Issue by emperorjm** [Sifchain/Support-Tickets#220]
A user is trying to pull down the snapshot using the link in the documentation https://github.com/Sifchain/sifchain-validators/blob/master/docs/nodes/setup/standalone/manual.md (sifchain.tar http://135.181.60.250:8081/sifchain/"${snapshot}") where ${snapshot} is set to "sifchain_2022-01-21.tar" but getting a 404 not found error.

**Comment by emperorjm** [comment]
The snapshot file name generated in the docs seem to be wrong. It's currently **snapshot=$(echo "sifchain_$(TZ=GMT date +'%Y-%m-%d').tar")** but should be **snapshot=$(echo "sifchain-1_$(TZ=GMT date +'%Y-%m-%d').tar")**. So the snapshot name should be sifchain-1_2022-01-21.tar http://135.181.60.250:8081/sifchain/sifchain-1_2022-01-21.tar

**Comment by emperorjm** [comment]
The following pull request should fix the docs https://github.com/Sifchain/sifchain-validators/pull/60

**Comment by ghost** [comment]
@emperorjm https://github.com/c29r3/cosmos-snapshots/blob/main/Sifchain.md
