### ISSUE TITLE
Rewards calculation is off.

### ISSUE THREAD

**Issue by LastPrime1** [Sifchain/Support-Tickets#221]
# Liquidity Mining / Rewards issue
Rewards for 200% pool does not match with 100% pool

## Pool(s) affected
Juno/Rowan

## Liquidity Add transaction(s)
Contact me on telegram for that. Or use my address below

## Claim transaction(s)
use my address below to view

## Sif address
sif1hadwx6l3lk3ajy2kqnjk5nkrjs72p7sjujtyeg

## Expected Reward amount / Received amount
about 350 rowan missing

## Reward Program title
Sif expansiion

## Error logs/Screenshots
Please add here error logs you are receiving/ screenshots>

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
Hi @LastPrime1. Can you say how you are doing the calculations? You can reference the following page to get an idea of how the rewards are calculated https://docs.sifchain.finance/using-the-website/web-ui-step-by-step/rewards

**Comment by emperorjm** [comment]
The major reason for this is that you would have been earning from v2 (Sif Expansion) and also v3 (Sif Expansion) which are both joined into Sif Expansion but the Pool of the People (v3) would only contain the v3 rewards. So if the v2 rewards from Sif Expansion are deducted the values would line up.

**Comment by LastPrime1** [comment]
![20220119_223311](https://user-images.githubusercontent.com/98266368/150989756-61a94b27-9b94-42e5-927b-d65969b83c9c.jpg)

Can you explain this?

**Comment by LastPrime1** [comment]
![20220125_092902](https://user-images.githubusercontent.com/98266368/150989899-b04f60cd-c2c5-4b92-a4e9-1600bbe64805.jpg)

Can you explain this then? Is it an addition or deduction?

**Comment by emperorjm** [comment]
Hi @LastPrime1. I'm not sure what you want me to explain. I believe my previous response would show why you can't just multiply the 100% amount on the Sif Expansion to the 200% from the pool of the people. Also if you have pools that are not in the Pool of the People but would be in the Sif Expansion that could also account for additional tokens added to the 100% Sif Expansion amount.
