### ISSUE TITLE
Claiming rewards

### ISSUE THREAD

**Issue by wordkeepa** [Sifchain/Support-Tickets#222]
Hi,
I've claimed rewards more than week ago, but didn't get any last Tuesday. And I can't claim any new rewards because button says "Pending claims". My address is sif1ug4p9pyeqnfd2kvtvgl5ulu2h7k428sytdr4vk. Please see the screenshot and advise.

![image](https://user-images.githubusercontent.com/55933816/150883465-03888168-20f4-4a8e-aad0-8c8b68df4245.png)

**Comment by emperorjm** [comment]
Hi @wordkeepa. We had an issue with distribution yesterday but distribution will be done today as the issue has been rectified. You should receive those rewards before the end of the day.

**Comment by lufa23** [comment]
hey @wordkeepa , rewards have been dispensed. (re-open this issue if this was not the case)
