### ISSUE TITLE
Claimed Rewards- Pending Dispensation 

### ISSUE THREAD

**Issue by GALAHAD2022** [Sifchain/Support-Tickets#223]
# Liquidity Mining / Rewards issue

## Describe the bug
I have 3 accounts all of them did not receive rewards. It's still pending dispensation 

## Pool(s) affected
Rowans/Atom Pool

## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.

## Claim transaction(s)

1st - 1 days ago ( 2022-01-24 15:27:26 )
2nd- 1 days ago ( 2022-01-24 15:28:25 )
3rd - 1 days ago ( 2022-01-24 15:28:02 )

## Sif address
3 address 
sif1z54ldlgmy50xfzldutzsxuze8fz5kz5lcgnllw
sif1vx7hvfrpfkyzn9q4xcuhecj4pauqlljzggnrz2
sif1vuvzqu928dt2fh4vj443slamkgxecprc0qhpej

## Expected Reward amount / Received amount
1st - 5,141.69 ROWAN
2nd - 4,867.03 ROWAN
3rd - 484.80 ROWAN

## Reward Program title
Sif's Expansion
Pools of the People (v3)

## Error logs/Screenshots

<img width="845" alt="Screen Shot 2022-01-25 at 6 19 37 PM" src="https://user-images.githubusercontent.com/98390227/150958388-69360f9a-7211-4ed8-90ff-9001192fee6c.png">

<img width="915" alt="Screen Shot 2022-01-25 at 6 19 14 PM" src="https://user-images.githubusercontent.com/98390227/150958276-38674d39-6c6e-4ad7-ad38-6aa6de14055b.png">

<img width="890" alt="Screen Shot 2022-01-25 at 6 20 26 PM" src="https://user-images.githubusercontent.com/98390227/150958490-99ff54fc-0dca-4e22-ba55-8889bf56658b.png">

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
Hi @GALAHAD2022. We had an issue with distribution yesterday but distribution will be done today as the issue has been rectified. You should receive those rewards before the end of the day.

**Comment by lufa23** [comment]
hey @GALAHAD2022 , rewards have now been dispensed

**Comment by GALAHAD2022** [comment]
thank you, received sir
