### ISSUE TITLE
Did not receive any reward on my account

### ISSUE THREAD

**Issue by kodapaul** [Sifchain/Support-Tickets#224]
# Liquidity Mining / Rewards issue

## Describe the bug
Write here a clear and detailed description of what the bug is.

## Pool(s) affected
Rowans/Atom Pool

## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.

## Claim transaction(s)
Please write here details on the claim transactions (amount, pairs and date) and the links to those transactions

## Sif address
sif1u4yjh0sxakwwzyytcfddez5qrjpen2tvf5c5mh

## Expected Reward amount / Received amount
1,481.04 ROWAN

## Reward Program title
Sif's Expansion
Pools of the People (v3)

## Error logs/Screenshots
Please add here error logs you are receiving/ screenshots>
<img width="809" alt="Screen Shot 2022-01-25 at 7 46 43 PM" src="https://user-images.githubusercontent.com/65590310/150971442-5b83f016-72ac-4cbb-98da-52de67ce40e4.png">

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
Hi @thepauldv. We had an issue with distribution yesterday but distribution will be done today as the issue has been rectified. You should receive those rewards before the end of the day.

**Comment by lufa23** [comment]
hey @thepauldv , you should have now received the rewards (feel free to open it again if not)
