### ISSUE TITLE
Export - $REGEN token cannot be exported to wallet

### ISSUE THREAD

**Issue by nimser** [Sifchain/Support-Tickets#225]
**Current behavior**
Attempting to export REGEN tokens from the Sifchain website to Regen Network using the "Export" button does not result in a Kepler wallet interaction. Instead it systematically results in the error message that follows: 

<img src="https://user-images.githubusercontent.com/634808/151182484-be3812b3-1f67-4669-9804-b3a0f8dccae8.png" width="250" height="200">

**Expected behavior**
Clicking on Export should allow to interact with Kepler to send a transaction and export REGEN tokens from Sifchain to Regen Network.

**Steps to reproduce**
1. With REGEN token in your wallet, click the "Export" button on [this page](https://dex.sifchain.finance/#/balances).
2. Confirm the export on the popup that appears.
3. Instead of opening your Kepler wallet with a transaction to pay for, the UI will directly come back to you with a "Failed to fetch" error.

**What tokens are you interacting with when this issue occurs?**
REGEN

**Comment by emperorjm** [comment]
Hi @nimser. Could you also share the error messages from the browser's console.

**Comment by emperorjm** [comment]
I was able to successfully complete both an import and export. Would love to see the error you are seeing in the console.

**Comment by emperorjm** [comment]
Another user got the following error:

![telegram-cloud-document-2-5447540238240977212](https://user-images.githubusercontent.com/1245772/151402531-f9b91bf5-914f-4f98-8b58-3302ae194b8e.jpg)

**Comment by emperorjm** [comment]
An update has been released that should fix this issue. @nimser please try again and let me know if the issue persist.
