### ISSUE TITLE
claimable rewards stuck?

### ISSUE THREAD

**Issue by nftlovers** [Sifchain/Support-Tickets#226]
# Liquidity Mining / Rewards issue

## Describe the bug
I see a claimable amount in my pools of the people v2 but it hasn't dispensed.
## Pool(s) affected
pools of the people v2

## Liquidity Add transaction(s)
B24C7E36C0AF6797C0F4E400747845B91AD77B0593F201A724A59B9B3A07600C ETH/Rowan 12/25/2021

## Sif address
sif17du53vjwt0tvmuhz3m3myfrwgmxzw6d5rv3ull

## Expected Reward amount / Received amount
48011

## Reward Program title
Pools of the People (v2)

**Comment by emperorjm** [comment]
Hi @nftlovers. Dispensations are done between Monday and Tuesday. So those accumulated rewards will be automatically dispensed on those days next week.

**Comment by nftlovers** [comment]
Ok they were from the v2 pool shouldn't that have dispensed already?
    On Friday, January 28, 2022, 05:51:21 AM PST, Adrian Thompson ***@***.***> wrote:  
 
 


Hi @nftlovers. Dispensations are done between Monday and Tuesday. So those accumulated rewards will be automatically dispensed on those days next week.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by emperorjm** [comment]
Can you share full screenshots of what you are seeing on the rewards screen as I am seeing all the v2 rewards distributed to your account. All rewards accumulated after the 25th will be paid out next week.

**Comment by nftlovers** [comment]
So the claimable 48011 was what I am referring to.



    On Friday, January 28, 2022, 11:27:46 AM PST, Adrian Thompson ***@***.***> wrote:  
 
 


Can you share full screenshots of what you are seeing on the rewards screen as I am seeing all the v2 rewards distributed to your account.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by emperorjm** [comment]
Hi @nftlovers. Can you send screenshots of what you are seeing on the rewards screen? On 2022-01-25 **332.9751966663421 ROWAN** was paid out for Pools of the People and on 2022-01-26 **208.5734053171389 ROWAN** for Sif Expansion.

**Comment by nftlovers** [comment]
I sent you the screenshot in the last email
    On Friday, January 28, 2022, 01:58:04 PM PST, Adrian Thompson ***@***.***> wrote:  
 
 


Hi @nftlovers. Can you send screenshots of what you are seeing on the rewards screen? On 2022-01-25 332.9751966663421 ROWAN was paid out for Pools of the People and 208.5734053171389 ROWAN for Sif Expansion.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by emperorjm** [comment]
I'm not seeing a screenshot in any of your posts.

**Comment by nftlovers** [comment]
That's strange. I added as attachment on this email.Not sure why it wasn't showing up for you on your email chain.
    On Saturday, January 29, 2022, 06:55:01 AM PST, Adrian Thompson ***@***.***> wrote:  
 
 


I'm not seeing a screenshot in any of your posts.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by emperorjm** [comment]
Hi @nftlovers. You should have received your rewards in the last distribution. I'll close this issue but if you didn't receive the tokens you can re-open the issue.
