### ISSUE TITLE
My sifchain wallet got hacked

### ISSUE THREAD

**Issue by babychoux13** [Sifchain/Support-Tickets#227]
**Describe the bug**

I was staking my sifchain with keplr pc version and i just found out my wallet got hacked

i have no idea how hacker hacked it but from 4 days ago, hacker claimed all reward and withdrawn it in every hour

The only change was installing official keplr android mobile app recently from keplr.app and before installing it, i only used pc with no problems.

i just unstaked all my asset but also worried that hacker steal my asset when it unstake after 21 days.

And from mintscan, I found out hacker sent 300 rowan to use it for transaction fee which i had none(so i was unable to claim my reward) and swapped rowan to atom then withdrawn it. 

What should I do to protect my asset?

My wallet addresses are
Sifchain : sif1q8qxuu9ekctskqla8dqsvplprhdqxa3hml09wr
Atom : cosmos1q8qxuu9ekctskqla8dqsvplprhdqxa3h7zqnpg

And my email address is babychoux13@gmail.com

Plz help us. I invested a lot to rowan...

During I write this report, scammer sent 1 rowan to my wallet to prepare hack my unbonding rowan.

https://www.mintscan.io/sifchain/account/sif1988lcruvlthwcx5pgfccm6jyr07uuaag98sz4y

This is the scammer's address and you can check there are 9789 rowan is my interest from staking.

**How to Reproduce**

4. See error "..."

**Expected behavior**
<Please write a clear and detailed description of what you expected to happen.>

**TX Hashes** (if applicable)

Please provide links to transaction hashes of the import / export issues you are facing

**Addresses** (if applicable
<Please provide links to your addresses (both of Sifchain and external chain)>

[My wallet]
1. Sifchain
https://www.mintscan.io/sifchain/account/sif1q8qxuu9ekctskqla8dqsvplprhdqxa3hml09wr
2. Atom 
cosmos1q8qxuu9ekctskqla8dqsvplprhdqxa3h7zqnpg

[Scammers wallet]
https://www.mintscan.io/sifchain/account/sif1988lcruvlthwcx5pgfccm6jyr07uuaag98sz4y

**Error logs**
<Please provide links to your addresses (both of Sifchain and external chain)>

**Screenshots**

**Providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
Hi @babychoux13. I'm sorry to hear that your wallet got hacked. Once someone has your private keys that person has full access and control of the accounts under that key and there is literally nothing that we can do as we have no control over your account. The only recommendation I can give is to try to transfer your tokens to another wallet account before the hacker does.

**Comment by babychoux13** [comment]
https://twitter.com/L1am_Crypto/status/1487385014656458758?t=d2XIFyuFUBgmayXkvFOJVg&s=19

this is exactly the situation I am suffering

I have no idea for exact time of getting my fund at the unbonding date and
in that twitter thread, they are mentioning the possibility to get fund
back with script bot

Can you check this thread with replies too?

This 780k rowan is so precious asset to me..

2022년 1월 29일 (토) 오전 6:55, Adrian Thompson ***@***.***>님이 작성:

**Comment by emperorjm** [comment]
As the thread reads you will need to transfer the tokens from your account to another account before the hacker does as soon as the unbonding period ends. As I said before there is nothing we can do in this regards.

**Comment by babychoux13** [comment]
But if you read the replies from the thread, they are mentioning estimating
the exact unbonding time and creating bot to move that fund faster than
hacker. They are mentioning some kind of script bot, block creation time
that I cannot understand fully. Then at least, can I figure out exact time
that the unbonding completes and returns to my wallet?

2022년 1월 30일 (일) 오후 10:18, Adrian Thompson ***@***.***>님이 작성:
