### ISSUE TITLE
IMPORT - $JUNO token cannot be imported in Sifchain

### ISSUE THREAD

**Issue by Kubas77** [Sifchain/Support-Tickets#230]
**Describe the bug**
Current behavior
Trying to import JUNO tokens from the JUNO Network to Sifchain using the "Import" button has no result. Instead, it systematically results in the following error message:

![Снимок экрана 2022-02-01 в 21 46 49](https://user-images.githubusercontent.com/98842587/152035295-19d0765b-666c-470d-be11-27de9774cd94.jpeg)
**How to Reproduce**

1 With the JUNO token on the JUNO Network, click on the "Import" button in the balance section.
2 Confirm the import in the pop-up window that appears.
3 Confirm the import in the Keplr popup that appears
4 An error message pops up**Expected behavior**

Expected Behavior
Clicking on "Import" should allow you to interact with Kepler to send a transaction and import JUNO tokens from JUNO Network to Sifchain

**Screenshots**

**Comment by emperorjm** [comment]
Hi @Kubas77. Can you attach a screenshot of the error shown in your console as well and your sif address.

**Comment by Kubas77** [comment]
Hi, no problem
![Снимок экрана 2022-02-01 в 20 18 59](https://user-images.githubusercontent.com/98842587/152059038-cbd17f37-b591-498b-8b69-cb5368098dcf.jpeg)
this is what you need?

**Comment by Kubas77** [comment]
now Sifchain is being updated, perhaps the problem was related to this

**Comment by emperorjm** [comment]
@Kubas77 let me know if you are still having the issue after the upgrade.

**Comment by Kubas77** [comment]
the problem is still present, the error has not gone away

**Comment by Kubas77** [comment]
@emperorjm the problem is still present, the error has not gone away

**Comment by lufa23** [comment]
@Kubas77 it works for me,
are you using a VPN?
are you using google chrome?

**Comment by emperorjm** [comment]
I just tried as well and both export and import features are working. Try clearing your cache and restart your browser and try again.
