### ISSUE TITLE
still some claimable amount  in "pools of the people (v2)"

### ISSUE THREAD

**Issue by imjaychow** [Sifchain/Support-Tickets#232]
# Liquidity Mining / Rewards issue

there are still some claimable amount  in "pools of the people (v2)" from my rewards page, it stay there for around 3 weeks already

## Pool(s) affected

not sure

## Liquidity Add transaction(s)
NA

## Claim transaction(s)
NA

## Sif address

sif18xxvy9mzvhyzkftj7w9ldqy7t4nwx8durrkmkz

## Expected Reward amount / Received amount

364.1304

## Reward Program title

pools of the people (v2)

## Error logs/Screenshots

![poolsv2](https://user-images.githubusercontent.com/98966603/152371456-701f9d5b-3b1a-46d2-9355-25828e307a68.png)

Thanks!

**Comment by emperorjm** [comment]
We are looking into this issue.

**Comment by emperorjm** [comment]
Hi @imjaychow. The amount outstanding would have been paid. Please let me know if you still seeing an outstanding amount.

**Comment by imjaychow** [comment]
thx, no more outstanding amount in v2, but now there is  another bug, the amount of "dispensed rewards" seems wrong

**Comment by imjaychow** [comment]
> Hi @imjaychow. The amount outstanding would have been paid. Please let me know if you still seeing an outstanding amount.

the amount of "dispensed rewards" remain wrong, so are there anyone reviewing the issue?
