### ISSUE TITLE
Not all rewards due were dispensed

### ISSUE THREAD

**Issue by bitshi** [Sifchain/Support-Tickets#233]
# Liquidity Mining / Rewards issue

## Describe the bug
Write here a clear and detailed description of what the bug is.

This past Tuesday I received less than half of combined Pools and Expansion rewards due to one Sif address. 

## Pool(s) affected
<Please write here the pool(s)you are having issues with>.

Over last week, I was in & out of several pools, including JUNO, RNDR, AKT, LUNA, ETH.

## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.

## Claim transaction(s)
Please write here details on the claim transactions (amount, pairs and date) and the links to those transactions

## Sif address
sif1tnasd2ucd22jgl8ermkkhder6h8y3yftea29wu

## Expected Reward amount / Received amount
Please write here details on the rewards amounts you were expecting

Going by memory, between 4100 and 4500 ROWAN were due to be dispensed, and I actually received 1900 something.

## Reward Program title
Please write here the name of the reward program you are having issues with

Rewards/bonuses from Expansion and Pools were due, nothing else. (Going just by memory of the accruing amounts, it may be that the Expansion portion was dispensed but not the Pools' portion.)

## Error logs/Screenshots
Please add here error logs you are receiving/ screenshots>

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
HI @bitshi. Based on the records in the last distribution you received 2,423.0722612888358 ROWAN from the Pools of the People and 1,889.4415031348065 from Sif Expansion.

**Comment by bitshi** [comment]
Haven’t actually seen the Pools portion…

Are Pools’ rewards sent out separately from Expansion?

What records are you referring to? Are they onchain, can I look them up?

Thanks

**Comment by bitshi** [comment]
hi, thanks but I don’t see the txs on mintscan: do the payout txs have any
easily searchable attributes like tx type or sender address?

**Comment by emperorjm** [comment]
The transactions are not currently being displayed on Mintscan but their team is working to have them displayed.
