### ISSUE TITLE
Reward issue

### ISSUE THREAD

**Issue by Zimgus** [Sifchain/Support-Tickets#235]
# Liquidity Mining / Rewards issue
My reward payout has reduced from 243 Rowan p/hour to 113 Rowan p/hour.

## Pool(s) affected
<Rowan/atom pool

## Liquidity Add transaction(s)
![Uploading F380C212-134E-4125-A9D9-A9F48424EFD1.jpeg…]()

## Claim transaction(s)
I entered the Rowan/Atom pool on the 03.02.21.
I added 500.23 atom and 197,499 Rowan. With a 0.34% pool share.

## Sif address
sif102mfdnr4crwvx04y2lcsd499nnxecx06u537wz

## Expected Reward amount / Received amount
I started receiving 243 Rowan p/hour in rewards for the first day. 
my rewards have now reduced to 113 Rowan p/hour.
This is a significant reduction of nearly 21,000 Rowan in rewards p/week.
Please can you look into this?

## Reward Program title
Rowan /atom 
Sif's expansion 100% 
Pools of the people 200%

Thank you
Gus

**Comment by emperorjm** [comment]
Hi @Zimgus. Impermanent Loss and price fluctuations affect the amount of rewards earned. The following document tries to explain how rewards are calculated https://docs.sifchain.finance/using-the-website/web-ui-step-by-step/rewards
