### ISSUE TITLE
Pools of the People (v3) reward not received. 

### ISSUE THREAD

**Issue by sheru-pan** [Sifchain/Support-Tickets#237]
# Liquidity Mining / Rewards issue

## Describe the bug
On the last reward distribution as there is automatic reward distribution is triggered. I have not done this manually. As I can remember My reward was 1K+ Rowans but In my wallet on 300+ rowans are added. It seems the Pools of the People (v3) reward is not rewarded to my wallet. 

## Pool(s) affected
Not Sure. 

## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.

## Claim transaction(s)
ROWAN/USDC , ROWAN/ATOM , I have not maid any claim. Its on auto reward. 

## Sif address
sif1rhttpxwxpfpfkpfnktgzuzvxu2mmyaakeek5hn

## Expected Reward amount / Received amount
The expected rewarded amount was near about 1100 Rowan and the received amount was 300+ Rowans. 

## Reward Program title
Pools of the People (v3)

## Error logs/Screenshots
![image](https://user-images.githubusercontent.com/60152441/153054371-16614063-dc8d-40c4-a69a-7121c7c26a33.png)

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
Hi @pycyber. From the last distribution, you received 348.7272921845974 ROWAN for Sif Expansion and 697.9876353577552 ROWAN for Pools of the People (v3). From our records, all the payouts made to your account comes to a total of 1820.296562151874966 but rounded up in the screenshot to 2 decimal places. The claimable amounts being shown now are what you've earned from the start of the new distribution week.

**Comment by sheru-pan** [comment]
Thank you @emperorjm for your kind reply. I received the reward of Sif Expansion in my wallet but the reward for Pools of the People (v3) is not added to my wallet. Which is 697.9876353577552 amount of ROWAN. What should I do to receive the reward of Pools of the People (v3) into my wallet. Thanks in advance for your kind support.

**Comment by emperorjm** [comment]
As stated above the total amount for both programs were distributed to your account. The transactions are not viewable on Mintscan right now but their team is working on that but we have our internal system that queries the blockchain and the full amounts were distributed to your account.

**Comment by sheru-pan** [comment]
@emperorjm Can you please share the link where I can see my updated amount for my wallet. If the distribution is transferred to my wallet address. Then why I am not able to see this in my wallet. 
Its bit confusing for me as well I am not able to trust the 300% reward programs. because I am only getting 100%. I am testing this platform with a smaller amount. How this is working. 
As this issue was closed but the actual issue was not resolved. Can you please share the link of the related issue `The transactions are not viewable on Mintscan right now but their team is working on that` this will help me to track my actual issue. Thank you

**Comment by emperorjm** [comment]
The pools of the people amount was transferred 2022-02-08 01:37:14.916 -0500 (697.9876353577552 ROWAN) and you added liquidity of 1,120 ROWAN some minutes after that transfer https://www.mintscan.io/sifchain/txs/FB38B9D38812614E9142C2DC36B3B395E760F21F6B0DBF7716EFF9BB261B6037. A few hours later 2022-02-08 03:11:45.298 -0500 the Sif Expansion amount was transferred (348.7272921845974 ROWAN) and we see that you have not done any transaction since and so you have 351.564821 ROWAN available in your account.

As I said above Mintscan currently does not show the actual transfers but the mintscan team is working on this. We however have our own internal system to queries the blockchain events to show when each transfer was done.

**Comment by sheru-pan** [comment]
If there any explorer where I can see my transaction history. That will be a great help for me. Thanks

**Comment by emperorjm** [comment]
No. Mintscan currently does not show the actual transfers but the mintscan team is working on this.

**Comment by sheru-pan** [comment]
Thanks a lot. 😃
