### ISSUE TITLE
Rewards not receieve week 2-9 feb

### ISSUE THREAD

**Issue by Mourmansk** [Sifchain/Support-Tickets#238]
# Liquidity Mining / Rewards issue

## Describe the bug
Pool of the people rewards not receive this week 
## Pool(s) affected
<Please write here the pool(s)you are having issues with>.

## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.

## Claim transaction(s)
Please write here details on the claim transactions (amount, pairs and date) and the links to those transactions

## Sif address
Please write here your sif address

## Expected Reward amount / Received amount
Please write here details on the rewards amounts you were expecting
880 rowan never hit my keplr wallet, data went to 0 on the dex dashboard 'Claimed - Pending Dispensation'

## Reward Program title
Pool of the people

## Error logs/Screenshots
<img width="797" alt="image" src="https://user-images.githubusercontent.com/99346347/153232310-25ac2563-e070-4b2e-808d-f70a9496e80a.png">

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by Mourmansk** [comment]
sif1cg8fn3lmn5u8qsr3ut9pzjya2ej68s5nh2fudv

**Comment by emperorjm** [comment]
Hi @Mourmansk. From the last distribution, you got 583.8949005904982 ROWAN from Pools of the People (v3) and 296.13464183392625 ROWAN from Sif Expansion. Both amounts were transferred to your wallet. I'm seeing where you used almost all the amount earned to purchase ATOMs https://www.mintscan.io/sifchain/txs/6D7B4BCB05D7A77854AC430C532560AD1729E3BDF1EB3C2F0046ED25C8995E58

**Comment by Mourmansk** [comment]
Hello,

Are you sure ? because I think this transaction is related to rowan that were already in my wallet from the previous week 
reward batch. Also the data in the dashboard was displaying 5000+ rowans now it's down to 3000+. 
Do you have a mintscan link with the rewards activity, not the keplr activity ?
thanks

**Comment by emperorjm** [comment]
Currently, the distribution transactions are not shown on Mintscan but the team is working on this but we have our own internal system query the blockchain which shows that an account receives the amount from a distribution and the full amount was distributed to your account.

**Comment by Mourmansk** [comment]
thank you
