### ISSUE TITLE
Rewards not calculated correctly for Luna pools since 6 Feb. IL mitigation dissapeared (probably)

### ISSUE THREAD

**Issue by antonymous-a** [Sifchain/Support-Tickets#239]
# Liquidity Mining / Rewards issue

## Describe the bug
After being in Luna pool for a long time (more than a month) constantly adding/removing liquidity and reinvesting Rowan rewards in that pool, I had to remove more than 90% of the pool between 4-6 Feb. Until 6-Feb the rewards were calculated OK and I received the proper auto-claim amount. Since 6 Feb the rewards do not add up leaving me thinking there is a bug.

## Pool(s) affected
Luna pool

## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.

## Claim transaction(s)
Please write here details on the claim transactions (amount, pairs and date) and the links to those transactions

## Sif address
Please write here your sif address

## Expected Reward amount / Received amount
At ~200 Luna in pool I received ~72 Rowan/h
At ~150 Luna in pool I received ~50 Rowan/h
Until 02.06, at ~15 Luna in pool I received ~10 Rowan/h (I guess IL mitigation has kicked in heavily by that point since I would expect half of those rewards)
... So far so good ...
Since 02.06, at ~15 Luna in pool I have received **3.5 Rowan in total**. This means it is around ~1 Rowan per DAY and doesn't compare to the rewards I was receiving before the Magnolia upgrade.

## Reward Program title
Sif expansion
Pools of the people v3

## Error logs/Screenshots
![image](https://user-images.githubusercontent.com/57235266/153404191-b0999ccc-c61b-4978-b022-e9f4013fdce3.png)

I can try to find the add/remove liquidity tx's and also post the sifchain address if needed.

Thanks!

**Comment by emperorjm** [comment]
Hi @antonymous-a. Impermanent Loss protection resets for each new program. So the IL protection that you had ib v2 will not be available in v3.

**Comment by antonymous-a** [comment]
That's unfortunate and really strange tbh. Still the rewards seem skewed even with no IL protection

**Comment by emperorjm** [comment]
For an idea of how the rewards are being calculated you can reference this doc https://docs.sifchain.finance/using-the-website/web-ui-step-by-step/rewards

**Comment by antonymous-a** [comment]
Yes, I used this formula and it shows that I should receive ~6.6 Rowan per hour. You can see in the screenshot how much is accumulated for this weekly epoch.

**Comment by emperorjm** [comment]
It's really difficult to calculate the amount of ROWAN you will earn per hour without taking into the constant change of the ROWAN price. "The value of your Liquidity Position (valued in Rowan) changes depending on the fluctuation of Rowan price". If you add liquidity asymmetrically your total rowan value might be less than what was added as well. So there are a lot of variables involved. I want to assure you that the rewards being earned are correct.

**Comment by antonymous-a** [comment]
Where can I see the current value of my LP (valued in rowan)? My assumption is that it is shown in the pool stats as "Your liquidity".

**Comment by lufa23** [comment]
hey, right now you can just see the value of LP valued in USD (in the[ pool page](https://dex.sifchain.finance/#/pool) under the field "Your Pool Value"
