### ISSUE TITLE
the amount in Dispensed Rewards are decreased about  200k

### ISSUE THREAD

**Issue by 4misscindylou** [Sifchain/Support-Tickets#240]
# Liquidity Mining / Rewards issue

## Describe the bug
Write here a clear and detailed description of what the bug is.
before the latest reward dispense my total reward dispensed is shown for 886k but after that it shows 676k
## Pool(s) affected
<Please write here the pool(s)you are having issues with>.

## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.

## Claim transaction(s)
Please write here details on the claim transactions (amount, pairs and date) and the links to those transactions

## Sif address
Please write here your sif address
sif1x54sxcn9edfe2cka525f6v9uu5qps53wqctqt2
## Expected Reward amount / Received amount
Please write here details on the rewards amounts you were expecting

## Reward Program title
Please write here the name of the reward program you are having issues with

## Error logs/Screenshots
Please add here error logs you are receiving/ screens
<img width="1440" alt="Screen Shot 2022-02-11 at 5 04 25 PM" src="https://user-images.githubusercontent.com/96751606/153670142-24e9383d-a533-4e8c-9c59-c84563687120.png">
hots>

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!
<img width="1440" alt="Screen Shot 2022-02-11 at 5 04 25 PM" src="https://user-images.githubusercontent.com/96751606/153669983-c6a41677-c701-4a00-b6fe-bf863f76f895.png">

**Comment by lufa23** [comment]
hey @4misscindylou , rewards dispensation follow the same dynamic regardless of the pool.

The value of your Liquidity Position (valued in Rowan) changes depending on the fluctuation of Rowan price. It's really difficult to manually calculate the amount of ROWAN you will earn per hour, as you need to take into account the continuous change of the ROWAN price. So if ROWAN prices decrease during an hour, your Rewards for that hour would decrease too (as they are calculated on the Rowan value of your liquidity position in that hour).

So it is not advisable to try to calculate manually the rewards, as you would need to take into account every hourly variation of Rowan price through the whole week.

As dispensation run smoothly, we can be confident in saying that rewards have been correctly dispensed

**Comment by 4misscindylou** [comment]
Ok thanks for explain. But  like I mentioned before in my UI where shows
Dispensed Rewards amount already claimed and received shows 676,890.49
ROWAN This number is about 200k Rowan short than my week before it was
886kish ROWAN that’s before last week the rewards which was about 200k
Rowan. The number should over 1m Rowan now. I am not the only one has that
issue some one also mentioned it in the chat room. Thanks

**Comment by lufa23** [comment]
yeah you're right about the UI bug,..We're looking into it

**Comment by mccallofthewild** [comment]
@4misscindylou the data processing for previous bonus programs has been shut off / deprecated so those dispensed amounts are no longer showing up in your total dispensed amounts.
