### ISSUE TITLE
I am getting less rewards than last week even tho I compound my reward every week 

### ISSUE THREAD

**Issue by 4misscindylou** [Sifchain/Support-Tickets#241]
# Liquidity Mining / Rewards issue

## Describe the bug
I am getting less rewards than last week even tho I compound my reward every week. My last week rewards was 200k+ I just do the calculation for this week my rewards is going to be around 189350 which is lower then last week 200k+. I should have more than 200K at least plus the rewards I compound  which is I put all the 200k back into the atom/erowan pool. also in my UI where Dispensed Rewards shows only 676,890.49 ROWAN but last week before I claim the reward it was 880K already ? The number should be over 1m+ 

## Pool(s) affected
<Please write here the pool(s)you are having issues with>.

## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.

## Claim transaction(s)
Please write here details on the claim transactions (amount, pairs and date) and the links to those transactions

## Sif address
Please write here your sif address

sif1x54sxcn9edfe2cka525f6v9uu5qps53wqctqt2

## Expected Reward amount / Received amount
Please write here details on the rewards amounts you were expecting

## Reward Program title
Please write here the name of the reward program you are having issues with

## Error logs/Screenshots
Please add here error logs you are receiving/ screenshots>
<img width="1440" alt="Screen Shot 2022-02-11 at 5 04 25 PM" src="https://user-images.githubusercontent.com/96751606/153672661-112f179f-22d9-4066-b73b-5caf2f8a4183.png">

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by antonymous-a** [comment]
I would reference this here https://github.com/Sifchain/Support-Tickets/issues/239

**Comment by 4misscindylou** [comment]
I don’t have Luna pool

**Comment by lufa23** [comment]
hey @4misscindylou , rewards dispensation follow the same dynamic regardless of the pool.

The value of your Liquidity Position (valued in Rowan) changes depending on the fluctuation of Rowan price. It's really difficult to manually calculate the amount of ROWAN you will earn per hour, as you need to take into account the continuous change of the ROWAN price. So if ROWAN prices decrease during an hour, your Rewards for that hour would decrease too (as they are calculated on the Rowan value of your liquidity position in that hour). 

So it is not advisable to try to calculate manually the rewards, as you would need to take into account every hourly variation of Rowan price through the whole week.

As dispensation run smoothly, we can be confident in saying that rewards have been correctly dispensed
