### ISSUE TITLE
Import / Export issue

### ISSUE THREAD

**Issue by tindang17-code** [Sifchain/Support-Tickets#245]
## Describe the bug
Describe the bug
A Detailed description of the issue (what happened, token affected and token amount)
I exported about 12 Atom from the sifchain (sif1sm3tsmf9k4ax4yhm033crzkt88jpy27xvvcc43) to Kepler (cosmos1sm3tsmf9k4ax4yhm033crzkt88jpy27xf3hw66), the transaction hung at first for 1minutes, and then it shows fail to fetch, I left some rowan for fee deduction as well.

![Screen Shot 2022-02-13 at 2 29 25 AM](https://user-images.githubusercontent.com/84979532/153725552-f36638f7-8463-43f6-8424-b9424fe7d825.png)

Thanks!

**Comment by lufa23** [comment]
hey, the IBC channel experienced some delays..
I will close this issue, as everything works fine now
