### ISSUE TITLE
Rewards Issue

### ISSUE THREAD

**Issue by Kalabus** [Sifchain/Support-Tickets#246]
# Liquidity Mining / Rewards issue

## Describe the bug
On my wallet and my father's, I see that "Claimed - Pending Dispensation" only shows 2/3 of the total Rewards.  For some reason, "Sif's Expansion" is grayed out, and that amount is still listed as "Claimable".  This is also the same for my girlfriend's wallet that I manage.

Additionally, the Pools page only shows the 200%, and not the additional 100% Sif's Expansion values.

## Pool(s) affected
ATOM/ROWAN

## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.

## Claim transaction(s)
Please write here details on the claim transactions (amount, pairs and date) and the links to those transactions

## Reward Program title
Sif's Expansion

## Error logs/Screenshots

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!
-Kalabus

**Comment by emperorjm** [comment]
Hi @Kalabus. This is an issue the Devs are currently looking into and the distribution will be put on hold until the issue is rectified.

**Comment by Kalabus** [comment]
Great!  Thank you so much for the quick reply!

**Comment by Kalabus** [comment]
I removed sensitive information for privacy, since this issue isn't just isolated to myself.  Thanks again!
