### ISSUE TITLE
the amount in "Dispensed Rewards" is not correct

### ISSUE THREAD

**Issue by imjaychow** [Sifchain/Support-Tickets#247]
# Liquidity Mining / Rewards issue
the amount in "Dispensed Rewards" is not correct, cant confirm the exact number, it should be around 500k as i remember, but its now showing around 300k only (I had received correct amount of rowan in my wallet, its just a UI bug)

## Pool(s) affected
not sure

## Liquidity Add transaction(s)
NA

## Claim transaction(s)
NA

## Sif address
sif18xxvy9mzvhyzkftj7w9ldqy7t4nwx8durrkmkz

## Expected Reward amount / Received amount
should be around 500k as i remember, but its now showing less than 300k

## Reward Program title
not sure

## Error logs/Screenshots

Thanks!

**Comment by lufa23** [comment]
hey, yup we've been experiencing some UI glitches..gonna get back to you on this

**Comment by mccallofthewild** [comment]
@imjaychow the old bonus programs have been deprecated so your previously dispensed amounts should have decreased.
