### ISSUE TITLE
rewards getting lower

### ISSUE THREAD

**Issue by dana-nomad** [Sifchain/Support-Tickets#253]
This ticket didn't send from bot for some reason. You can find user in discord room #9

SifTickets
BOT
 — Yesterday at 11:52 PM
Please write a detailed description of the issue.
DraTiger — Today at 12:11 AM
Hello how are you nice job! I have some situation. I think my apy rewards are less in compare with last 3 weeks now i count +-950 Rowan a day before was +- 1300 and i didint remove any liq . my sif sif1hhp7s5wzy04e6xju4dak0nnjqml24wsecgf4yw can you please check it out greetings
SifTickets
BOT
 — Today at 12:11 AM
What is the name and amount of the token affected?
DraTiger — Today at 12:11 AM
ROWAN
SifTickets
BOT
 — Today at 12:11 AM
What is your Sifchain address?
DraTiger — Today at 12:12 AM
sif1hhp7s5wzy04e6xju4dak0nnjqml24wsecgf4yw
SifTickets
BOT
 — Today at 12:12 AM
What is your address on the other chain?
DraTiger — Today at 12:12 AM
0x73362776338f356BdC13c91CbeBa23CEAC8a7ADe
SifTickets
BOT
 — Today at 12:12 AM
What is the link to the transaction has you are having problem with?
DraTiger — Today at 12:12 AM
no have is about rewards
SifTickets
BOT
 — Today at 12:12 AM
Are there any error logs you can share?
DraTiger — Today at 12:12 AM
no
DraTiger — Today at 5:48 AM
Hello
this go down sinds 3 days ago when they had problem with apy and few hours was 200%
i count now it is +- 1,011 Rowan a day before was +- 1,285 a day 3 weeks, yes i pool 50/50
thank you for your help
nomad sif دانا — Today at 8:11 AM
Ok I am going to send this ticket to our DEVs. They will be in touch shortly. I will be checking in to make sure you get taken care.
@DEVs

**Comment by lufa23** [comment]
Hey! So few things to keep into consideration when it comes to calculating your rewards:


- The value of your Liquidity Position (valued in Rowan) changes depending on the fluctuation of Rowan price. It's really difficult to forecast or manually calculate the amount of ROWAN you will earn per hour, as you need to take into account the continuous change of the ROWAN price. So if ROWAN prices decrease during an hour, your Rewards for that hour would decrease too (as they are calculated on the Rowan value of your liquidity position in that hour).

- It is not advisable to try to calculate manually the rewards (or forecast rewards amount based on previous distributions), as you would need to take into account every hourly variation of Rowan price through the whole week.

From our records dispensation run smoothly, we can be confident in saying that rewards have been correctly dispensed
