### ISSUE TITLE
hey this didn't send

### ISSUE THREAD

**Issue by dana-nomad** [Sifchain/Support-Tickets#255]
SifTickets
BOT
 — Today at 6:59 PM
Please write a detailed description of the issue.
berno131395 — Today at 7:00 PM
Hello. I transfered Atom to my account but the transaction is still pending after a while. Also there was a message "transaction timed out" on sifchain website. Here is a link:

https://www.mintscan.io/cosmos/txs/569FAB529F7C6498D175AA716E4C6DEAF3856635DF8485C031A44770930361A4

Thank you
[Mintscan - Chain explorer by COSMOSTATION](https://www.mintscan.io/cosmos/txs/569FAB529F7C6498D175AA716E4C6DEAF3856635DF8485C031A44770930361A4)[](https://www.mintscan.io/mintscan.png)
Cosmos explorer powered by Cosmostation, Supports Cosmos, Kava, Iris, Starname. Kava Explorer. Iris explorer. Starname explorer.
Image
SifTickets
BOT
 — Today at 7:00 PM
What is the name and amount of the token affected?
berno131395 — Today at 7:01 PM
363.239490 Atom
SifTickets
BOT
 — Today at 7:01 PM
What is your Sifchain address?
berno131395 — Today at 7:02 PM
sif1awmz585mrzvyexnawkrvu3n7dzlecdys475t2g
SifTickets
BOT
 — Today at 7:02 PM
What is your address on the other chain?
berno131395 — Today at 7:04 PM
cosmos1awmz585mrzvyexnawkrvu3n7dzlecdyssrma9r
SifTickets
BOT
 — Today at 7:04 PM
What is the link to the transaction has you are having problem with?
berno131395 — Today at 7:04 PM
https://www.mintscan.io/cosmos/txs/569FAB529F7C6498D175AA716E4C6DEAF3856635DF8485C031A44770930361A4
[Mintscan - Chain explorer by COSMOSTATION](https://www.mintscan.io/cosmos/txs/569FAB529F7C6498D175AA716E4C6DEAF3856635DF8485C031A44770930361A4)[](https://www.mintscan.io/mintscan.png)
Cosmos explorer powered by Cosmostation, Supports Cosmos, Kava, Iris, Starname. Kava Explorer. Iris explorer. Starname explorer.
Image
SifTickets
BOT
 — Today at 7:04 PM
Are there any error logs you can share?
berno131395 — Today at 7:05 PM
no
nomad sif دانا — Today at 7:10 PM
Hey one minute
looking into it
Would you mind if while I wait for a response from the team I invite our helpful community members to this ticket?
berno131395 — Today at 7:14 PM
It's ok. You can invite them.
nomad sif دانا — Today at 7:16 PM
@helpful people
@DEVs
ChickenMcPluckU — Today at 7:17 PM
Seems there is a relayer issue to cosmoshub at the moment: https://discord.com/channels/769209144515100693/890703929178996797/944432224730751026 
Probably should notify the team.
nomad sif دانا — Today at 7:17 PM
ty!
SifTickets
BOT
 — Today at 7:18 PM
You are not able to use this command.
Only you can see this • [Dismiss message]()
nomad sif دانا — Today at 7:33 PM
damn the ticket didn't send
let me saend manually

**Comment by lufa23** [comment]
closing this tickets as packets are going through as per [ibc-status](https://discord.com/channels/769209144515100693/890703929178996797)
