### ISSUE TITLE
Import / Export issue

### ISSUE THREAD

**Issue by ivorychristine** [Sifchain/Support-Tickets#260]
## Describe the bug

Osmo import/export not working. Balance just keep on loading

A Detailed description of the issue (what happened, token affected and token amount)

## How to Reproduce

4. See error "..."

## Expected behaviour
Please write a clear and detailed description of what you expected to happen.

Osmo import/export not working. Balance just keep on loading

## TX Hashes
Please provide links to transaction hashes of the import / export issues you are facing

## Addresses
Please provide links to your addresses (**both** of Sifchain and external chain)

## Error logs
Please provide links to your addresses (both of Sifchain and external chain)
Error Log from one of the community members

## Screenshots

**Providing as much detail as possible will help engineers to solve the case faster..**

Thanks!
![2022-02-23 03 08 01](https://user-images.githubusercontent.com/94232457/155201910-d788f4e1-e471-46cd-a4bb-ba9a51648804.jpg)

**Comment by emperorjm** [comment]
This issue has since been resolved. The osmosis node was down and the chainops team got it back to a functional state.
