### ISSUE TITLE
Unable to setup Docker validator node due to cosmovisor version issue

### ISSUE THREAD

**Issue by emperorjm** [Sifchain/Support-Tickets#261]
When I try to setup a validator node using the docker setup wizard (https://github.com/Sifchain/sifchain-validators/blob/master/docs/nodes/setup/standalone/docker.md) I get the following error:

Attaching to sifchain-1_sifnode_1
sifnode_1  | panic: runtime error: invalid memory address or nil pointer dereference
sifnode_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1296909]
sifnode_1  | 
sifnode_1  | goroutine 1 [running]:
sifnode_1  | github.com/Sifchain/sifnode/tools/sifgen/node.(*Node).saveGenesis(0xc000f40000, 0x0, 0x0, 0x0)
sifnode_1  | 	/sifchain/tools/sifgen/node/node.go:279 +0xe9
sifnode_1  | github.com/Sifchain/sifnode/tools/sifgen/node.(*Node).networkGenesis(0xc000f40000, 0xc000e77c80, 0xf)
sifnode_1  | 	/sifchain/tools/sifgen/node/node.go:118 +0x54
sifnode_1  | github.com/Sifchain/sifnode/tools/sifgen/node.(*Node).genesis(0xc000f40000, 0x0, 0x0)
sifnode_1  | 	/sifchain/tools/sifgen/node/node.go:109 +0x5b
sifnode_1  | github.com/Sifchain/sifnode/tools/sifgen/node.(*Node).Build(0xc000f40000, 0xc000f40000, 0xa, 0xd18c2e2800)
sifnode_1  | 	/sifchain/tools/sifgen/node/node.go:74 +0xe9
sifnode_1  | github.com/Sifchain/sifnode/cmd/sifgen/cmd.nodeCreateCmd.func1(0xc000f37080, 0xc000f38780, 0x3, 0xa)
sifnode_1  | 	/sifchain/cmd/sifgen/cmd/root.go:152 +0x5ee
sifnode_1  | github.com/spf13/cobra.(*Command).execute(0xc000f37080, 0xc000f38640, 0xa, 0xa, 0xc000f37080, 0xc000f38640)
sifnode_1  | 	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
sifnode_1  | github.com/spf13/cobra.(*Command).ExecuteC(0xc000f362c0, 0x0, 0x1326700, 0xc000100058)
sifnode_1  | 	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
sifnode_1  | github.com/spf13/cobra.(*Command).Execute(...)
sifnode_1  | 	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
sifnode_1  | main.main()
sifnode_1  | 	/sifchain/cmd/sifgen/main.go:10 +0x2b
sifnode_1  | 9:35PM ERR configuration error: error="cannot stat home dir: stat /root/.sifnoded/cosmovisor: no such file or directory" module=cosmovisor
sifnode_1  | 9:35PM ERR  error="cannot stat home dir: stat /root/.sifnoded/cosmovisor: no such file or directory" module=cosmovisor
sifchain-1_sifnode_1 exited with code 1

The latest version of cosmovisor does not work with versions of Cosmos SDK prior to v0.45 so the script to install cosmovisor fails and then trying to use cosmovisor to execute sifnoded also fails as the binary does not exist.

**Comment by pandaring2you** [comment]
can you help me understand the business case for this and priority? thanks!

**Comment by emperorjm** [comment]
This is one of the three options within the documentation for setting up a validator node here https://github.com/Sifchain/sifchain-validators/blob/master/docs/nodes/setup.md. I see where users are still using and referencing the docker setup. I see that a shift for recommendations has moved from AWS/Docker to the standalone manual setup but if we still have the docker option documented then we should make sure the setup works. If not maybe we should remove that option from the docs.
