### ISSUE TITLE
REWARDS VANISHED

### ISSUE THREAD

**Issue by Kyoshii123** [Sifchain/Support-Tickets#267]
# Liquidity Mining / Rewards issue

## Describe the bug
I had pending rewards of CCA 20k ROWAN. I have no screenshot of this. I think it was sif expansion (6k rowans) and v4 (14k) rowans. PENDING DISPENSATION WAS 20K ROWAN.

After distribution got done, PENDING DISPENSATION SHOW 0. DISPENSED REWARDS ROSE FOR +6K ROWANS. Balance shows 6k rowans.

MISSING 14k ROWANS.

## Pool(s) affected
<Please write here the pool(s)you are having issues with>.

ROWAN - USDC

## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.

## Claim transaction(s)
Please write here details on the claim transactions (amount, pairs and date) and the links to those transactions

## Sif address
Please write here your sif address
sif1tc04s3qm00fyhllzrm4e3lrdrhzx798x3q7s84

## Expected Reward amount / Received amount
Please write here details on the rewards amounts you were expecting

## Reward Program title
Please write here the name of the reward program you are having issues with

## Error logs/Screenshots
Please add here error logs you are receiving/ screenshots>

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
Hi @Kyoshii123. The last distribution took a very long time to complete and the reason there was a big gap between receiving rewards from both programs. You received 13,704.949674667878 ROWAN from the Pools of the People (v4) at 2022-03-08 04:05:56.963 -0500 and then 6,732.291499129095 ROWAN (Sif Expansion) 14 hours later at 2022-03-08 18:30:53.162 -0500.

**Comment by Kyoshii123** [comment]
Adrian, i am sorry, i dont see 13,704.949674667878
 Rowan under balance. Please assist.


V sre., 9. mar. 2022 14:57 je oseba Adrian Thompson <
***@***.***> napisala:

**Comment by emperorjm** [comment]
Hi @Kyoshii123. The amount would have been included in the following swap https://www.mintscan.io/sifchain/txs/769AD205BAB0C4B93A926C7CFFC067DA104C808E1E3E96F0AD64922CF9588205 or liquidity addition https://www.mintscan.io/sifchain/txs/961BDC821EDBD168AC9D3D5BDE315EE2F3C883C42322664061668543E5FC5EF5 which were done a little over a minute after you received the tokens.

**Comment by Kyoshii123** [comment]
Thank you for finding it. I will go through mintscan.

I was doing rebalancing of pools i guess when first part distributed? Did
not even notice i used the rewards for repooling.

So i repooled first part of reward i guess. I did notice my pool a bit
higher value but did not thought it was from first part of distribution.


Checking mintscan.

Thank you!!!

V sre., 9. mar. 2022 15:16 je oseba Adrian Thompson <
***@***.***> napisala:
