### ISSUE TITLE
Swap screen disappears when selecting a new token on the SWAP page

### ISSUE THREAD

**Issue by emperorjm** [Sifchain/Support-Tickets#273]
On the SWAP page when a token is searched for and selected, the swap screen either disappears or the token does not get selected within the interface. The following screencast gives an example of each issue.

https://user-images.githubusercontent.com/1245772/157499400-a6c0d571-80a9-4d48-9edd-c3e1fdd97701.mov

**Comment by bksifchain** [comment]
@emperorjm  - Still looking into the fix for this, but the workaround is to do hard-refresh after making these selections and they will appear as normal. 

cc @alanrsoares

**Comment by bksifchain** [comment]
resolved
