### ISSUE TITLE
Incorrect Reward Amount

### ISSUE THREAD

**Issue by ivorychristine** [Sifchain/Support-Tickets#274]
**Describe the bug**

A Detailed description of the issue (what happened, token affected and token amount)

Ive been pooling for over 3 months and have recorded and calculated the amount of sifchain i recieve every week. This week I am supposed to get 33000-35000 rowan, but instead after calculating this weeks reward i am going to recieve about 27000rowan which is wrong. Can i get a help for this problem?

atom/rowan pool

**How to Reproduce**

4. See error "..."

**Expected behavior**
<Please write a clear and detailed description of what you expected to happen.>

**TX Hashes** (if applicable)

Please provide links to transaction hashes of the import / export issues you are facing

**Addresses** (if applicable
<Please provide links to your addresses (both of Sifchain and external chain)>

sif1ftu0tsxs4jc36kdv2ffj0e0x40dgyyrm8qj63q

**Error logs**
<Please provide links to your addresses (both of Sifchain and external chain)>

**Screenshots**

**Providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

user: M

**Comment by emperorjm** [comment]
The value of your Liquidity Position (valued in Rowan) changes depending on the fluctuation of Rowan price. It's really difficult to forecast or manually calculate the amount of ROWAN you will earn per hour, as you need to take into account the continuous change of the ROWAN price. So if ROWAN prices decrease during an hour, your Rewards for that hour would decrease too (as they are calculated on the Rowan value of your liquidity position in that hour). A week ago the ROWAN price was at $0.11 and now it's under $0.9 so the amount calculated will not be the same. There are also other factors that can increase or increase rewards received.

From our records, dispensations have been running smoothly and we are confident that the rewards being displayed are correct.

**Comment by emperorjm** [comment]
Currently, there is an issue with the frontend where the Sif Expansion amount is not being shown but the UI team is working on this but this is a new issue.
