### ISSUE TITLE
Import / Export issue

### ISSUE THREAD

**Issue by OlegEnthusiast** [Sifchain/Support-Tickets#275]
Hello! A user reported about the bran new error notification, please check and let me reason of it and the way to fix it. Thanks!

![image](https://user-images.githubusercontent.com/92320396/158216807-17f6acdc-9b67-49d7-8fe3-98932c8f6b9c.png)

sif1ackfzggrrvppqkpmgwgxgxm987vrwpvvaz9v5z

**Comment by emperorjm** [comment]
@OlegEnthusiast ask the user to make sure the network selected in Metamask is Ethereum and try again.

**Comment by emperorjm** [comment]
The wrong network was selected in Metamask.
