### ISSUE TITLE
Import / Export issue- Transfereing issue

### ISSUE THREAD

**Issue by Jennifer2022** [Sifchain/Support-Tickets#278]
## Describe the bug

I was transfering 4,340.632920 ROWAN token from my ''sif1kqp00smua43aczs834yzau8futvsyslht8mmn4'' address to ''osmo1kqp00smua43aczs834yzau8futvsyslhxp8a2v'' address, but the 4,340.632920 ROWAN token don't went through. Because I choose max amount, I forgot to leave some Rowan for fees.

I got this message ''failed to execute message; message index: 0: 242920400685915659rowan is smaller than 4340632920400685910459rowan: insufficient funds''.
The 4,340.632920 ROWAN token did't went back to my wallet either. I have transferred same way many times before with no issue.

This is the first time I got this issue.

## How to Reproduce

Here is my link for my transaction https://www.mintscan.io/sifchain/txs/9F64EEB0E29C420B988C58E39873D59830542E305EE419A0BD823959518C0C08

And the txhash is: 
9F64EEB0E29C420B988C58E39873D59830542E305EE419A0BD823959518C0C08

## Expected behaviour
I hope you guys can return back my 4,340.632920 ROWAN token to my wallet or to the receiver .

## TX Hashes
9F64EEB0E29C420B988C58E39873D59830542E305EE419A0BD823959518C0C08

## Addresses
https://www.mintscan.io/sifchain/txs/9F64EEB0E29C420B988C58E39873D59830542E305EE419A0BD823959518C0C08

## Error logs
failed to execute message; message index: 0: 242920400685915659rowan is smaller than 4340632920400685910459rowan: insufficient funds

I am feeling really bad how this happen to me, what will happen if it was large amount of Rowan. Are we going to lose it or what?
I am waiting for a positive respond from you guys!!!

**Comment by emperorjm** [comment]
Hi @Jennifer2022. Did you use the export feature within the DEX or you did a direct IBC transfer via Keplr?

**Comment by Jennifer2022** [comment]
I use the direct IBC transfer via Keprl

**Comment by emperorjm** [comment]
The tokens were returned to your account. It took a longer time than usual but if the transfer fails the tokens will be refunded to the account that executed the transaction.
