### ISSUE TITLE
Pool value by half

### ISSUE THREAD

**Issue by Czuwaj** [Sifchain/Support-Tickets#279]
sif1c6x5nfmehryedc5h2ynjflsns9aj8v5mawnddj
Please add here error logs you are receiving/ screenshots>

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**
Today I find out my pool values it’s by half 
Roman/Juno I have 28 Juno and 11716 erowan
It’s around 2100$ but pool it’s showing 1050$
same story it’s about rowan/atom
19 atom and 5914 erowan it’s like 1060$ but pool showing 530$ 
And my rewards and counted by half 
Thanks!

**Comment by emperorjm** [comment]
Hi @Czuwaj. Can you share a screenshot of what you are seeing on your screen for the JUNO pool.

**Comment by Czuwaj** [comment]
![Uploading AC2BF6ED-C611-418B-9DF6-7BB07A818290.jpeg…]()

**Comment by emperorjm** [comment]
I did a test and added 10 USDT and the equivalent ROWAN and I am now seeing the issue you are having. The value in the screenshot should show $20 as opposed to $10. When I do a withdrawal it does show the correct value though.:

![image](https://user-images.githubusercontent.com/1245772/158644749-1eccbdd8-8bb4-4fe6-bb4f-23eddfd06e15.png)


I will forward this to the Devs to look into.

**Comment by Czuwaj** [comment]
I’m adding screenshots, but how the rewards are counted?

**Comment by emperorjm** [comment]
I've reported both issues to the Devs. I'll update you on the fix.

**Comment by Czuwaj** [comment]
![275735885_970883296905303_5013876447230389007_n](https://user-images.githubusercontent.com/101731812/158646910-f4deb71c-42e3-4a7e-915d-d03d41cb0528.jpg)

**Comment by Czuwaj** [comment]
Thanks for support Adrian

**Comment by emperorjm** [comment]
@Czuwaj try doing a hard refresh. I just did a hard refresh and I am now seeing the correct values.
