### ISSUE TITLE
ticket 48 on discord

### ISSUE THREAD

**Issue by dana-nomad** [Sifchain/Support-Tickets#280]
Please write a detailed description of the issue.
I do not receive my pool rewards.
the amount now is in dispensed rewards but last night it was in claimed pending dispensation and i do not receive any ROWAN.

What is the name and amount of the token affected?
ROWAN about 80

What is your Sifchain address?
sif1jljc8q5ldykyvxxquvvfx7fv8tm5n9hmdy3yr5

What is your address on the other chain?
.

What is the link to the transaction has you are having problem with?
.

Are there any error logs you can share?
no

**Comment by emperorjm** [comment]
There was a big gap between this week's distributions which might have caused the issue. 61.66559729180866 ROWAN (Pools of the People) were distributed on 2022-03-15 22:42:14.762 -0500 and 25.6212500904783 ROWAN (Sif Expansion) were distributed on 2022-03-16 01:11:43.674 -0500.
