### ISSUE TITLE
UI pages "Pool" and "Pool stats" not loading

### ISSUE THREAD

**Issue by lufa23** [Sifchain/Support-Tickets#281]
# User Interface Issue
## Describe the bug
UI pages "Pool" and "Pool stats" do not load and throw a 501 error on sifchain.finance
`Failed to load resource: the server responded with a status of 501 ()
`
## To Reproduce
Go to www.sifchain.finance
Open the Pool or Pool Stat pages

## Screenshots
![79af8b0a-e921-47b4-b356-13104333f492](https://user-images.githubusercontent.com/67415638/158847662-da77a471-73b8-47e2-9e3e-ae0bb5ab92ae.png)
![e9d82995-456c-4b68-8cb5-99ad79fd500c](https://user-images.githubusercontent.com/67415638/158847678-f0b44a14-7855-4cc2-b031-df97e2fa4442.png)

## Browser
Chrome

## VPN 
No

**Comment by bksifchain** [comment]
resolved
