### ISSUE TITLE
unreceived rewards

### ISSUE THREAD

**Issue by vitalie65** [Sifchain/Support-Tickets#282]
Hello. 
My address is sif1qar9hsq504n0nafl08tzusga7fkup47vluqr00
I have LP ROWAN / USDC.
 Until this week, I have been receiving rewards from this pool on Tuesdays and Wednesdays. 
This week I received only a portion  ( 525 Rowan) of my rewards on Wednesday.
 I was supposed to 685 Rowan.
 I ask you to find out the reason for the partial accrual and receipt of the due rewards on my balance. I will also be very grateful to you for correcting this error and crediting the missing rewards to my balance.
![image](https://user-images.githubusercontent.com/36607854/158848884-95a6e46e-58da-4d4b-8029-18eac272b245.png)

Thanks!
By regards
 Vitalie

**Comment by emperorjm** [comment]
Hi @vitalie65. There was a big gap between this week's distributions which might have caused the issue. 522.5171760135653 ROWAN (Pools of the People) were distributed on 2022-03-15 23:00:09.264 -0500 and 232.92401038543733 ROWAN (Sif Expansion) were distributed on 2022-03-16 01:37:44.210 -0500.

A short time after you executed the following IBC transfer https://www.mintscan.io/sifchain/txs/9823F46DE4C22FB30CE7868230DF73AF1A6FB2D38B6E73C55FF01A87847EDDC3 which would include the tokens received.

**Comment by vitalie65** [comment]
thanks!

**Comment by vitalie65** [comment]
thanks,Adrian







чт, 17 мар. 2022 г. в 19:34, Adrian Thompson ***@***.***>:
