### ISSUE TITLE
Rewards issue

### ISSUE THREAD

**Issue by barmaglot91** [Sifchain/Support-Tickets#283]
# Liquidity Mining / Rewards issue
Rewards issue

## Describe the bug
Write here a clear and detailed description of what the bug is.
Added to rowan/usdc pool on 17/03/2022 and no rewards

## Pool(s) affected
<Please write here the pool(s)you are having issues with>.
ROWAN/USDC

## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.
i was provide 310$ on rowan/usdc pool https://www.mintscan.io/sifchain/txs/01BA7EFFCD1B2B9793E8DC37F6FF8DF9CBA165151F9522A48A7A19D4B6B53C47

## Claim transaction(s)
Please write here details on the claim transactions (amount, pairs and date) and the links to those transactions

## Sif address
Please write here your sif address
sif1wfzmj9fvag2wp5cjzfyj07dmqhwvklttahedtn

## Expected Reward amount / Received amount
Please write here details on the rewards amounts you were expecting
650 rowan

## Reward Program title
Please write here the name of the reward program you are having issues with
Pools of the People (v3) rowan/usdc 300% (1748%)

## Error logs/Screenshots
Please add here error logs you are receiving/  #screenshots>
<img width="1410" alt="Снимок экрана 2022-03-21 в 19 09 02" src="https://user-images.githubusercontent.com/79308300/159335252-e13e063b-ef86-4031-9c89-656cd9babfdf.png">

<img width="1431" alt="Снимок экрана 2022-03-21 в 19 13 05" src="https://user-images.githubusercontent.com/79308300/159335323-06eb1af9-0060-48c5-931d-a30d7f5d0741.png">
<img width="1344" alt="Снимок экрана 2022-03-21 в 19 13 46" src="https://user-images.githubusercontent.com/79308300/159335405-fa910c0d-b70b-47bd-aec2-8342394b01dc.png">

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
Hi @barmaglot91. You received 581.168567509348 ROWAN (Pools of the People) on 2022-03-22 01:33:13.470 -0400 and 182.31963024747827 ROWAN (Sif Expansion) were distributed at 2022-03-22 00:15:23.709 -0400.
