### ISSUE TITLE
ticket-58 - Rewards not showing

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#287]
**Please write a detailed description of the issue.**
Hi,
As requested.
My pending rewards (on right hand side) were showing at around 1100-1200 earlier on today (after my weekly pay out so these are rewards accrued for today.)

After the pool changes were made my rewards disappeared and started again from zero. plus they are accruing much slower it seems.

My sif address - sif1k2m5t3vvlems4jr86m8dc75mv3lcaxmhtkchqu

**What is the name and amount of the token affected?**
ROWAN

**What is your Sifchain address?**
sif1k2m5t3vvlems4jr86m8dc75mv3lcaxmhtkchqu

**What is your address on the other chain?**
sif1k2m5t3vvlems4jr86m8dc75mv3lcaxmhtkchqu

cosmos1k2m5t3vvlems4jr86m8dc75mv3lcaxmhwthp0h

**What is the link to the transaction has you are having problem with?**
-

**Are there any error logs you can share?**
-

**Comment by emperorjm** [comment]
Hi. Your rewards are auto claimed each week and distributed to your wallet. From the last distribution your received 1,691.340946300855 ROWAN from HARVEST at 2022-03-29 01:59:02.193 -0400 and 3,382.68189260171 from Expansion at 2022-03-29 03:03:44.746 -0400.
