### ISSUE TITLE
ticket-60 -trying to add liquidity to a pool but can't get the sifchain site to prompt for signing on keplr,

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#289]
**Please write a detailed description of the issue.**
trying to add liquidity to a pool but can't get the sifchain site to prompt for signing on keplr, just takes me to this form and pends with no popup on keplr or ledger

**What is the name and amount of the token affected?**
rowan 29k ish

**What is your Sifchain address?**
sif182d4fx786tal2wxl2jcymxe90ukynwqpwa5fm7

**What is your address on the other chain?**
n/a

**What is the link to the transaction has you are having problem with?**
n/a

**Are there any error logs you can share?**
no

**Comment by emperorjm** [comment]
Are you accessing https://sifchain-dex.forbole.com/? Try doing a hard refresh and try again.
