### ISSUE TITLE
Not able to add liquidity

### ISSUE THREAD

**Issue by Bezinho81** [Sifchain/Support-Tickets#291]
**Describe the bug**

A Detailed description of the issue (what happened, token affected and token amount)
I tried to add the farmed rowan and staking rewards to my Luna Rowan pool, but the kepler popup doesnt show.
restarted computer, cleared cache and cookies.
Kepler was connected, but I wasnt able to finalize transaction, because the transaction popup didnt work.
I tried swapping Rowan for Luna on the dex and this worked, als Kepler worked normally on Osmosis.
This leads to assume that the problem is somewhere else

**How to Reproduce**

4. See error "..."

1. Go to add liquidity Rowan Luna
2. Click pool unequally
3. Add max Rowan minus 2 for transactions
4. Click add liquidity
5. Click confirm
6. No Kepler transaction popup appears like normally

**Expected behavior**
<Please write a clear and detailed description of what you expected to happen.>

I expected my liquidity to be added to the pool

**TX Hashes** (if applicable)

Please provide links to transaction hashes of the import / export issues you are facing
No TX available as a transaction was not possible

**Addresses** (if applicable
<Please provide links to your addresses (both of Sifchain and external chain)>
N.A

**Error logs**
<Please provide links to your addresses (both of Sifchain and external chain)>

N.A.

**Screenshots**

![image](https://user-images.githubusercontent.com/102655742/160789658-81784574-f676-4145-bb93-bf19bc0a2526.png)
no transaction popup, this screen hangs

**Providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by lufa23** [comment]
hey,
- Are you using google chrome? Do you have any VPN?
- Can you send us a screeshot of what appears in the devtools console?
<img width="704" alt="devtools" src="https://user-images.githubusercontent.com/67415638/160860811-4eb5adc7-6851-4182-9b80-1a3064f85bc4.png">

**Comment by lufa23** [comment]
i have tried several times doing it myself and even if the Keplr didn't pop up, the transaction gets successfully signed..
Can you confirm if the issue persists?

**Comment by permacrab** [comment]
I can confirm the problem has not been resolved yet. I get the following error when trying to add single side liquidity to the USDC pool (even liquidity works fine.) The Keplr window doesn't pop up. It happens on Brave and Chrome, both updated to the latest version.

![error](https://user-images.githubusercontent.com/102806088/161262156-8096fdcb-dc34-426e-b2c0-103345a7aa0c.png)

**Comment by lufa23** [comment]
hey @permacrab , was the issue temporary?
