### ISSUE TITLE
Wrong calculation for LM rewards

### ISSUE THREAD

**Issue by OlegEnthusiast** [Sifchain/Support-Tickets#292]
Hi! There is a user sif1jd6ye7hk0drkfl3x2jd28cyt8n8g84yd20vqsk, which clearly getting the wrong rewards.

He took screenshots right before distributions each week. As a result, it is clear that he does not receive the entire rewards

![image](https://user-images.githubusercontent.com/92320396/160791004-189e5c3b-4d9f-4966-9142-73469d98f0d2.png)
March 22

![image](https://user-images.githubusercontent.com/92320396/160791052-b8bf3022-cacd-45d6-83a3-b1083b3e6fd7.png)
March 29

![image](https://user-images.githubusercontent.com/92320396/160791123-5a46442b-ecde-4aac-b47e-b8d89f346603.png)
March 30

His pools

![image](https://user-images.githubusercontent.com/92320396/160791184-05c00dda-7b1d-4126-ae3c-fe62edc754d4.png)

**Comment by emperorjm** [comment]
We have cut over to a new server which now starts accruing rewards from Tuesday morning 8am PST. For this first week the lost rewards from Monday will be added programmatically by the system at the next distribution. That would account for some reduced numbers shown on the rewards screen for this week.

**Comment by OlegEnthusiast** [comment]
But previous rewards had the same issue

Ср, 30 марта 2022 г. в 17:44, Adrian Thompson ***@***.***>:

**Comment by emperorjm** [comment]
What issue exactly? They earned more rewards on the 29th as opposed to the 22nd. Can the user submit the calculations used to come up with the rewards he/she were expecting?

**Comment by OlegEnthusiast** [comment]
12.5-13

**Comment by OlegEnthusiast** [comment]
March 22 ~12.5-13k
March 29 ~14k

He cannot calculate exactly, so he mentioned estimated amounts.

**Comment by emperorjm** [comment]
@OlegEnthusiast it is very difficult for someone to calculate their rewards precisely because there are a lot of variables involved especially with the movement of the ROWAN price. So if the user can't show what formula they've been using and even a spreadsheet breakdown then we have to assume that the values shown in the DEX are correct.

**Comment by OlegEnthusiast** [comment]
He received less on 29th as well, he cannot submit the calculations, since it's not possible to. But there is definitely a bug

**Comment by OlegEnthusiast** [comment]
11,258 + 65,660 = 76,919

76,919 + 12,131 = 89 050, he received this, but in Claimed Dispensation amount, there is 93 898

**Comment by emperorjm** [comment]
I have passed it on to a Dev to look into.

**Comment by OlegEnthusiast** [comment]
Hey, @emperorjm please give some update on this issue

in addition to the fact that last time he was not credited with at least 4847.9 ROWAN, he hasn't received part of the tokens again, let me show once again
![image](https://user-images.githubusercontent.com/92320396/162397774-bb0b950e-dfc7-44c9-b05e-7ddd83c9d75e.png)

11258.68+65660.34=76919.02

![image](https://user-images.githubusercontent.com/92320396/162397828-48b3294e-5213-409a-8157-0ffa32decc51.png)

12131.19+76919.02=89050.21

on the next screenshot it is stated that he has already received 93898.11, but actually received 89050.21, where did 4847.9 ROWAN go?

![image](https://user-images.githubusercontent.com/92320396/162397955-4f39e03b-c674-4ee5-9d1e-20c48b000cc7.png)

from the amount of 93898.11 continues the calculation of this week, 93898.11 + 12619 = 106517, this figure is more or less mathematically correct if you add the partial rewards that came to him, and once again shows that the algorithm takes into account the figure 4847, 9 ROWAN he has never received

![image](https://user-images.githubusercontent.com/92320396/162398271-539ddb87-c622-4875-8c65-fe0320724900.png)

in addition, please pay attention to the current dynamics of rewards, I think it is too small, because this week he pooled up to 1k USDC, and for more than 3 days he accrued only 4192 ROWAN

![image](https://user-images.githubusercontent.com/92320396/162398663-9e924e46-0cbe-4309-b291-eb082c0f08b0.png)
![image](https://user-images.githubusercontent.com/92320396/162398689-8396cbd7-073b-44a6-aa6e-abf2444c30b4.png)
![image](https://user-images.githubusercontent.com/92320396/162398704-568a96ec-c3b6-41d0-9314-a7f31925945a.png)
![image](https://user-images.githubusercontent.com/92320396/162398728-ba6cb556-81d6-4781-810d-078df94f46c4.png)

**Comment by emperorjm** [comment]
Hi @OlegEnthusiast. I have passed this issue onto the Devs. @bksifchain should be able to give an update.

**Comment by vasul17** [comment]
14 days the ticket remains without consideration, probably the team is just not interested in solving "small" problems of users

**Comment by emperorjm** [comment]
@vasul17 your address has been added to a list of addresses that will be audited and updates will be given on Discord in regards to the findings and when compensations will be made if any. I'll close this ticket for now.

**Comment by vasul17** [comment]
@emperorjm I'm not the owner of this address, but I'm just very surprised that the team does not respond for a long time, and then you just close the ticket, and not waiting for the response of the developers

**Comment by Yoshi210** [comment]
probably this project is just a scam because there are all signs of it and there is no feedback from the developers

**Comment by lufa23** [comment]
hey guys, as you may have noticed, we have a considerable backlog of addresses to audit and we really appreciate your patience on this..
