### ISSUE TITLE
Rewards not going through

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#294]
**Please write a detailed description of the issue.**
rewards are nott  movvingg   for abbboout 3 hours  nnoww

**What is the name and amount of the token affected?**
rowann   and  atom

**What is your Sifchain address?**
sif143z2459faf772e6sw3weh35dge88mjvsv6tsne

**What is your address on the other chain?**
cosmos143z2459faf772e6sw3weh35dge88mjvsf8yxuj

**What is the link to the transaction has you are having problem with?**
https://sifchain-dex.forbole.com/#/rewards

**Are there any error logs you can share?**
nno

**Comment by emperorjm** [comment]
The previous rewards implementation calculated rewards approximately every 1-2 hours but the new implementation will see calculations done every 20-25 minutes.

You can use the following https://data.sifchain.finance/beta/network/rewardPay/{walletaddress} to check your rewards being calculated.
 The last field, **updated_time_gmt** shows the last time the reward calculations are updated in GMT. 

Maybe there was an issue then but all is good now.
