### ISSUE TITLE
ticket-76 - Transaction failed

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#296]
**Please write a detailed description of the issue.**
tx failed

**What is the name and amount of the token affected?**
atom 70

**What is your Sifchain address?**
sif1t8e5vktvrtwxn98tfr3k3esl424s2jm6syu237

**What is your address on the other chain?**
cosmos1t8e5vktvrtwxn98tfr3k3esl424s2jm64enu74

**What is the link to the transaction has you are having problem with?**
tx failed

**Are there any error logs you can share?**

**Comment by emperorjm** [comment]
What exactly are you trying to do? If you are getting an error on the DEX please also send a screenshot of the error in the console as well as a screenshot of the error in the UI.

<img width="704" alt="160860811-4eb5adc7-6851-4182-9b80-1a3064f85bc4" src="https://user-images.githubusercontent.com/1245772/161115894-2351affa-11d9-4d74-82c9-4e62b1f45a66.png">

**Comment by stakrspace** [comment]
<img width="306" alt="Снимок экрана 2022-04-04 в 15 49 19" src="https://user-images.githubusercontent.com/65043457/161547357-c0e1b963-72ff-4e7f-8025-2ffdc0501cb7.png">
<img width="527" alt="Снимок экрана 2022-04-04 в 15 46 09" src="https://user-images.githubusercontent.com/65043457/161547362-ad47edb7-fb2e-44b5-9d03-8e8405e6f8a6.png">
<img width="463" alt="Снимок экрана 2022-04-04 в 15 49 14" src="https://user-images.githubusercontent.com/65043457/161547365-6284459c-85f4-4432-b533-86cb5f2e07fb.png">

index.f98f7559.js:10 Error: Cannot render environment null undefined
    at getEnv (index.f98f7559.js:10:157885)
    at index.f98f7559.js:233:55684
    at index.f98f7559.js:1:662
    at index.f98f7559.js:313:33639
getEnv @ index.f98f7559.js:10
index.f98f7559.js:313 Hiding redundant Metamask 'header not found' errors.
console.error @ index.f98f7559.js:313
index.f98f7559.js:313 ethereum wallet connect error Object
console.error @ index.f98f7559.js:313
index.f98f7559.js:313 Error: Attempt to retrieve the asset with key "rowan" before it had been cached.
    at Asset$1 (index.f98f7559.js:106:118004)
    at AssetAmount (index.f98f7559.js:106:121419)
    at calculateIBCExportFee (index.f98f7559.js:106:331246)
    at IBCService.estimateFees (index.f98f7559.js:106:337331)
    at Object.estimateFees (index.f98f7559.js:233:52505)
    at ReactiveEffect.fn (index.f98f7559.js:258:9598)
    at ReactiveEffect.run (index.f98f7559.js:6:35670)
    at ComputedRefImpl.get value [as value] (index.f98f7559.js:6:47289)
    at ReactiveEffect.fn (index.f98f7559.js:258:10895)
    at ReactiveEffect.run (index.f98f7559.js:6:35670)
console.error @ index.f98f7559.js:313
api-int.sifchain.finance/clp/getPmtpParams:1          Failed to load resource: the server responded with a status of 501 ()
api-int.sifchain.finance/ibc/applications/transfer/v1beta1/denom_traces:1          Failed to load resource: the server responded with a status of 501 ()
index.f98f7559.js:257 Uncaught (in promise) Object
index.f98f7559.js:106 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'connect')
    at IBCService.logIBCNetworkMetadata (index.f98f7559.js:106:338965)
    at index.f98f7559.js:233:44766
index.f98f7559.js:313 Error: signature verification failed; please verify account number (5945), sequence (129) and chain-id (sifchain-1): unauthorized
    at r (injectedScript.bundle.js:10:32583)
    at c (rocket-loader.min.js:1:9405)
console.error @ index.f98f7559.js:313
DevTools failed to load source map: Could not load content for chrome-extension://dmkamcknogkgcdfhhbddcghachkejeap/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://oiohdnannmknmdlddkdejbmplhbdcbee/browser-polyfill.js.map: System error:

**Comment by emperorjm** [comment]
@papanomad535 are you still having this issue?
