### ISSUE TITLE
Rewards disappeared 

### ISSUE THREAD

**Issue by OlegEnthusiast** [Sifchain/Support-Tickets#297]
Hi! The user pooled out 75k the USD value from liquidity, but after that his rewards are completely disappeared from the UI, he tried some basic actions, like refreshing the page and different browsers, but without success. 

His address: sif1uk77p6he26undp9wjjav6ygtu53kswl60cd5va
TX of removing liquidity: DC029E695206B7021EDA095AD1D46D66D30E5DD0BF1B62994ED94D2C810BCF1B

![image](https://user-images.githubusercontent.com/92320396/161395667-b1542b2c-4727-457a-84be-6148fa423345.png)

**Comment by emperorjm** [comment]
@OlegEnthusiast this user pooled 3 days ago https://www.mintscan.io/sifchain/txs/E27D45EC5AE12E31EDC4C2EB7735BCE34F01A857ED77731F0CB630EB1266FC87 and then removed all liquidity a day and a half later https://www.mintscan.io/sifchain/txs/DC029E695206B7021EDA095AD1D46D66D30E5DD0BF1B62994ED94D2C810BCF1B but they should still have earned some rewards during this time. This might be a frontend bug. Let me push this to the Devs.

**Comment by emperorjm** [comment]
The following is the response from the DEV:

"Rewards are based on the pool balance accrued and paid out at the time of dispensation. Pooling in and out with net zero balance times any duration equals zero rewards being dispensed for that week."

**Comment by OlegEnthusiast** [comment]
@emperorjm before three days ago the same amount was pooled on a different wallet, and all the accrued rewards have disappeared from this wallet as well
sif1ek4as5w4tnqas2qqwfvp0fx2qe9tnj4j7vnca8
Here the transaction where he removed the liquidity from the other wallet: 
DA0028B67388DF7D71C1B7AABC61C0DDF9F6379A74DBAE8D856B0D43C7A072FA 
this is something that should be reported cause if anybody else will remove  liquidity before the next time of dispensation all their accrued rewards will disappear as well. And please try to liaise with the devs to restore his rewards balance, it was a considerable amount.

**Comment by emperorjm** [comment]
@OlegEnthusiast an update has been made to account for this scenario but the Devs are still working on fixing the rewards calculation issue. This should be resolved soon.
