### ISSUE TITLE
Bigg Export Issue

### ISSUE THREAD

**Issue by ctrl13x** [Sifchain/Support-Tickets#299]
I can't export my Atom coins to the CosmosHub network, ask me for a commission in ETH, please solve this problem. More details in the screen video record I attached below. Thanks

https://user-images.githubusercontent.com/98986450/161433405-58a0f3d0-24bd-4ba8-b474-ab715b628780.mp4

**Comment by OlegEnthusiast** [comment]
Please take a look, @emperorjm. User tried different browsers and refreshed the page many times

**Comment by ctrl13x** [comment]
??????????????,  @emperorjm

**Comment by emperorjm** [comment]
Hi @ctrl13x. Can you clear all cache for the DEX and try again.
