### ISSUE TITLE
ticket-96 - - Rewards Incorrect

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#304]
**Please write a detailed description of the issue.**
I only received 13233 rowan tokens as reward however, my ui says 16727 tokens. Can you please verify if this is correct

**What is the name and amount of the token affected?**
Rowan, possibly 3-4 thousand

**What is your Sifchain address?**
sif17wpqw98f5yrg0gtgd406mn7jv49n2vtav4as47

**What is your address on the other chain?**
n/a

**What is the link to the transaction has you are having problem with?**
n/a

**Are there any error logs you can share?**
no

**Comment by emperorjm** [comment]
For **Expansion** (2022-04-05 03:58:08.059 -0400) you received 8,821.115199979718 ROWAN and **Harvest** (2022-04-05 05:36:36.295 -0400) 4,410.557599989855 ROWAN. So the amount received is correct. Can you share a screenshot of what you are seeing on the rewards screen?
