### ISSUE TITLE
ticket-98 - - Rewards Incorrect

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#305]
**Please write a detailed description of the issue.**
My dispensed rewards show 1976ROWAN but I never received anything in my balance

**What is the name and amount of the token affected?**
ROWAN, 1976

**What is your Sifchain address?**
sif10kccu43rr34y6lpcg435nnm42pczu9my29e5xu

**What is your address on the other chain?**
sif10kccu43rr34y6lpcg435nnm42pczu9my29e5xu

**What is the link to the transaction has you are having problem with?**
No link available

**Are there any error logs you can share?**
Don't know

**Comment by Figuartsmate** [comment]
Will anyone help me here? Still no rewards received while it shows the amount already claimed and received

**Comment by emperorjm** [comment]
Hi @Figuartsmate. You received the following number of tokens:
- Expansion (2022-04-05 03:27:43.699 -0400): 1,297.165257063923 ROWAN
- Harvest (2022-04-05 05:10:49.140 -0400): 648.582628531962 ROWAN

You executed the following liquidity addition shortly after with 1,296.915257063923000000ROWAN: https://www.mintscan.io/sifchain/txs/E8A19F3FD020A881C50CE9B3D0EDF8DA6FD9C5037FFED784F54F83D7C8A29817 and you still have 648.832628648.832628531962000000 ROWAN in your wallet.
