### ISSUE TITLE
ticket-105 - Did not receive Rewards for the last week

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#313]
**Please write a detailed description of the issue.**
Did not receive Rewards for the last week

**What is the name and amount of the token affected?**
Rowan Rewards.Dont know the Amount because there was an Pending Rewards UI Issue

**What is your Sifchain address?**
sif1gwfccvzd75wnu99fgaf5q3xympn0kxt4uazd24

**What is your address on the other chain?**
no

**What is the link to the transaction has you are having problem with?**
no

**Are there any error logs you can share?**
no

**Comment by emperorjm** [comment]
You are correct. You did not receive any rewards from the last distribution which shouldn't have been affected by the liquidity removal done 4 days ago. I am going to pass this on to the Devs to look into.

**Comment by emperorjm** [comment]
Missing payouts were made.
