### ISSUE TITLE
Pending rewards continue to accumulate after the cutoff time

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#314]
**Please write a detailed description of the issue.**
difference between total pending reward and the actual pay out

**What is the name and amount of the token affected?**
683 rowan

**What is your Sifchain address?**
sif1tgrj7sakajqpmfngz2jrja2u98rq0t0rhlpsjp

**What is your address on the other chain?**
NA

**What is the link to the transaction has you are having problem with?**
NA

**Are there any error logs you can share?**

**Comment by emperorjm** [comment]
These two screen shots were captured on April 5th when the last reward was paid out:

![Reward](https://user-images.githubusercontent.com/1245772/162771985-f86b9ece-8a30-4611-9e44-f4c0a17048f3.png)

**Comment by emperorjm** [comment]
The user receive 24,649.42 ROWAN but as you can see on the pending screen the amount shown was 25,339.14 which can be confusing.

- Expansion (2022-04-05 09:27:00.188 -0400): 16,432.95208077906 ROWAN
- Harvest (2022-04-05 08:43:18.918 -0400): 8,216.47604038953 ROWAN
