### ISSUE TITLE
Import / Export issue

### ISSUE THREAD

**Issue by johnt1973** [Sifchain/Support-Tickets#315]
## Describe the bug
I am trying to transfer ROWAN from Sifchain to Osmosis (using Cosmos) but it ONLY gives me Ethereum as an option for network

A Detailed description of the issue (what happened, token affected and token amount)
I am trying to transfer ROWAN from Sifchain to Osmosis (using Cosmos) but it ONLY gives me Ethereum as an option for network

## How to Reproduce

4. See error "..."

## Expected behaviour
Please write a clear and detailed description of what you expected to happen.

## TX Hashes
Please provide links to transaction hashes of the import / export issues you are facing

## Addresses
Please provide links to your addresses (**both** of Sifchain and external chain)

## Error logs
Please provide links to your addresses (both of Sifchain and external chain)

## Screenshots

**Providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
Hi @johnt1973. Thanks for bringing this to our attention. I tried just now and I am also only able to select the Ethereum network. I'll forward this issue to the Devs.

![Sifchain](https://user-images.githubusercontent.com/1245772/163040127-4b9cc28d-311d-4ce4-85b2-7c4683d96477.png)

**Comment by johnt1973** [comment]
Thank you so much for looking into this! Yes, it has been like this every time I tried in last couple of weeks...how long do you think it might take to resolve? also I was a little bit shocked in last hour suddenly under pools, I only seemed to see half of my account balances, I assumed it was a temporary bug, and sure enough within a few minutes now everything is displaying properly again which is good ! Just want to feel funds are safe at all times even if there is some display issue from time to time...Cheers,John

    On Tuesday, 12 April 2022, 21:33:06 CEST, Adrian Thompson ***@***.***> wrote:  
 
 


Hi @johnt1973. Thanks for bringing this to our attention. I tried just now and I am also only able to select the Ethereum network. I'll forward this issue to the Devs.

**Comment by bksifchain** [comment]
@emperorjm - Is this resolved / can we close this issue? If the user wants to import an ROWAN to Osmosis - they can go to Osmosis and select to import. They don't need to export.
