### ISSUE TITLE
Rewards Amounts Decreasing

### ISSUE THREAD

**Issue by DavesCrypto1** [Sifchain/Support-Tickets#316]
# Liquidity Mining / Rewards issue

## Describe the bug
On March 22, I claimed 490k ROWAN rewards. I swapped half ROWAN for ATOM and put all in liquidity pool. 
On March 28, I claimed 522k ROWAN rewards, **earning 32k more rewards than prior week**. I swapped half ROWAN for ATOM and put all in liquidity pool. 
On April 4, I claimed 544k ROWAN rewards, **earning 22k more rewards than prior week**. I swapped half ROWAN for ATOM and put all in liquidity pool.
On April 12, I claimed 539k ROWAN rewards, **earning 4.5k fewer rewards than prior week**.

## Pool(s) affected
ATOM/ROWAN

## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.

## Claim transaction(s)
Please write here details on the claim transactions (amount, pairs and date) and the links to those transactions

## Sif address
sif19wscsgp23dtlv8a287ht9f00vgnknl5fayew8c

## Expected Reward amount / Received amount
Expecting rewards amount to increase weekly when all rewards added to liquidity pool

## Reward Program title
Pool of the People

### March 22, 2022
On March 22, 2022, I had claimed 490,140.39 ROWAN:  

![2022-03-22-Rewards Claimed](https://user-images.githubusercontent.com/103544538/163078230-1e7fe6c2-5685-493b-95a3-41bd34ae1f80.png)

I had added 245,074 ROWAN and 802.64691 ATOM to liquidity pool:
 
![2022-03-22-Adding to Liquidity Pool](https://user-images.githubusercontent.com/103544538/163078341-0d0c1568-2ef4-4763-b359-34d4f59c5bab.png)

### MARCH 28, 2022
On March 28, 2022, I had claimed 522,851.53 ROWAN in rewards:

![2022-03-28-Adding to Liquidity Pool](https://user-images.githubusercontent.com/103544538/163078386-01757c27-c4d4-446c-b58c-c983e5652eca.png)

522,851 ROWAN rewards is 32,707.14 more rewards than the rewards for the prior week.

I swapped half of the ROWAN for ATOM and added 261428 ROWAN and 856.38753 ATOM to liquidity pool:

![2022-03-28-Adding to Liquidity Pool](https://user-images.githubusercontent.com/103544538/163078453-5ca4497c-e91c-49fa-b208-3612d27ccd6c.png)

### APRIL 5, 2022
On April 5, 2022, I had approximately 544,276.78 ROWAN rewarded:
 
![2022-04-04-Rewards Claimed](https://user-images.githubusercontent.com/103544538/163078530-4fb09053-0542-4c94-8342-6da55fb70a21.png)

544,276.78 ROWAN rewards is **21,425.25** more rewards than the rewards for the prior week. (However, the rewards for the prior week were **32,707** more than the prior week).

I swapped half of the ROWAN for ATOM and added 272139 ROWAN and 977.97349 ATOM to liquidity pool:
 
![2022-04-04-Adding to Liquidity Pool](https://user-images.githubusercontent.com/103544538/163078617-0562248c-7be6-4e8f-8094-caaafd9c8dd5.png)

### April 12, 2022
On April 12, 2022, I claimed approximately 539921.78 ROWAN in rewards:
 
![2022-04-12-Rewards Claimed](https://user-images.githubusercontent.com/103544538/163078665-109c97a3-982a-4cfc-bfd9-5193550395d7.png)

539921.78 ROWAN rewards is **4,355 FEWER** rewards than the rewards for the prior week, after adding in all of my rewards from the prior week to the liquidity pool.

**If I keep adding to the liquidity pool, the amount I am rewarded should be going up, not down.**

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
Hi @DavesCrypto1. Your address has been added to a list of addresses that will be audited and updates will be given on Discord in regards to the findings and when compensations will be made if any.

**Comment by DavesCrypto1** [comment]
Any updates on this? Thanks for your help.

**Comment by emperorjm** [comment]
Rewards coming to users on Tuesday, May 10th. Read below for everything you need to know about the situation.

Full Rewards Debrief: https://sifchain.notion.site/Rewards-Debrief-0502d12c872344a3b58d90c98a1f34d4

**Comment by emperorjm** [comment]
@DavesCrypto1 did you receive your rewards?
