### ISSUE TITLE
not receiving rewards for lm

### ISSUE THREAD

**Issue by talves12** [Sifchain/Support-Tickets#318]
# Liquidity Mining / Rewards issue

## Describe the bug
i have not been receiving the correct amount of rewards for lm. i still havent received any for 4/5/22 despite what it says on your end apparently. can you have a look? 

## Pool(s) affected
<Please write here the pool(s)you are having issues with>.

## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.

## Claim transaction(s)
Please write here details on the claim transactions (amount, pairs and date) and the links to those transactions

## Sif address
sif1dxh7d7fuvjy43e0557mx6wwe4luyc0s20fw0qp

## Reward Program title
Please write here the name of the reward program you are having issues with

## Error logs/Screenshots
Please add here error logs you are receiving/ screenshots>

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by talves12** [comment]
hello! its been 3 days, can somebody please get back to me on this?!!!!!!

**Comment by emperorjm** [comment]
Hi @talves12. I am seeing where your rewards have been distributed:

Last Week:
- Expansion (2022-04-05 05:16:59.215 -0500):  310.0016808219211 ROWAN
- Harvest (2022-04-05 05:21:12.624 -0500): 155.0008404109606 ROWAN


This Week:
- Expansion (2022-04-11 21:50:33.917 -0500):  273.4310020654546 ROWAN
- Harvest (2022-04-12 01:09:33.904 -0500): 136.7155010327272 ROWAN


You've said you are not receiving the correct amount of rewards. Can you say the amount you were expecting and how you came up with that amount?

**Comment by talves12** [comment]
I also wanted to add that I'm supplying about $700 to liquidity pools. My
rewards for this past week would be quite a bit more than last week and in
the figures you sent me, that's not nearly the case. I should have paid
closer attention apparently. I wasn't aware you guys were having these
types of issues. Thanks again for helping me to sort this out.

**Comment by talves12** [comment]
it may show on your guys' end that rewards have been dispensed, but if you check on mintscan, this is definitely not the case. i actually don't even think the 875.15 expected rewards that you guys have showing for me is even an accurate amount. it should be higher. i would have notified team sooner, but my first week on the i wasn't sure if rewards were sent directly to wallet or added back to pools so i was unsure if i had received them or not. obviously now i understand that they would have been added straight to my wallet and were not. please audit my address and you will notice that i received absolutely nothing on april 5th contrary to what you say.
                                                                    thank you

**Comment by talves12** [comment]
will you guys please have the devs take a look and audit my address? this most definitely needs to be adjusted to the correct amounts. even today, my pending rewards have been stuck at 236.93 for much of the day now. i don't know if this is due to them possibly working on the issue or not but there are obviously problems with my account. thanks for your assistance.

**Comment by emperorjm** [comment]
Hi @talves12. You address was audited and recalculations done. You were overpaid for week 2 and 3 by 330.46891753247545 ROWAN which was deducted from your week 4 rewards which were distributed to your account.
