### ISSUE TITLE
-

### ISSUE THREAD

**Issue by ghost** [Sifchain/Support-Tickets#319]
--

**Comment by ghost** [comment]
@OlegEnthusiast @karan-sifchain @ivorychristine @sml1991 

Please assign ticket to dev team and advise.

**Comment by emperorjm** [comment]
Hi @siffuku. We are looking into this.

**Comment by ghost** [comment]
@emperorjm added additional findings above, I hope devs can make me whole for this simple bug and we can move on! Thanks!

**Comment by emperorjm** [comment]
@siffuku an audit will be done which will take a few weeks to complete after which the rewards will be distributed.

**Comment by ghost** [comment]
Thanks, will you update me here?

**Comment by ghost** [comment]
@emperorjm @OlegEnthusiast @karan-sifchain @ivorychristine 

so I never got any rewards to my wallet despite proving my case above. I am owed 10,069.58+ Rowan

Please re-read my issue above and manually disburse the correct amount to my wallet in question for LP I provided.

**Comment by emperorjm** [comment]
Hi @siffuku. Weeks 2 and 3 saw a lot of accounts being overpaid which included your address where you were overpaid by 21,483.9224610131928 ROWAN which was deducted from the amount you earned in Week 4 which could not cover the overpaid amount and the reason you didn't receive a payout.

**Comment by ghost** [comment]
Thank you for the clarity! Let's close this issue :) Take care mate
