### ISSUE TITLE
Not getting correct rewards this week

### ISSUE THREAD

**Issue by Kyoshii123** [Sifchain/Support-Tickets#320]
# Liquidity Mining / Rewards issue

## Describe the bug
Not getting correct rewards this week under total pending rewards. I think i should be getting way more than is displayed. UI BUG ?

## Pool(s) affected
ROWAN - USDT

## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.

## Claim transaction(s)
Please write here details on the claim transactions (amount, pairs and date) and the links to those transactions

## Sif address
sif1tc04s3qm00fyhllzrm4e3lrdrhzx798x3q7s84

## Expected Reward amount / Received amount
I should be getting way more rewards than is currently shown. UI BUG ?

## Reward Program title
Please write here the name of the reward program you are having issues with

## Error logs/Screenshots
Please add here error logs you are receiving/ screenshots>

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
Hi @Kyoshii123. We are looking into this.

**Comment by Kyoshii123** [comment]
Hi @emperorjm . Thank you for your response and help.

**Comment by Kyoshii123** [comment]
is it possible for you to also check previous week rewards if they were all dispensed?
Thank you!

**Comment by emperorjm** [comment]
Yes all rewards from last week were dispensed:
- Expansion (2022-04-12 00:20:43.717 -0500): 36,230.5556832926 ROWAN
- Harvest (2022-04-12 02:08:55.977 -0500): 18,115.27784164634 ROWAN

**Comment by Kyoshii123** [comment]
Thank you. Any news on the current rewards issue ?

**Comment by emperorjm** [comment]
Hi @Kyoshii123. All rewards for harvest expansion were distributed.
