### ISSUE TITLE
Rewards

### ISSUE THREAD

**Issue by skymochulsky** [Sifchain/Support-Tickets#321]
# Liquidity Mining / Rewards issue

## 
![IMG_20220416_171232_668](https://user-images.githubusercontent.com/103832820/163676281-ef0343a9-4383-4a6c-a018-21b07b090b5d.jpg)
![IMG_20220416_171237_543](https://user-images.githubusercontent.com/103832820/163676286-e468cc0a-46df-4e1e-b193-f9a6cc6949e0.jpg)

**Comment by emperorjm** [comment]
Hi @skymochulsky. We are looking into this.

**Comment by emperorjm** [comment]
Hi @skymochulsky. All addresses were audited for the last 3 weeks of the Harvest program. All rewards have now been distributed.
