### ISSUE TITLE
amount of rewards received wrong 

### ISSUE THREAD

**Issue by talves12** [Sifchain/Support-Tickets#322]
# Liquidity Mining / Rewards issue

## Describe the bug
the amount of rewards i have received since adding liquidity is way off. i didnt receive any rewards at all last week.

## Pool(s) affected
<Please write here the pool(s)you are having issues with>.

## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.

## Claim transaction(s)
Please write here details on the claim transactions (amount, pairs and date) and the links to those transactions

## Sif address
sif1dxh7d7fuvjy43e0557mx6wwe4luyc0s20fw0qp

## Expected Reward amount / Received amount
Please write here details on the rewards amounts you were expecting

## Reward Program title
Please write here the name of the reward program you are having issues with

## Error logs/Screenshots
Please add here error logs you are receiving/ screenshots>

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
Duplicate issue

**Comment by talves12** [comment]
maybe you should fix the problem before you close it
