### ISSUE TITLE
amount of rewards received is wrong. none received at all for last week!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by talves12** [Sifchain/Support-Tickets#323]
# Liquidity Mining / Rewards issue

## Describe the bug
amount of rewards received is wrong. none received at all for last week. only began providing liquidity a little over 2 weeks ago, so it shouldn't be that difficult to remedy.

## Pool(s) affected
<Please write here the pool(s)you are having issues with>.

## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.

## Claim transaction(s)
Please write here details on the claim transactions (amount, pairs and date) and the links to those transactions

## Sif address
sif1dxh7d7fuvjy43e0557mx6wwe4luyc0s20fw0qp

## Expected Reward amount / Received amount
Please write here details on the rewards amounts you were expecting

## Reward Program title
Please write here the name of the reward program you are having issues with

## Error logs/Screenshots
Please add here error logs you are receiving/ screenshots>

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
Duplicate issue

**Comment by talves12** [comment]
ok, you guys may show that rewards were distributed to me but if you check
my address on mintscan, you will see that this is not the case. i
received 2 dispersals on tues for this past week equaling about $30.00
which i instantly staked. that seemed a bit low to me but this week ive
still received nothing. i appreciate you taking the time to help me out
with this.
                                   thanks
