### ISSUE TITLE
Wrong rewards in previous week

### ISSUE THREAD

**Issue by Vitaminchenko** [Sifchain/Support-Tickets#324]
# Liquidity Mining / Rewards issue

## 
![CB108352-61BD-48CA-BE6F-122DF2D73820](https://user-images.githubusercontent.com/103862525/163711511-1b62e164-995c-4c6f-b3f7-a940d6837c83.jpeg)
![99A6A14E-62F1-470B-8579-CFF762B13AF7](https://user-images.githubusercontent.com/103862525/163711526-8f79851f-03e8-476a-8596-bf3c6845f028.jpeg)

**Comment by emperorjm** [comment]
Hi @Vitaminchenko.  An audit will be done which will take a few weeks to complete after which the rewards will be distributed.

**Comment by emperorjm** [comment]
Hi @Vitaminchenko. All audits have been completed and recalculations done and rewards distributed.
