### ISSUE TITLE
No rewards distributed after PMTP conversion

### ISSUE THREAD

**Issue by mbaileyff** [Sifchain/Support-Tickets#326]
# Liquidity Mining / Rewards issue
I accumulated over 8500 ROWAN before 4/19/22 and none were rewarded after the PMTP switchover

## Pool(s) affected
Pools of the People

## Liquidity Add transaction(s)
Pools ROWAN/LUNA and ROWAN/ATOM

## Claim transaction(s)
Please write here details on the claim transactions (amount, pairs and date) and the links to those transactions

## Sif address
sif1jfqml9433yus7a6tzttluav3vv9m9y4rhl0dh0

## Expected Reward amount / Received amount
Expected at least 8500 ROWAN/ Received None

## Reward Program title
Sifs Expansion and Pools of the People

## Error logs/Screenshots
Please add here error logs you are receiving/ screenshots>

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
Hi @mbaileyff.  An audit will be done which will take a few weeks to complete after which the rewards will be distributed. an announcement was made on Discord in the announcement channel.

**Comment by mbaileyff** [comment]
Ty

**Comment by emperorjm** [comment]
@mbaileyff did you receive the rewards?

**Comment by mbaileyff** [comment]
Hi. I responded to your email but have not got a reply. I received a small fraction of my rewards. 
As indicated in my original issue. I was expecting around 8,000 ROWAN. I received 968 ROWAN. I would like another audit done to correct the rewards due. 
Respectfully 
Mark

**Comment by emperorjm** [comment]
Hi @mbaileyff. Weeks 2 and 3 saw a lot of accounts being overpaid which included your account where you were overpaid by 7,707.510917707102194 ROWAN which was deducted from the amount you earned in Week 4 leaving you with the net amount 962.989030181142325 ROWAN.
