### ISSUE TITLE
No rewards come after the new PMTP program

### ISSUE THREAD

**Issue by 88yarcev88** [Sifchain/Support-Tickets#327]
Hello. Since the start of the new liquidity program, there have been no awards received. sif157lhf9e3dqm2n2f5epxrsxze0e25ne9qt44hst

**Comment by emperorjm** [comment]
Hi @88yarcev88. Rewards from the new Ascension rewards program are generated at each block which works out to be every 6 seconds and are automatically compounded in your pool. Therefore you won't see the tokens in your wallet but in your pool value.

**Comment by 88yarcev88** [comment]
Hello! The number of coins in the pool has become less compared to a week earlier (since the addition of the revarods received under the last program) was 38500 rowan, now 38200 rowan, and the total value of the pool has not increased either.

**Comment by 88yarcev88** [comment]
> Hi @88yarcev88. Rewards from the new Ascension rewards program are generated at each block which works out to be every 6 seconds and are automatically compounded in your pool. Therefore you won't see the tokens in your wallet but in your pool value. 

Hello! The number of coins in the pool has become less compared to a week earlier (since the addition of the revarods received under the last program) was 38500 rowan, now 38200 rowan, and the total value of the pool has not increased either.

**Comment by 88yarcev88** [comment]
> Hi @88yarcev88. Rewards from the new Ascension rewards program are generated at each block which works out to be every 6 seconds and are automatically compounded in your pool. Therefore you won't see the tokens in your wallet but in your pool value. 

???

**Comment by emperorjm** [comment]
> > Hi @88yarcev88. Rewards from the new Ascension rewards program are generated at each block which works out to be every 6 seconds and are automatically compounded in your pool. Therefore you won't see the tokens in your wallet but in your pool value.
> 
> Hello! The number of coins in the pool has become less compared to a week earlier (since the addition of the revarods received under the last program) was 38500 rowan, now 38200 rowan, and the total value of the pool has not increased either.

This could be due to impermanent loss but your rewards are added back into your pools every 6 seconds which is the current block time. Let me know if you are still having an issue. If not I will close this issue.
