### ISSUE TITLE
Decreased liquidity

### ISSUE THREAD

**Issue by Ozerdemirel** [Sifchain/Support-Tickets#328]
**Describe the bug**

My liquidity amount is constantly decreasing

A Detailed description of the issue (what happened, token affected and token amount)

I didn't get any reward in the atom/rovan pool I made for liquidity. There is a constantly decreasing graph
![405250CD-E050-4198-8C25-712064A83A5C](https://user-images.githubusercontent.com/104192401/164631504-d2e39330-5f6e-4722-b294-da027e3cd0d2.jpeg)
![73B723C6-E820-4D29-AEB4-36DB94623579](https://user-images.githubusercontent.com/104192401/164631820-08cb2d8a-e7dd-4f95-924e-f82e35a76405.jpeg)

**How to Reproduce**

4. See error "..."

**Expected behavior**
<Please write a clear and detailed description of what you expected to happen.>

**TX Hashes** (if applicable)

Please provide links to transaction hashes of the import / export issues you are facing

**Addresses** (if applicable
<Please provide links to your addresses (both of Sifchain and external chain)>

**Error logs**
<Please provide links to your addresses (both of Sifchain and external chain)>

**Screenshots**

**Providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
@Ozerdemirel were the rewards distributed to your account?

**Comment by Ozerdemirel** [comment]
Yes,
Thankyou

17 May 2022 Sal, saat 15:37 tarihinde Adrian Thompson <
***@***.***> şunu yazdı:

**Comment by Ozerdemirel** [comment]
Thank you!

17 May 2022 Sal, saat 19:47 tarihinde Adrian Thompson <
***@***.***> şunu yazdı:
