### ISSUE TITLE
cant swap atom to rowan

### ISSUE THREAD

**Issue by abuzinneerah** [Sifchain/Support-Tickets#329]
**Describe the bug**

A Detailed description of the issue (what happened, token affected and token amount)

Cant swap my atom to rowan

**How to Reproduce**

4. See error "..."

**Expected behavior**
<Please write a clear and detailed description of what you expected to happen.>

**TX Hashes** (if applicable)

Please provide links to transaction hashes of the import / export issues you are facing

**Addresses** (if applicable
<Please provide links to your addresses (both of Sifchain and external chain)>

**Error logs**
<Please provide links to your addresses (both of Sifchain and external chain)>

unexpected token i in JSON position 2

Received ill-formatted txhash. Must be non-empty upper-case hex

**Screenshots**

**Providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by lufa23** [comment]
yeah ATOM - ROWAN swaps seem to have issues


<img width="675" alt="Screenshot 2022-04-24 at 14 12 43" src="https://user-images.githubusercontent.com/67415638/164975925-3a624126-37b3-4b6d-9ce4-6d6091f28044.png">
<img width="610" alt="Screenshot 2022-04-24 at 14 13 21" src="https://user-images.githubusercontent.com/67415638/164975938-46fd08f8-c9fa-4c4d-9fe4-cbf694fdcaae.png">

We're checking on it

**Comment by bksifchain** [comment]
This issue is resolved on betanet. Closing.
