### ISSUE TITLE
time remaining for unbonding period disappears

### ISSUE THREAD

**Issue by dana-nomad** [Sifchain/Support-Tickets#330]
people cannot see the amount of days left in their unbonding period. it disappears and refreshing won't bring it back

**Comment by lufa23** [comment]
hey @dana-nomad can you share the specific error logs that user get by using the browser dev tools?
<img width="704" alt="devtools" src="https://user-images.githubusercontent.com/67415638/164975534-abfe1074-94f7-432c-b360-90a295b64fe2.png">

(I am trying to replicate the issue but i am currently facing another issue)

**Comment by lufa23** [comment]
hey @dana-nomad has this been resolved?

**Comment by lufa23** [comment]
closing the issue as it seems to have been resolved
