### ISSUE TITLE
Users unable to import Ethereum based tokens 

### ISSUE THREAD

**Issue by emperorjm** [Sifchain/Support-Tickets#331]
There seems to be an issue with the Peggy bridge which is preventing users from importing their tokens to the DEX. A particular user is receiving an error message "**Cannot read properties of undefined (reading 'call')**".

**Comment by ivorychristine** [comment]
Hi Kym. I've just been testing my Metamask with other apps (eg, zapperDOTfi, polygon bridge) and they all display correct token balances for my MM wallet. It's only the sifchain import function that's displaying zero balances for my tokens. It seems like your bridge isn't working properly

**Comment by MPOLloeng** [comment]
![Devt](https://user-images.githubusercontent.com/104271202/164916097-67585873-5ef3-4068-ab55-e16d11f300fa.png)


Told that this would help the devs. This is what is seen in the console when the error occurs (chrome).
