### ISSUE TITLE
Cosmostation App Error

### ISSUE THREAD

**Issue by ivorychristine** [Sifchain/Support-Tickets#332]
**Describe the bug**

A Detailed description of the issue (what happened, token affected and token amount)

**How to Reproduce**

4. See error "..."

**Expected behavior**
<Please write a clear and detailed description of what you expected to happen.>

**TX Hashes** (if applicable)

Please provide links to transaction hashes of the import / export issues you are facing

**Addresses** (if applicable
<Please provide links to your addresses (both of Sifchain and external chain)>

**Error logs**
<Please provide links to your addresses (both of Sifchain and external chain)>

**Screenshots**

**Providing as much detail as possible will help engineers to solve the case faster..**

Thanks!
![IMG_20220423_081537_923](https://user-images.githubusercontent.com/94232457/164836932-b0a2c24d-fd05-499b-8777-bf03f3871e84.jpg)

**Comment by lufa23** [comment]
Cosmostation is looking into it

**Comment by lufa23** [comment]
hey, this should have been fixed now.
Let me know if it's not the case
