### ISSUE TITLE
Pool replenishment

### ISSUE THREAD

**Issue by Vyacheslav999** [Sifchain/Support-Tickets#333]
# Liquidity Mining / Rewards issue

## Describe the bug
Hi, I can't align the pool using an asymmetric deposit, since the deposited token (USDC) is distributed between USDC and rowans

## Pool(s) affected
<Please write here the pool(s)you are having issues with>.
USDC \ Rowan
## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.

## Claim transaction(s)
Please write here details on the claim transactions (amount, pairs and date) and the links to those transactions 
There is a difference in the value of tokens in the pool, in order to align the pool, I add asymmetrically (7 USDC and 0 row), and in the pool they are distributed symmetrically (3.5 USDC and 3.5 USDC in terms of a row) and the difference of 7 USDC remains
![Screenshot_1](https://user-images.githubusercontent.com/99545852/164885622-80e10cce-6e35-4d5b-8406-4f850e14088c.png)
![Screenshot_2](https://user-images.githubusercontent.com/99545852/164885624-c5bdd0b5-5e32-494b-95ea-3d388f233ceb.png)
![Screenshot_3](https://user-images.githubusercontent.com/99545852/164885626-27785497-5733-4e9a-802d-d4ea6108ee89.png)

## Sif address
Please write here your sif address
sif13gqun5f87xdp74jqvx4qw6wql0wymuy7t8w6cc

## Expected Reward amount / Received amount
Please write here details on the rewards amounts you were expecting

## Reward Program title
Please write here the name of the reward program you are having issues with

## Error logs/Screenshots
Please add here error logs you are receiving/ screenshots>

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by lufa23** [comment]
mm.. i just tried myself and it seemed to be working fine..


Can you try again and share the console log that you get by using the browser dev tools?
<img width="704" alt="devtools" src="https://user-images.githubusercontent.com/67415638/164975322-02f34a52-000f-437f-b131-5a9d1e79b3f2.png">

**Comment by Vyacheslav999** [comment]
Hello, I'm sending you new screenshots and a screenshot of the console. Is this what was needed?

  
>Воскресенье, 24 апреля 2022, 14:59 +03:00 от lufa23 ***@***.***>:
> 
> 
>mm.. i just tried myself and it seemed to be working fine..
>Can you try again and share the console log that you get by using the browser dev tools?
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <Sifchain/Support-Tickets/issues/333/1107826356 @ github . com> 
 
 
--
Вячеслав Бисеров
Отправлено из Почты  Mail.ru

**Comment by Vyacheslav999** [comment]
Something else

  
>Воскресенье, 24 апреля 2022, 14:59 +03:00 от lufa23 ***@***.***>:
> 
> 
>mm.. i just tried myself and it seemed to be working fine..
>Can you try again and share the console log that you get by using the browser dev tools?
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <Sifchain/Support-Tickets/issues/333/1107826356 @ github . com> 
 
 
--
Вячеслав Бисеров
Отправлено из Почты  Mail.ru

**Comment by lufa23** [comment]
Hey we did suspended asymmetric deposits for a period (which i assume it was the period in which you were not able to add asymmetrically). Everything should have worked properly since then, closing the issue for now
