### ISSUE TITLE
REDELIGATION ERROR 

### ISSUE THREAD

**Issue by Mrakama** [Sifchain/Support-Tickets#336]
I have 70% of my portfolio delegated to THORchain validator and observe that this Validator is Shutting down in 2days. I have been trying to redelegate my tokens to another delegator and the transaction keeps failing even when I have increased the gas fee to 10k. Attached is the video of me trying to redelegate. Kindly attend to this because I can't afford to loose this tokens.

**Comment by Mrakama** [comment]
My Sifchain address is (sif17m6vqcfx9uhsuzude7cjnh0hcj5fzql638d5su)

**Comment by Mrakama** [comment]
[REDELIGATION ERROR.zip](https://github.com/Sifchain/Support-Tickets/files/8553171/REDELIGATION.ERROR.zip)
Kindly watch video or the process and error

**Comment by lufa23** [comment]
i tried myself, and redelegation seems to work fine.

If you encounter issues again, can you
<img width="704" alt="devtools" src="https://user-images.githubusercontent.com/67415638/165090835-7396a261-7198-4823-9b9f-feec7e493988.png">
 share the error logs by using the browser web tools?
Thanks

**Comment by Mrakama** [comment]
https://api-cryptoeconomics.sifchain.finance/api/vs?key=userData&snapshot-source=mainnet&timestamp=now&address=sif17m6vqcfx9uhsuzude7cjnh0hcj5fzql638d5su

Above is the error log as requested

**Comment by Mrakama** [comment]
Hello, please someone should check my wallet please i cant carry out any transaction

**Comment by emperorjm** [comment]
Hi @Mrakama. You cannot do multiple redelegations  of the same tokens within a 21 day period. You can only redelegate the first 400 tokens delegated to Thorchain validator done here  https://www.mintscan.io/sifchain/txs/E6D5798F0BF5ED42CF73298BB4763DD974017C88B8D8FF63B6E38ABF06AE172B. The other 86 rowan redelegated from Blockngine as shown here https://www.mintscan.io/sifchain/txs/12CC34F6BD8F889FD651190E15843DB75B08733309979B1DE587A4E8675B292E will need to complete that 21 days cycle.

So at this point you can only redelegate only 400 Rowan from Thorchain. Try to redelegate this amount and let us know the outcome.
