### ISSUE TITLE
Stuck import TX

### ISSUE THREAD

**Issue by lufa23** [Sifchain/Support-Tickets#338]
**Description:**
15K USDC stuck transaction

**What is your Sifchain address?**
sif12wsx4daft4ccp0e7mkravh0q7hdayslpymwc3a

**What is your address on the other chain?**
0xC12db58827524592C8a77C33B6b9DF501f32d12A

**What is the link to the transaction has you are having problem with?**
https://etherscan.io/tx/0x4ba34303610d8edc57d96d05b2cdcf63c05319136b97029d79522a1e22e75f3f

**Are there any error logs you can share?**
Original transaction dropped and replaced
[Ethereum Transaction Hash (Txhash) Details | Etherscan](https://etherscan.io/tx/0x4ba34303610d8edc57d96d05b2cdcf63c05319136b97029d79522a1e22e75f3f)
Replaced by Txn Hash:
0x5b7a548ba099cfbbd9b6a4f032e673e410ecdbe004c2a1b32e7097d7e02b3ec0

**Comment by banshee** [comment]
This isn't the transaction going through?

https://www.mintscan.io/sifchain/txs/80A3B338C8671BABEBF56AD687A450F993C0DBB1588669C6A5E98E03A4472FD7
