### ISSUE TITLE
Missing Expansion Reward Distribution from 2022-04-12 (-> not the current audit week)

### ISSUE THREAD

**Issue by Rewardrequest** [Sifchain/Support-Tickets#339]
# Liquidity Mining / Rewards issue

## Describe the bug
In the week prior to the last Expansion reward payout (that has not occured yet), rewards were not distributed to 3 of my wallets. I already had this problem a few months back, but then the missing amount was distributed with the next weekly distribution. As this has not yet occured and the last Expansion distribution is being audited, I just want to make sure that my missing distribution will be included.

## Pool(s) affected
USDC, ATOM, ETH

## Liquidity Add transaction(s)

It's not really possible for me to give the exact LP add transactions that are affected as I have a very long history of adds and removals due to arbitrage actions to balance the pools back. What I would need is the number of ROWAN pooled at block x. Then I could list the information how much was pooled for what amount of time during that Expansion week. (was pooled for only around 1.5-2d during that reward window)
 But I don't know how to get this or wether it's possible to get this for a non-dev with tools that are publicly available. So I guess you'll do something like this in the audit anyway.

Maybe it makes more sense to include the LP removal transactions, as I have removed 100% of liquidity from those 3 affected wallets (probably the reason that there have been problems to the reward payout for that week)

Address #1 : sif1tr5232uays8d25g3rfpsa3f5edl6sy0dp09der
Liquidity removal transactions:
57867978FD1B7E9F09A9CD5877A1FC84C6053A82B343C1E28F37BD0D9BA61DD1 (229,751.408997731193612724ROWAN)
D0F07C61CA5CFA56883B48016E9A01D45786FEF1259A45DA975077F886BAB3CF (139,752.924502120497796088ROWAN)
8C12B879DEAB7044C0D997C0F02232A7CB0F28860DB0E8B09849ABD64C0C3D85 (600,482.807219855040781565ROWAN)
E1066749B3C1B3B9841C7478E7749074F4011F8A2DFD9642CC045EBE6F583776 (2,694.029470362308229529ROWAN)
F4A78E9A8A9D241C6522E66603F98461102D23ABF596E53AADB6A943B37B1573 (297,123.035111293856654709ROWAN)
A17956C3769F4202BCB013073F4B7059FC5C54E48FC477E671A382B5E44F765C (2,214.903788011910452048ROWAN)

The last time that I noted the reward amount that I should have received before removing the liquidity was 17,924 ROWAN.

Address #2: sif17pwuj3w7lvm03ex7d6a73k4xfne5803mc425l5
382F25661DC89EE999888A510A237D97ED00F4DBAF4340BE62363B02DAF23843 (1,355,190.250089918581305291ROWAN)
743F6554994C6A632AB4922B97DFBE73403810008C63DD9D97E7E6248DFA63E4 (14,233.553569809546207567ROWAN)
5AA6B6F62F6ECB0D17A72C36FC57D12C35C7A62EB9ECFF2810A8B3F1F3EEC15A (148.984094020446113333ROWAN)

The last time that I noted the reward amount that I should have received before removing the liquidity was 26,990 ROWAN.

Address #3: sif12y6ltyq23xhggkvws2a26tlwdznavt0y06u2d9
57C6529EF6AAD0F5CE945D8658AEF9F4BB77B686052649CFA60EF6B39CEED81D (8,517.999423730155099574ROWAN)
9AACD5562D7E2E9FB9FCBA693E35DC8B0FE0013BC71BC037150CE2AECC69C19D (813,787.551633741612911530ROWAN)

The last time that I noted the reward amount that I should have received before removing the liquidity was 25,772 ROWAN.

## Sif address
Address #1 : sif1tr5232uays8d25g3rfpsa3f5edl6sy0dp09der
Address #2: sif17pwuj3w7lvm03ex7d6a73k4xfne5803mc425l5
Address #3: sif12y6ltyq23xhggkvws2a26tlwdznavt0y06u2d9

## Expected Reward amount / Received amount
Address #1: 17,924 ROWAN / 0 ROWAN
Address #2: 26,990 ROWAN / 0 ROWAN
Address #3: 25,772 ROWAN / 0 ROWAN

## Reward Program title
program=harvest_expansion and program=expansion_v4_bonus
https://www.mintscan.io/sifchain/txs/F6079A365F967927493E03784F93A5DA3F7E6D3529553116D4D417381CD1BF75
https://www.mintscan.io/sifchain/txs/F523A900303BF97BCEF9C90035EA8ED4B9E2273F44D7C7E900132037B3CA225C

I also checked the reward distribution (linked above), but the addresses of my affected wallets do not show up at all.

btw you're all doing a fantastic job and sorry for the difficulty in tracking my rewards that I probably caused myself due to arb actions and frequent LP adds and removals. 

And take all the time needed. Better to have the last Expansion reward payout properly audited than end up in giving out too much rewards which can't be reversed. We all want to see Sifchain strive and not have any unneccessary sell or compound pressure.

**Comment by emperorjm** [comment]
Hi @Rewardrequest. The last distribution that was to be done before the launch of the Ascension program has not been released due to the need for an audit which is being done. The distribution will be done as soon as the audit is completed.

**Comment by Rewardrequest** [comment]
Thanks for the response @emperorjm 

I know. That is why I have specifically stated that this request is not about the week before Ascension launched.
In the title I mentioned: "(-> not the current audit week)" and the date of the affected distribution: "2022-04-12"
That was 2 weeks prior Ascension launch and I just wanted to make sure that this is also being recalculated, as I'm not sure whether the audit only includes the last week.

I had this problem already one time, but back then the rewards have been sent out in the following week. As the following week was the week before Ascension launched, this did of course not happen. And again, just wanted to make sure that those wallets are included in the audit for the previous week.

**Comment by emperorjm** [comment]
The audit will be for the last two weeks before the audit as some users did not receive any rewards in that first week as well. We will keep this issue opened until those rewards are distributed.

**Comment by Rewardrequest** [comment]
Perfect, that's exactly what I was inquiring about. Thanks a lot!

**Comment by emperorjm** [comment]
@Rewardrequest were the rewards distributed to your account?
