### ISSUE TITLE
Wrong Text ETH-DAI 

### ISSUE THREAD

**Issue by ivorychristine** [Sifchain/Support-Tickets#340]
**Describe the bug**

A Detailed description of the issue (what happened, token affected and token amount)

when adding to ROWAN/ETH pool the confirmation says DAI
see attached picture

**How to Reproduce**

4. See error "..."

**Expected behavior**
<Please write a clear and detailed description of what you expected to happen.>

**TX Hashes** (if applicable)

Please provide links to transaction hashes of the import / export issues you are facing

**Addresses** (if applicable
<Please provide links to your addresses (both of Sifchain and external chain)>

**Error logs**
<Please provide links to your addresses (both of Sifchain and external chain)>

**Screenshots**

**Providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

![2022-05-02 04 46 12](https://user-images.githubusercontent.com/94232457/166163958-c3ab16bd-2fb1-443d-86f1-275f162319db.jpg)

**Comment by lufa23** [comment]
i just tried it out, it works good
