### ISSUE TITLE
User issued unbound request 12 days ago but did not receive tokens

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#341]
**Please write a detailed description of the issue.**
I unlocked liquidity 7 days ago and didn't receive it yet. Wasn't the unlocking period 7 days?

**What is the name and amount of the token affected?**
rowan

**What is your Sifchain address?**
2000

**What is your address on the other chain?**
The problem that I see is -

**What is the link to the transaction has you are having problem with?**
https://www.mintscan.io/sifchain/txs/49C5962F8EB0EB1935D805CEB1B004089B4B2173ED27F0DC34B48E6D08A1F9BC

**Are there any error logs you can share?**
https://www.mintscan.io/sifchain/txs/49C5962F8EB0EB1935D805CEB1B004089B4B2173ED27F0DC34B48E6D08A1F9BC

**Comment by emperorjm** [comment]
User didn't claim unbounded amount within the 3 days period after amount was unbounded and so the tokens were added back to the pool.
