### ISSUE TITLE
ETH export has not arrived to user's Ethereum wallet

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#342]
**Please write a detailed description of the issue.**
Exported ETH from Sifchain to Ethereum last night while gas was pumping. Gas has settles now and the ETH still hasn't arrived

**What is the name and amount of the token affected?**
0.478705509997872986ETH

**What is your Sifchain address?**
sif1q33zlx5zrg8wtkxpqsyz8gfz3f5j87p4yvd5qs

**What is your address on the other chain?**
0xc78A95019C52aD9856aA764D6908E88D5b7930eE

**What is the link to the transaction has you are having problem with?**
https://www.mintscan.io/sifchain/txs/A79A0028CA12EA6AFC512B52ACE783C002EF319C99E2FBD37B3DF29D0D0FCD35

**Are there any error logs you can share?**
no

**Comment by banshee** [comment]
Gas prices spiked (to around 6k gwei, far above the normal range) and the relayers errored out.  Relayers need to run the replay command for the following block range:

```
2022-05-01T02:46:11.169Z	INFO	relayer/cosmos.go:145	cosmos process events for blocks.	{"startingBlockHeight": 6648011, "currentBlockHeight": 6648011}
and ending with
2022-05-01T03:21:05.808Z	INFO	relayer/cosmos.go:145	cosmos process events for blocks.	{"startingBlockHeight": 6648354, "currentBlockHeight": 6648354}
```

**Comment by ghost** [comment]
@emperorjm - this has been resolved. Transaction was replayed and we can see the funds have been transferred successfully.

**Comment by emperorjm** [comment]
Thanks @intl-man. I'll relay this to the user.
