### ISSUE TITLE
Stuck ETH export

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#343]
**Please write a detailed description of the issue.**
Eth withdraw to ethereum from sif has been stuck for a while

**What is the name and amount of the token affected?**
Eth 3.5

**What is your Sifchain address?**
sif1djdvh237t5telq3u5mj8m2p3erkh454fpg3rzl

**What is your address on the other chain?**
0x3Efa23FE670E6640504F6920A40BfBF602da1531

**What is the link to the transaction has you are having problem with?**
https://www.mintscan.io/sifchain/txs/B6D6FD8F63803628249D12E7F301B599CC089E28C2A9E040442370167DF3DBA3

**Are there any error logs you can share?**
None, but it looks like the transaction went through on the sif side via mintscan. Maybe something stuck in the bridge?

**Comment by banshee** [comment]
Gas prices spiked (to around 6k gwei, far above the normal range) and the relayers errored out. Relayers need to run the replay command for the following block range:

```
2022-05-01T02:46:11.169Z	INFO	relayer/cosmos.go:145	cosmos process events for blocks.	{"startingBlockHeight": 6648011, "currentBlockHeight": 6648011}
and ending with
2022-05-01T03:21:05.808Z	INFO	relayer/cosmos.go:145	cosmos process events for blocks.	{"startingBlockHeight": 6648354, "currentBlockHeight": 6648354}
```

**Comment by emperorjm** [comment]
Tokens have been transferred to account https://etherscan.io/tx/0xf438f7d92482664a188386dcddc292f89cf3a66840a4acc7dc01e77ebeb5a8dd
