### ISSUE TITLE
Import Token to Sifchain

### ISSUE THREAD

**Issue by m4R7y91** [Sifchain/Support-Tickets#345]
I have problem with import UST to sifchain.
As i can see, transaction at terra chain is success. But in my sifchain account i cant see transfered token.
This is my second attempt to show an error.

My sif adress: sif1kx8s7mk9gjwn7ayt8yqjmxg32tky72kyw3flvk
Transaction TX : https://finder.terra.money/mainnet/tx/4594911916E06933CCB2903204B684D5FC9E2447FC3AC67A57413C463E3D661A

![photo_2022-05-10_16-29-58](https://user-images.githubusercontent.com/105298947/167653166-b93a65bd-4746-4698-9131-8b3193d3e856.jpg)

Thanks!

**Comment by lufa23** [comment]
hey we're on it

**Comment by lufa23** [comment]
Terra blockchain has halted several times..
