### ISSUE TITLE
BUG: Import  issue

### ISSUE THREAD

**Issue by botter100** [Sifchain/Support-Tickets#346]
I have imported 957 LUNA.
The transaction seems to have been successful, but after waiting for over 7 hours, it is not credited to my Sif wallet.

My sif address: sif1340h06astyxym5ahx5r0xvwc70myf6z4clftk9
My terra address:terra1c4ce9zq5ux8sqgwp7t644e89yxp42m6uy7a70f
Transaction TX : https://finder.terra.money/mainnet/tx/EBF8A5769DBDFA525F832F4A5B9AD98328E34C4EC895AEED3EF66443BBC56EDA

**Comment by lufa23** [comment]
hey we're checking

**Comment by botter100** [comment]
I would like to see a quick resolution to this issue as it is a very serious loss due to Luna's crash.

**Comment by lufa23** [comment]
yeah think is that with the networks halts and the congestions it's not something that depends on us. We are closely monitoring the channels if there are improvements that can be done from our side

**Comment by lufa23** [comment]
Informal is looking into this

**Comment by lufa23** [comment]
Informal is looking into this

**Comment by lufa23** [comment]
hey can you please confirm that this issue has been solved?
