### ISSUE TITLE
LUNA importing error

### ISSUE THREAD

**Issue by yp-cc01** [Sifchain/Support-Tickets#347]
Please help me as soon as possible! Most of my assets have been frozen!

## Describe the bug

After importing $LUNA from terra station wallet to Sifchain, the balance disappeared from terra station wallet but is not deposited in sif chain.

Transaction details are here.
https://finder.terra.money/mainnet/tx/98F130683804D29B8F401B7B29D2168A91B9C74496C3271497462FECFCA6797A

## How to Reproduce

1. Go to Sifchain "https://sifchain-dex.forbole.com/#/balances"
2. Connect Keplr wallet and Terra Station Wallet
3. Click balance.
4. Import LUNA

## Expected behaviour
The balance disappeared from terra station wallet but is not deposited in Sifchain.

## TX Hashes
https://finder.terra.money/mainnet/tx/98F130683804D29B8F401B7B29D2168A91B9C74496C3271497462FECFCA6797A

## Addresses
Terra station wallet address:
terra17pxzdzqr5mqp32zvxlc82sw4p8yl2rjm2592c4
Sifchain:
sif1cfd230y3dl0grad208hzunkluxdvlfjqxsd594

## Error logs
Please provide links to your addresses (both of Sifchain and external chain)

## Screenshots
Right after importing (1)
![image](https://user-images.githubusercontent.com/101242531/167746942-367aab2a-561a-40f7-8da8-8f7812ebd71b.png)
15 min after importing (2)
![image](https://user-images.githubusercontent.com/101242531/167747077-e05fcf2c-a871-48bf-b1ce-b558d64b7028.png)

**Comment by emperorjm** [comment]
Did you receive the tokens imported?
