### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by dmtrskv** [Sifchain/Support-Tickets#348]
## Describe the bug
Import of 4 LUNA. Completed 11 hours ago on Terra (2022.05.10 13:08:49 UTC), still nothing on Sifchain.

## TX Hashes
Terra: 38097D069AD1634DC67303E83AE42A3C3F8FE91F839FD961DA77D3012359D8EE

## Addresses
terra1vzz3877s99qhcfx3mjrrpwq5jlyjhexkqcamzf
sif1k0u7l860hxkfd4cy3mqxut0npvuupt7prjpwj3

**Comment by emperorjm** [comment]
@dmtrskv I am seeing where the tokens were refunded back to your Terra wallet.

**Comment by dmtrskv** [comment]
Yes, now I understand that there is a 1 day timeout. It expired few hours ago.
I see my Luna back in my Terra wallet.
Thank you!
