### ISSUE TITLE
Luna export issue

### ISSUE THREAD

**Issue by asotirov** [Sifchain/Support-Tickets#349]
## Describe the bug

Luna export has been stuck for more than 20 hours
Luna export doesn't work.

## How to Reproduce

Exporting Luna through the interface

## TX Hashes

CE0FFE75B6F6AA5D6CEFE106F955E21429F046B0C9C9B0861A638F003E07F9DA
B2B96950D4F0BB1FC3D7A37905C840C2057F1EE826CE9D258CEFA3B8808158CB
286D79B1D0DB937FE5FEA7DABD45087CBBFCC2F55BD1DBC40B5EDDEB20E6BEE7

## Addresses
Please provide links to your addresses (**both** of Sifchain and external chain)

The funds are supposed to be refunded but they weren't.

Thanks!

**Comment by emperorjm** [comment]
@asotirov were the tokens refunded to your account?

**Comment by asotirov** [comment]
They were refunded. Thank you
