### ISSUE TITLE
Unexpected token i in JSON at position 2

### ISSUE THREAD

**Issue by kacperlondon** [Sifchain/Support-Tickets#351]
**Describe the bug**

Hello could you help me with my problem I just tried to exchange some coins on the decks and I’ve got this information which I don’t know what’s going on could you please help me with that I also find out yesterday I received some unexpected rowan from this address  and i swap them for USDC        sif1nq2drdvx0tu32h5xfzweyfdlk0sprkup5ndeux 
I send you my address and copy of the alert I’ve got thank you very very much for your help
 sif1wv3csjcktxyhlfv5spwqv37dzm3gwtkcptn932       

**How to Reproduce**

<img width="866" alt="Screenshot 2022-05-13 at 15 10 36" src="https://user-images.githubusercontent.com/72800051/168308925-5108694d-98f0-4b5c-be18-d82ff599683a.png">

4. See error "..."

**Expected behavior**
<Please write a clear and detailed description of what you expected to happen.>

**TX Hashes** (if applicable)

Please provide links to transaction hashes of the import / export issues you are facing

**Addresses** (if applicable
<Please provide links to your addresses (both of Sifchain and external chain)>

**Error logs**
<Please provide links to your addresses (both of Sifchain and external chain)>

**Screenshots**

**Providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by emperorjm** [comment]
@khdegraaf The amount received from sif1nq2drdvx0tu32h5xfzweyfdlk0sprkup5ndeux is for the final payout of the Harvest rewards program. 

I just did a swap from USDC to RUNE on https://sifchain-dex.redstarling.com/ and it worked. Try clearing your browser's cache and try again.

**Comment by josie2222** [comment]
I have the same issue after clearing cache

it worked only for USDCx Rowan but will not work for ant other tokens..

please advise?
thanks.

**Comment by emperorjm** [comment]
@josie2222 are you still having this issue?

**Comment by josie2222** [comment]
yes!  sorry, I've never used github and didn't realize you would email me about it.
________________________________

**Comment by emperorjm** [comment]
Duplicate issue
