### ISSUE TITLE
Transactions fails intermittently with signature verification failure

### ISSUE THREAD

**Issue by emperorjm** [Sifchain/Support-Tickets#352]
I was able to SWAP from USDC to SAND with no issue but then trying to SWAP from SAND to ROWAN I get the following error:

**signature verification failed; please verify account number (169), sequence (308) and chain-id (sifchain-1): unauthorized**

On second try the SWAP goes through successfully.

<img width="1512" alt="Screenshot 2022-05-13 at 4 19 58 PM" src="https://user-images.githubusercontent.com/1245772/168391610-3245b883-e1e5-42c2-a4a7-4b60c48977c3.png">

Another user had the same error when trying to unbound liquidity.

![image](https://user-images.githubusercontent.com/1245772/168392146-99412e3f-9ec6-45f2-9f85-07217c1b2f1f.png)

**Comment by bksifchain** [comment]
@alanrsoares - could you pls take a look at the error on this swap issue? I've never seen this one before.

**Comment by lufa23** [comment]
@alanrsoares i guess we can close this right?
