### ISSUE TITLE
Unexpected token i in JSON at position 2

### ISSUE THREAD

**Issue by josie2222** [Sifchain/Support-Tickets#355]
**Describe the bug**

A Detailed description of the issue (what happened, token affected and token amount)

this has happened with every swap EXCEPT USDC

I clear cache everytime..

even when i was able to execute USDC (it only works 1 out of 7 times).

I've paid 20x rowan trying to do it after I clear my cache.

Hoping you can help..

Thanks for your time.

**How to Reproduce**

4. See error "..."

**Expected behavior**
<Please write a clear and detailed description of what you expected to happen.>

**TX Hashes** (if applicable)

Please provide links to transaction hashes of the import / export issues you are facing

**Addresses** (if applicable
<Please provide links to your addresses (both of Sifchain and external chain)>

**Error logs**
<Please provide links to your addresses (both of Sifchain and external chain)>

**Screenshots**

**Providing as much detail 
![Screen Shot 2022-05-15 at 9 50 32 PM](https://user-images.githubusercontent.com/105614739/168506866-508b4ea9-50b5-403e-896f-e0db487149cc.png)
as possible will help engineers to solve the case faster..**

Thanks!
[](url)

**Comment by lufa23** [comment]
I have tried now and everything seems fine..
Maybe there were the rpc endpoint was clogged.
 Can you let us know if the issue persists?

**Comment by josie2222** [comment]
still happening - same error in json at position 2

**Comment by lufa23** [comment]
can you try clearing the cache and refresh the browser?

**Comment by emperorjm** [comment]
@josie2222 this error could be related to setting the slippage too low.
