### ISSUE TITLE
The wallet received ROWAN tokens

### ISSUE THREAD

**Issue by FogFX77** [Sifchain/Support-Tickets#360]
# Liquidity Mining / Rewards issue

**Comment by FogFX77** [comment]
.

**Comment by lufa23** [comment]
hey, you are receiving rewards.
These are only some of the transactions:
https://www.mintscan.io/sifchain/txs/97D35A2ABEAE3E3FD7974E8AC89229753EA5C8595AB11F3EE6AF36F3B9B60BD0
https://www.mintscan.io/sifchain/txs/324020643FB0BEDEF517309BEA64CAFCCA06FB3A5C68CCBF77ABB0F5E1047E24
