### ISSUE TITLE
Swap issue 2 (ticket-318)

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#361]
**Please write a detailed description of the issue.**
I had a total of 1,616 USDC on the sifchain DEX.  I swapped half  (808) of my USDC to Rowan, which gave me roughly 4,783 Rowan.  However when I went to add liquidity to the Rowan/USDC pool the amount of Rowan requested was 7,811.  I didn't get that much Rowan on the swap.  As a result, I was only able to pool 490 USDC instead of 808 USDC.  This also happened with ATOM and USDT.

**What is the name and amount of the token affected?**
ATOM, USDC and USDT

**What is your Sifchain address?**
sif1wf6plm5slkg9zv9raf98wum4h2sr8c0sk5mhh3

**What is your address on the other chain?**
no other chain was affected.  This issue occurred within the liquidity pooling feature

**What is the link to the transaction has you are having problem with?**
327AF16DB3488DE4CC1D960DE921D40ABF488FDD070E0FD8BFB87CCCC521F4A7

40707F229E13CC4F37579036313CBE620E25B90FB16F3FD51F1CBF2890E94BD7

B97D4AC280956E5F1D5D9976ED0067E44C35B0B2AC02DF5406006278A22D2DE7

667B460B8A0D2716BD6BC65230359BFCE62328614527BCD18C1E53305CD6D4AA

**Are there any error logs you can share?**
all of the transaction logs are shown on mintscan

**Comment by lufa23** [comment]
hey, have you looked into the pool composition when adding liquidity?

With PMTP parameters chosen by on.chain governance, pool ratios may change. You can have a look at what PMTP is [here](https://docs.google.com/document/d/155ChKRm8hE2ja8MxltoaZV6nf5JiPg8I9PDTgsLDc5c/edit)

**Comment by lufa23** [comment]
you can also have a look [here](https://docs.sifchain.finance/project/pmtp)
