### ISSUE TITLE
Did not receive rewards: ticket-410

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#363]
**Please write a detailed description of the issue.**
No rewards

**What is the name and amount of the token affected?**
Usdc/rowan

**What is your Sifchain address?**
sif1h6mc4ja8e8mkp5w4amt2ce0y25w7ek3s0ahgdh

**What is your address on the other chain?**
0x2Da049645C0b1E4683Ba08C8667a93775F71d237

**What is the link to the transaction has you are having problem with?**
Liquidity no rewards

**Are there any error logs you can share?**
I haven't error

**Comment by emperorjm** [comment]
The user received the following payouts:
- https://www.mintscan.io/sifchain/txs/47D26CC7505C34C4E86F1B73DD6E9F006EAEFB0D6CF2AF549E8DCDF7373E0D82
- https://www.mintscan.io/sifchain/txs/F0FCC43E0846627EEA22B68BF18C597625D1E9AEF4267ADA67E8BBE781E314F3
