### ISSUE TITLE
Error exporting to IRISnet - ticket-412

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#364]
**Please write a detailed description of the issue.**
Trying to export IRIS and getting error.  Been like this for past 24hrs+

**What is the name and amount of the token affected?**
irisnet - exporting around 1200 to mainnet

**What is your Sifchain address?**
sif16j9u4u7u84wm3w09aed06uuktu2y4efz4srkwu

**What is your address on the other chain?**
iaa16j9u4u7u84wm3w09aed06uuktu2y4efz90v3rx

**What is the link to the transaction has you are having problem with?**
NA

**Are there any error logs you can share?**
just screen capture of what i uploaded

**Comment by emperorjm** [comment]
The issue has been relayed to the Devs.

**Comment by emperorjm** [comment]
The following error is shown in the console:

Access to fetch at 'https://proxies.sifchain.finance/api/irishub-1/rpc' from origin 'https://sifchain-dex.redstarling.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by emperorjm** [comment]
![image](https://user-images.githubusercontent.com/1245772/170307448-9ea6c8ff-1ff2-4ead-ad1d-0ef96ae70616.png)

**Comment by emperorjm** [comment]
Issue resolved by Notional.
