### ISSUE TITLE
Luna transferred to terra wallet missing - ticket-413

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#366]
**Please write a detailed description of the issue.**
Luna transferred out to Terra Wallet missing

**What is the name and amount of the token affected?**
Luna, 561.132308

**What is your Sifchain address?**
sif18y7xef0zxnns7ev44cch2wfathw74mlzw9zmra

**What is your address on the other chain?**
terra17ghljpjxczreejdmlpfeje8x82579mptsl4g57

**What is the link to the transaction has you are having problem with?**
No such link found

**Are there any error logs you can share?**
No error log was shown

**Comment by lufa23** [comment]
heya IBC packets cue has been cleared, can you check if the problem persists?
