### ISSUE TITLE
Imported UST missing - ticket-414

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#367]
**Please write a detailed description of the issue.**
I imported UST from terra station onto Sifchains "balance" page. It has not showed up and is not in the terra station wallet. 

Is there anyway to get it reversed back to my terrastation address?

**What is the name and amount of the token affected?**
UST 28400

**What is your Sifchain address?**
sif12j7rg02evw2nuzsq2llh8acvnwd3eltkshswy7

**What is your address on the other chain?**
terra1u4qqv0knn7w2p0vwwh7q4utrjruhjwdjxmc3we

**What is the link to the transaction has you are having problem with?**
https://finder.terra.money/mainnet/tx/C75BBC1ED3288C04C7872B2B356AC7CB2F55B217768FF0CE1BEDECD5C38A8FEE

**Are there any error logs you can share?**
no

**Comment by emperorjm** [comment]
The UST was transferred to this wallet terra1r726yra3euctv92qqfxh45xztewgp2qjjqp649 but not delivered to the users Sifchain account.
