### ISSUE TITLE
Only token in whitelist can be transferred to cosmos

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#368]
**Please write a detailed description of the issue.**
Hello.

**Problem with import of USDC from ETH to SIF.**

My wallet - [0x38ca8396E04e23299635Ea06fbb657e2a4e693c4](https://etherscan.io/address/0x38ca8396E04e23299635Ea06fbb657e2a4e693c4)

Failed TX - [0xa418d3eb10f028f198b8429482da9cd2f97ef6b69775a2f6967642d952ad6ef8](https://etherscan.io/tx/0xa418d3eb10f028f198b8429482da9cd2f97ef6b69775a2f6967642d952ad6ef8)

`Error for function "burn" - Fail with error 'Only token in whitelist can be transferred to cosmos'
`

Before today function "lock" was invoked by button "Import" at Sif's website.
Today function "burn" is invoked...

There failed transactions from other people for USDC too.

Please check.

**What is the name and amount of the token affected?**
USDC ( Eth )

16000

**What is your Sifchain address?**
sif15a5g72967828dqdh029eedk3t7hlqchyqv5lq6

**What is your address on the other chain?**
0x38ca8396E04e23299635Ea06fbb657e2a4e693c4

**What is the link to the transaction has you are having problem with?**
https://etherscan.io/tx/0xa418d3eb10f028f198b8429482da9cd2f97ef6b69775a2f6967642d952ad6ef8

**Are there any error logs you can share?**
Other failed transactions at Sif's contract

**Comment by Brando753** [comment]
It appears to be a frontend issue at first glance. The user should not be attempting to burn USDC but rather lock it, has the frontend logic swapped those two?

**Comment by bksifchain** [comment]
@tien @alanrsoares - did we introduce a regression somehow here?

**Comment by lufa23** [comment]
hotfix is building on staging

**Comment by lufa23** [comment]
hotfix v2.7.5 released, problem solved
