### ISSUE TITLE
XPRT import issue

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#369]
**Please write a detailed description of the issue.**
Hello, i cant import xprt

**What is the name and amount of the token affected?**
XPRT 780, IRIS 35000

**What is your Sifchain address?**
sif1msyzs6ng0psclpvrxacpndvrupgz0zzucyu8up

**What is your address on the other chain?**
0x12a0b8aC3bDe6dA2636e8F2297F40E9786aDEab3

**What is the link to the transaction has you are having problem with?**
no link

**Are there any error logs you can share?**
i think yes

**Comment by lufa23** [comment]
i couldn't import either, we are verifying the IBC channels

**Comment by lufa23** [comment]
<img width="663" alt="Screenshot 2022-05-26 at 18 45 06" src="https://user-images.githubusercontent.com/67415638/170581797-4910bc1e-931a-4ccb-9349-f49d43df931e.png">
<img width="687" alt="Screenshot 2022-05-26 at 18 44 52" src="https://user-images.githubusercontent.com/67415638/170581803-090c44b3-395e-458b-8e09-b3b27806a460.png">

**Comment by lufa23** [comment]
@bksifchain it seems to be a FE issue, because xprt import goes through but FE throws an error and import balance is still updating

**Comment by bksifchain** [comment]
Could be a couple things
1. FE is not forming the request properly and there's an error on entry
2. There could be an error on the node

Will continue to investigae

**Comment by lufa23** [comment]
hey can we close this issue?
