### ISSUE TITLE
Tokens missing after LUNA import - ticket-418

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#370]
**Please write a detailed description of the issue.**
Hi, I tried to import LUNA from my Terra Wallet to Sifchain and it did not work. However, the LUNA is missing from my wallet and the transaction appears as successful, here are the details: https://finder.terra.money/mainnet/tx/2CF24408B79B5568EAF7C6BE8EA553D333122A44025CFA236E46A92F8B608F31

**What is the name and amount of the token affected?**
20 LUNA

**What is your Sifchain address?**
sif195pu3prwn0fzw3y04dxrftclhhtthme9sfydrh

**What is your address on the other chain?**
terra1z5kzx87kycnwpfkzzcm3erscv7y505cf3hww33

**What is the link to the transaction has you are having problem with?**
https://finder.terra.money/mainnet/tx/2CF24408B79B5568EAF7C6BE8EA553D333122A44025CFA236E46A92F8B608F31

**Are there any error logs you can share?**
No

**Comment by lufa23** [comment]
heya IBC packets cue has been cleared, can you check if the problem persists?
