### ISSUE TITLE
Did not receive UST tokens - ticket-419

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#371]
**Please write a detailed description of the issue.**
I sent UST to sif from Terra several hours ago ... it left my wallet and the tx timed out and seems to be stuck in-between. Do I need to do anything? Was told it should come back automatically but it hasn't

**What is the name and amount of the token affected?**
UST (from terra), about 1400

**What is your Sifchain address?**
sif1jxfjp0xhwkq08kxg7nrnfw6ququ5n3f3f72um0

**What is your address on the other chain?**
terra1s7nxlep2jyux6p7pcpwqhlem7g6guk99c5dyvz

**What is the link to the transaction has you are having problem with?**
https://finder.terra.money/mainnet/tx/60CAA02DB7060E24B6CF97D997C657406EAA51EAF11A93FAC68DCAB95518C367

**Are there any error logs you can share?**
No

**Comment by lufa23** [comment]
heya IBC packets cue has been cleared, can you check if the problem persists?
