### ISSUE TITLE
BUG: LUNA export not working (ticket 421)

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#372]
**Please write a detailed description of the issue.**
Is LUNA Export available now in Sifchain?

**What is the name and amount of the token affected?**
430

**What is your Sifchain address?**
sif10fgqa9pjtw9m9qrxduayahe5fagsd8unajmt8t

**What is your address on the other chain?**
terra1twgdkpdqhpqqwzqjfyw0hulncrqgvzmtzpc8wf

**What is the link to the transaction has you are having problem with?**
I am not too sure

**Are there any error logs you can share?**
No

**Comment by lufa23** [comment]
heya! can  you please check if the problem persists? Channel should be active now
https://www.mintscan.io/sifchain/txs/AB44EABF7E50DF9EF4480BC147D01BFB0440BCCB9E8DA923DB52DF504E937D9D
