### ISSUE TITLE
BUG: LUNA export not working (ticket 420)

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#373]
**Please write a detailed description of the issue.**
Moving from sifchain to terra station, the pending time is over 10 hours. Isn't this a serious problem?

**What is the name and amount of the token affected?**
luna

**What is your Sifchain address?**
sif19vcxq9rjp0dnl30rk308cjqhcu9tq7e5wdyg4q

**What is your address on the other chain?**
terra station wallet

**What is the link to the transaction has you are having problem with?**
https://www.mintscan.io/sifchain/txs/657C52E7BE1E20D55072FA96EE1CF852F2B8981B90FED3953CBE614B1B6AED36

**Are there any error logs you can share?**
no

**Comment by lufa23** [comment]
heya can you confirm if the issue has been solved? Channels should be active again
