### ISSUE TITLE
REGEN Import from ethereum issue

### ISSUE THREAD

**Issue by tuthanden9999** [Sifchain/Support-Tickets#375]
## Describe the bug
I can't import REGEN token from ethereum network to sifchain.

## How to Reproduce

1. Go to (https://sifchain-dex.redstarling.com/#/balances)
2. On (Search Token...), enter Regen
3. After only Regen token is listed, click (Import) button, then dialog (Import Token to Sifchain) appear
4. In (Network) combobox, select Ethereum
5. Error: In (Token) combobobox is empty, and can't found Regen on (Token) combobox

## Expected behaviour
After select Ethereum in (Network) combobox, still display Regen on (Token) combobox, and load Regen balance from Ethereum network. Then, import Regen from Ethereum network.

## TX Hashes
No TX Hashes

## Addresses
Ethereum: 0xFf7c6De1293d363dC2BF307B1614B48B21781Be8
Sifchain: sif16xjt0aplv4l753qxydt2dzrntc5g5jy6cunh6q

## Error logs
No logs

## Screenshots
![image](https://user-images.githubusercontent.com/21007362/170839812-9d47c4b8-0423-4400-b385-7410328e7a7d.png)

**Providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by lufa23** [comment]
it worked for me, can you try again and let us know if the issue persists?

**Comment by lufa23** [comment]
also, can you use the browser devtools and send us a screenshot of the console logs?
<img width="704" alt="devtools" src="https://user-images.githubusercontent.com/67415638/170975316-0230b098-b99c-4e91-98a8-cab81c591a2e.png">

**Comment by tuthanden9999** [comment]
This issue still occur.
Please check console at attach image.

![consoleLog](https://user-images.githubusercontent.com/21007362/171230057-2c829947-51ba-4b2e-9e70-5cbedab43793.PNG)

**Comment by tuthanden9999** [comment]
I also try to clear cache, disconnect and reconnect many times, but issue still occur.

**Comment by lufa23** [comment]
Can you please show us the console logs?
![Screenshot 2022-06-01 at 15.05.08.png](https://images.zenhubusercontent.com/6050a28ecf34f141cf22d02a/42105a25-d2d2-4265-bf9e-5013a7132ff9)

**Comment by tuthanden9999** [comment]
![consoleLog2](https://user-images.githubusercontent.com/21007362/171807765-4d581840-5386-4954-adae-1a711fa30fa0.PNG)

Please see Console Log with above attach image.

**Comment by lufa23** [comment]
looking at your address, i cannot see any Regen ERC-20 on your ethereum wallet.. I am not sure why should you be able to import it from ethereum to sifchain if you don't have it on ethereum in the first place.. am i missing something here?

**Comment by tuthanden9999** [comment]
Yes, I swapped REGEN ERC-20 to EROWAN since 12 days ago.
Please see transaction:
https://etherscan.io/tx/0x375e8068033a8a010b437e2a6c9ef98c9cc07d9e33fdde3ef356fa137b0fa583

Why I do it? Because I can't wait you handle too long and see REGEN price go down on bear market. I will lost more money if I continue to wait you, please understand me.
This issue still occur, I'm sure. 
Please focus on reproduce steps, logs, and solve it. You can use a new sifchain address and new ethereum address and clear cache and retry this issue, I think will reproduce easily.
And, I see REGEN ERC-20, AKT ERC-20, XPRT ERC-20, IRIS ERC-20 all have above isssue, you also can check them too.
Thanks and hope this issue will resolved soon.

**Comment by lufa23** [comment]
thanks for the info, let us get back to you

**Comment by lufa23** [comment]
hey can you try following [this guide](https://docs.google.com/document/d/161bXWtViU7R2K1UnicHVFnXhcNi00jT2pbFekruwMMM/edit?usp=sharing)?
We suggest starting with a small amount, as we currently cannot guarantee 100% on it, as focus is on Peggy 2.0

**Comment by lufa23** [comment]
closing the issue for now. Feel free to re-open it when needed

**Comment by tuthanden9999** [comment]
Hi, I tried following [this guide](https://docs.google.com/document/d/161bXWtViU7R2K1UnicHVFnXhcNi00jT2pbFekruwMMM/edit?usp=sharing)

But I got error when excute transaction, when metamask dialog appear.
Please check the below infors and image:
Token: AKT (ERC20)
Token contract: 0xc727f87871ee12bbcedd2973746d1deb7529aad6
Ethereum address: 0xC7BD4F27fd0B802bC687AD4162ca31fd6b4c4465
Sifchain address: sif1qq3a83xxsaxwnlzv7pche8pjh4ktyj5ffx0yd6
Amount: 969.976323 AKT

So now I can't transfer AKT token from ethereum to sifchain. Please check and help me as soon as possible.
Thank you very much!

Detail error image:
![errAkt](https://user-images.githubusercontent.com/21007362/188358835-3cff3593-de59-4650-8842-e348ee096f92.PNG)
