### ISSUE TITLE
Community Complaint - 2

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#376]
Write a detailed description of your complaint 

someone in chat was mean to me. help me. i want to talk to the owner

**Comment by Stellar-tickets** [comment]
LALALALA: this is just a test

**Comment by Stellar-tickets** [comment]
LALALALA: testing testing

**Comment by Stellar-tickets** [comment]
LALALALA:

**Comment by Stellar-tickets** [comment]
LALALALA:

**Comment by Stellar-tickets** [comment]
LALALALA: !!close

**Comment by lufa23** [comment]
testing
