### ISSUE TITLE
Bug Report: Unable to unbound liquidity using a Ledger - 4

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#377]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

When using LEDGER,
"Liquidity unbond request" have an issue that cannot be Cancel.

**Comment by Stellar-tickets** [comment]
sif_baldr: <@855790915036512307> can you share the error logs from the console as well.

**Comment by Stellar-tickets** [comment]
cosya: Ok
I filed an issue on github.

**Comment by Stellar-tickets** [comment]
cosya: OK
I have submitted an issue to github.

**Comment by Stellar-tickets** [comment]
cosya: ○ Pool: ROWAN / ATOM

○ Error message:
"Failed to cancel liquidity unbond request"

○ Chrome - Developer Tools -> Console
“stargate”, “no-legacy-stdTx” feature has been deprecated.
The launchpad is no longer supported, thus works without the two features.
We would keep the aforementioned two feature for a while,
but the upcoming update would potentially cause errors.
Remove the two feature.

index.54c99700.js:335 Error: Broadcasting transaction failed with code 4 (codespace: sdk).
Log: signature verification failed;
please verify account number (48676),
sequence (2) and chain-id (sifchain-1): unauthorized
at Proxy.broadcastTx (index.54c99700.js:27:70308)

**Comment by Stellar-tickets** [comment]
sif_baldr: We are looking into this.

**Comment by lufa23** [comment]
hey, the unbonding button has been officially removed..
You can have a look at discord for the announcement:
https://discord.com/channels/769209144515100693/773772812019564574/984088324006346842

**Comment by Stellar-tickets** [comment]
sif_baldr: <@855790915036512307> are you still having this issue?

**Comment by Stellar-tickets** [comment]
LALALALA: !!close
