### ISSUE TITLE
BUG: Ledger: Fail to send token

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#378]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

Keplr error
When using LEDGER,
IBC token (eg ATOM) cannot be transferred from "Sifchain address 1" to "Sifchain address 2".

Error Message:
"Ledger: Fail to send token: Data is invalid : Unrecognized error code"

**Comment by lufa23** [comment]
![ibctokenerr](https://user-images.githubusercontent.com/67415638/171131249-7098dbbe-40c4-46d4-9afd-acc78596a2a3.jpg)

**Comment by Stellar-tickets** [comment]
lufa23: hey let us look into it

**Comment by Stellar-tickets** [comment]
cosya: This issue was already submitted to github a month ago.
It's still not resolved.
https://github.com/chainapsis/keplr-wallet/issues/368
https://github.com/cosmos/ledger-cosmos/issues/65

**Comment by Stellar-tickets** [comment]
sif_baldr: <@855790915036512307> the failed to Send token would be a Keplr issue as that was done directly via Keplr. You would need to submit a ticket to the Keplr team for that issue. In regards to your other issue to unbond liquidity we are looking into it.

**Comment by lufa23** [comment]
hey, i have pinged the Ledger team as the issue could be on their side.. let's see if this spin up the resolution

**Comment by lufa23** [comment]
issue seems to be on Zondax's side.. I have opened [a ticket in the Zondax repository](https://github.com/Zondax/ledger-cosmos-js/issues/56)

**Comment by Stellar-tickets** [comment]
lufa23: hey the issue seems to be on Zondax's side.. I have opened a ticket in the Zondax repository
https://github.com/Zondax/ledger-cosmos-js/issues/56

**Comment by Stellar-tickets** [comment]
lufa23: Could you try again and use the devtools and record a video or screenshots on all the console logs you get?

**Comment by Stellar-tickets** [comment]
cosya: using Keplr wallet With LEDGER,
When sending IBC token (ATOM) to Sifchain address1->Sifchain address2
No message is generated in the console of Google Chrome.

Messages are generated only in the Keplr window.
   "Ledger: Fail to send token: Data is invalid : Unrecognized error code"

**Comment by Stellar-tickets** [comment]
cosya: correction)
The Keplr error message does not contain the text "Ledger: ".
Error Message:
"Fail to send token: Data is invalid : Unrecognized error code"

**Comment by Stellar-tickets** [comment]
cosya: Reference)
Keplr v0.10.5
Ledger nano X - Firmware: v2.0.2, Cosmos App v2.34.4

**Comment by Stellar-tickets** [comment]
lufa23: thanks, we are investigating

**Comment by lufa23** [comment]
blocked as per:
https://github.com/Zondax/ledger-cosmos-js/issues/56

**Comment by Stellar-tickets** [comment]
cosya: Ledger cosmos App v2.34.6 released
Send issue of IBC Token is fixed

**Comment by Stellar-tickets** [comment]
sif_baldr: !close

**Comment by Stellar-tickets** [comment]
sif_baldr: !!close
