### ISSUE TITLE
Bug: Stuck Terra tx

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#379]
**Description:**
LUNA transfer has been successfully send from Sifchain, but not Received on Terra.
Packet is still pending since 3 days
**Link to the transaction:** https://www.mintscan.io/sifchain/txs/828E348A571905769936C3A439D7BD0BE69C12753CEC291DF2DCC230EC34716A

**Link to the Terra address:**
https://finder.terra.money/mainnet/address/terra1erds4vtgf96wz683cv5c6arpqvm6mf4h9d8y26

**Screenshot:**
![Screenshot 2022-06-01 at 17.52.37.png](https://images.zenhubusercontent.com/6050a28ecf34f141cf22d02a/47bc207d-21d4-4fe7-94ea-202a02169050)

**Comment by Stellar-tickets** [comment]
lufa23: it should get reverted soon
cc <@476844095499796491>

**Comment by Gideon20222** [comment]
@lufa23 


* Have you gotten your funds? If not,You’re experiencing transcript error. Sorry for this inconvenience, Please reach out to [Terra Ecosystems Support Team](http://terramoneysupport.com/) with the ticket id LUN474768 using the livechat page, the best team of dev will assist you on the issue immediately.

**Comment by lufa23** [comment]
hey can you confirm that the funds arrived?

**Comment by Stellar-tickets** [comment]
lufa23: hey <@738842482842009661> can you confirm you received the funds?

**Comment by Stellar-tickets** [comment]
cltrader: hi there. sorry for the delay. No I have not received the funds

**Comment by Stellar-tickets** [comment]
cltrader: Still pending: https://www.mintscan.io/sifchain/txs/828E348A571905769936C3A439D7BD0BE69C12753CEC291DF2DCC230EC34716A

**Comment by Stellar-tickets** [comment]
cltrader:

**Comment by Stellar-tickets** [comment]
cltrader:

**Comment by Stellar-tickets** [comment]
cltrader: Not in my wallet

**Comment by Stellar-tickets** [comment]
cltrader: <@694599887680962692> and <@940008313230344192> <@476844095499796491> can we please fix this. Going on 10 days here.

**Comment by Stellar-tickets** [comment]
sif_baldr: <@738842482842009661> I have reached out to the devs to rectify the issue.

**Comment by Stellar-tickets** [comment]
cltrader: <@476844095499796491>  Following up. Still nothing. Can you please reach out again?

**Comment by Stellar-tickets** [comment]
cltrader: Where else can I go for help. This is just ridiculous.

**Comment by Stellar-tickets** [comment]
lufa23: hey, the funds have been already credited to your account:
https://finder.terra.money/classic/tx/89F916F04EFF295F5C71A3786500A67E25665E1D35AB898C54AC688F4A45C28F

**Comment by Stellar-tickets** [comment]
LALALALA: !!close
