### ISSUE TITLE
Secret import failed - 8

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#380]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

A transaction from Keplr to Sif failed and I lost 64+ SCRT

**Comment by Stellar-tickets** [comment]
sif_baldr: The transaction timed out and was refunded to your Scret account

**Comment by emperorjm** [comment]
@ghuznee this is not actually a bug as this happens from time to time with IBC transfers where if the transaction times out the tokens are refunded to the users wallet. Will close this issue.

**Comment by Stellar-tickets** [comment]
lufa23: !!close
