### ISSUE TITLE
Bug: Unable to SWAP from ROWAN to OH - 10

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#381]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

Issue on swap erorr: Unexpected token i in JSON at position 2

**Comment by emperorjm** [comment]
Response from user:

**im trying to swap from rowan to OH
getting Unexpected token i in JSON at position 2
tried also higher slippage but nothing same error**

**Comment by emperorjm** [comment]
As per my response to a similar issue here https://github.com/Sifchain/Support-Tickets/issues/355 this issue could be related to the slippage being too low.

**Comment by Stellar-tickets** [comment]
sif_baldr: <@711624984505876640> can you share the slippage being used?

**Comment by Stellar-tickets** [comment]
Draaker: hello sorry for late response.

**Comment by Stellar-tickets** [comment]
Draaker: so i tried right now.. but the chain looks very slow

**Comment by Stellar-tickets** [comment]
Draaker:

**Comment by Stellar-tickets** [comment]
Draaker:

**Comment by Stellar-tickets** [comment]
Draaker: tested with 0.5% slippage

**Comment by Stellar-tickets** [comment]
Draaker: testing with 1.5% slippage

**Comment by Stellar-tickets** [comment]
Draaker:

**Comment by Stellar-tickets** [comment]
Draaker: error 504

**Comment by Stellar-tickets** [comment]
Draaker: idk

**Comment by Stellar-tickets** [comment]
sif_baldr: Hi <@711624984505876640>. I just successfully did a SWAP from ROWAN to OH with 1% slippage. Are you using a ledger device?

**Comment by Stellar-tickets** [comment]
Draaker: yes using ledger..

**Comment by Stellar-tickets** [comment]
sif_baldr: Oh. I think there is an issue with Ledger. The team is working on getting a fix but I believe it was only restricted to liquidity addition and removal. Let me update the issue.

**Comment by Stellar-tickets** [comment]
Draaker: thanks

**Comment by Stellar-tickets** [comment]
sif_baldr: Hi <@711624984505876640>. Can you try again and let me know if you are the same issue.

**Comment by Stellar-tickets** [comment]
Draaker: nope

**Comment by Stellar-tickets** [comment]
Draaker: ticket can be close.

**Comment by Stellar-tickets** [comment]
Draaker: thanks

**Comment by Stellar-tickets** [comment]
sif_baldr: !!close
