### ISSUE TITLE
BUG: Button CLAIM doesn't work 

### ISSUE THREAD

**Issue by SergeyZver** [Sifchain/Support-Tickets#382]
**Describe the bug**

Hi. I wanted to take the coins out of the pool and put them into staking. After I waited 7 days, the CLAIM button doesn't work. I click on CLAIM and that's it, nothing else happens. Reloaded the page ctrl+F5 and ctrl+r it does not help. 

**Screenshots**
![image](https://user-images.githubusercontent.com/103934319/171900497-246cb0ab-a0d2-4298-a9ec-3ee89563d5af.png)

sif17aznmpghekl9hqlew82wxsuu2fzwrr6s8322zx

Thanks!

**Comment by lufa23** [comment]
hey, can ypu use the browser DevTools and show us the logs you get from the console?
<img width="704" alt="devtools" src="https://user-images.githubusercontent.com/67415638/171922855-6d76ff55-6fa9-4017-a745-8914c5f2a434.png">

**Comment by nikinosuke** [comment]
Hello!
I tried to unbond my Rowan/Atom pool, but after 7days, there were no claim button and all the coins were in the pool again.
Is there any possible reason for this phenomenon?
During the unbonding period I could see the announcement “3more days “”2 more days “.

**Comment by nikinosuke** [comment]
I can paste the photo of my DevTools if needed.

**Comment by lufa23** [comment]
hey, the unbonding button has been officially removed
You can have a look at discord for the announcement:
https://discord.com/channels/769209144515100693/773772812019564574/984088324006346842
