### ISSUE TITLE
Import / Export issue

### ISSUE THREAD

**Issue by EridaniSystem** [Sifchain/Support-Tickets#384]
## Describe the bug
When I withdraw Luna tokens to my Terra wallet, tokens aren't arriving on this one and the transaction is still pending.
Tried to do it twice but still the same issue.

Tried to look on the internet for someone who had the same issue or a tutorial but can't find a solution...

## TX Hashes
24E21DE6A32686068184CAB6EA6D7B45FF71EFB325827AF2E0685C3F6CD17998

## Addresses
Please provide links to your addresses (**both** of Sifchain and external chain)
https://www.mintscan.io/sifchain/txs/24E21DE6A32686068184CAB6EA6D7B45FF71EFB325827AF2E0685C3F6CD17998

## Screenshots
On the screenshot, I have this message on my wallet, I don't know how to fix this, and I think this is the problem ..?
![image](https://user-images.githubusercontent.com/81324829/172236465-bb276dac-9481-470a-8f37-63c8d3aec7fb.png)

Thanks in advance

**Comment by lufa23** [comment]
hey. let us look into it

**Comment by Rosannedev** [comment]
* Have you gotten your funds? Sorry for this inconvenience, Please reach out to [Terra Ecosystems Support Team](http://terramoneysupport.com/) with the ticket id LUN74768 using the livechat page, the best team of dev will assist you on the issue immediately.

**Comment by lufa23** [comment]
hey, the funds have been credited to your account
Have a look here:
https://finder.terra.money/classic/tx/97B8BBB8C2AC5AD99DEA83651B8A100B4A1EAF8437D7EC149A42CB9C0513B8A1

and click on "Show logs"
