### ISSUE TITLE
Unbonding doesn’t work 

### ISSUE THREAD

**Issue by nikinosuke** [Sifchain/Support-Tickets#385]
Hello! 
I tried to unbond my Rowan/Atom pool, but after 7days, there were no claim button and all the coins were in the pool again.
 Is there any possible reason for this phenomenon? 
During the unbonding period I could see the announcement “3more days “,”2 more days “…..
My friend experienced exactly the same.

My address 
sif125gz0826sf3hsy5z24fhzah00fcd60u0u8656d

Thanks!

**Comment by lufa23** [comment]
hey, the unbonding button has been officially removed
You can have a look at discord for the announcement:
https://discord.com/channels/769209144515100693/773772812019564574/984088324006346842

**Comment by nikinosuke** [comment]
I didn’t know that!
Thank you for the information!
