### ISSUE TITLE
BAND token swap issues

### ISSUE THREAD

**Issue by Mitya8** [Sifchain/Support-Tickets#386]
Translation:

When exchanging BAND tokens in SWAP, the amount of tokens is not shown

Good afternoon! Tell me why Band is listed in the list of tokens available for swap, and when choosing it as a token that I want to receive as a result, swapa does not give out the amount that will result from the exchange. The BAND token is not on ETH, but the usual one on BandChain. I have been observing this situation for a couple of days.

**Comment by lufa23** [comment]
Original message:`


Добрый день! Подскажите, почему Band указана в списке доступных для swap токенов, а при выборе её как токена который хочу получить в результате swapa не выдаёт суммы которая получится в результате обмена. Токен BAND не на ETH, а обычный на BandChain. Данную ситуацию наблюдаю уже пару дней.`

**Comment by lufa23** [comment]
@bksifchain it seems there are two Band tokens on the FE, and swaps can be made only with the ethereum version. I attach the console logs i get
![Screenshot 2022-06-09 at 19 48 11](https://user-images.githubusercontent.com/67415638/172914180-405ba612-92e2-4237-97f5-54008a5b0251.png)
![Screenshot 2022-06-09 at 19 48 04](https://user-images.githubusercontent.com/67415638/172914187-41ed81da-4354-4a27-b875-1924a4fe680d.png)
![Screenshot 2022-06-09 at 19 45 54](https://user-images.githubusercontent.com/67415638/172914190-1e6b7910-71b0-4d57-8917-68f0de9e87a2.png)

![Screenshot 2022-06-09 at 19 48 18](https://user-images.githubusercontent.com/67415638/172914166-28e206df-a0b0-44b2-9f9a-377068be20ad.png)

**Comment by lufa23** [comment]
Some exports and imports have been currently disabled. i guess we can close this issue for now
