### ISSUE TITLE
Luna export to Terra Station failed

### ISSUE THREAD

**Issue by nstevens778** [Sifchain/Support-Tickets#387]
I followed the instructions to export my Luna on Sifchain to Terra Station and it seems to be stuck (c 20 hours now). It hasn’t made it to Terra station

The TX ID is

76398ED61F7139CB0E95AF00BA8EE12778599C9D8F3CDC4D61B7DFF2BB5F764E

Please can you assist? 

Thank you

**Comment by lufa23** [comment]
hey, let us check

**Comment by Rosannedev** [comment]
* Have you gotten your funds? If not,You’re experiencing transcript error. Sorry for this inconvenience, Please reach out to [Terra Ecosystems Support Team](http://terramoneysupport.com/) with the ticket id LUN74768 using the livechat page, the best team of dev will assist you on the issue immediately.

**Comment by nstevens778** [comment]
> hey, let us check

hey Lufa23, Is Rosannedev and the link they provided a scam?

**Comment by EridaniSystem** [comment]
Any update on this problem ?
I have the same issue and have two pending transactions since 10 days now...

**Comment by nstevens778** [comment]
Nope…. Nothing

**Comment by lufa23** [comment]
hey, the packet has been properly relayed and the funds are in your account
Have a look here:
https://finder.terra.money/classic/tx/2e3381c52043f3a3b30f18aee46622cb1f4c4b08e4c039309d802fe940b122e0

Scroll down and click on "Show logs"

**Comment by nstevens778** [comment]
> hey, the packet has been properly relayed and the funds are in your account Have a look here: https://finder.terra.money/classic/tx/2e3381c52043f3a3b30f18aee46622cb1f4c4b08e4c039309d802fe940b122e0
> 
> Scroll down and click on "Show logs"

Thanks a lot all good now
