### ISSUE TITLE
 unbonding liquidity not working

### ISSUE THREAD

**Issue by kacperlondon** [Sifchain/Support-Tickets#388]
# Liquidity Mining / Rewards issue
Hi I unbond my liquidity from two poles on Saturday 4 June and  now it looks like nothing happened Bad on Saturday show me reminding time 7days

Write here a clear and detailed description of what the bug is.

## Pool(s) affected
<Please write here the pool(s)you are having issues with>.

## Liquidity Add transaction(s)
Please write here details on the provided liquidity(amount, pairs and date) and the links to those transactions.

## Claim transaction(s)
Please write here details on the claim transactions (amount, pairs and date) and the links to those transactions

## Sif address
Please write here your sif address
sif1wv3csjcktxyhlfv5spwqv37dzm3gwtkcptn932

## Expected Reward amount / Received amount
Please write here details on the rewards amounts you were expecting

## Reward Program title
Please write here the name of the reward program you are having issues with

## Error logs/Screenshots
Please add here error logs you are receiving/ screenshots>

**Keep in mind that providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by lufa23** [comment]
hey! the unbonding button has been officially removed..
You can have a look at discord for the announcement:
https://discord.com/channels/769209144515100693/773772812019564574/984088324006346842
