### ISSUE TITLE
Feedback on token decimals - ticket 14

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#390]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

Github ticket: With bear market conditions it seems we are going to need an extra decimal on subzero price tokens to show accurate prices
for example dvpn has been showing .001 as its price for a while
but the next decimal has fluctuated a lot for the past 2 months: 0.00121478 to 0.00193122

**Comment by Stellar-tickets** [comment]
LALALALA: there is a link to the ticket so you can check on the progress

**Comment by lufa23** [comment]
hey, let us look into it

**Comment by Stellar-tickets** [comment]
lufa23: hey, let us look into it

**Comment by lufa23** [comment]
hey, i can see already 6 decimals.. are you suggesting to increase it to more than 6 decimals?

<img width="575" alt="Screenshot 2022-06-15 at 14 32 13" src="https://user-images.githubusercontent.com/67415638/173827658-2f9eb800-5959-42a8-83c1-6eb1ea7ca86c.png">

**Comment by Stellar-tickets** [comment]
sif_baldr: !!close
