### ISSUE TITLE
Frontend Bug - Evmos

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#391]
**Description:**
When swapping Evmos throws a JSON position error depending on swapped amount

![432343](https://user-images.githubusercontent.com/67415638/173450550-d8fd450f-6d23-4bb2-a053-cde9d9e443e4.png)

![34534](https://user-images.githubusercontent.com/67415638/173450561-894a9ff2-3225-476b-ba04-8ae9ed848c20.png)
![434323](https://user-images.githubusercontent.com/67415638/173450557-c1fd1649-e6de-44a3-960c-49472a587f03.png)

**Comment by lufa23** [comment]
hey the pool is currently inactive, as we need to build a custom wallet connector for it.
We will announce once the pool is operational

**Comment by Stellar-tickets** [comment]
sif_baldr: !!close
