### ISSUE TITLE
Different background colour in DEX theme

### ISSUE THREAD

**Issue by lufa23** [Sifchain/Support-Tickets#393]
# User Interface Issue
## Describe the bug
Background cover image for the DEX has a grey and black background colour (rather than just black)

## To Reproduce
Please write here the steps to reproduce the behavior, for example:
1. Go to [Sifchain DEX](https://sifchain.akash.pro/#/swap?from=uatom&to=rowan&slippage=1.0)
2. Click on the bottom to change theme (on the bottom right)
3. Change the theme to the black background and gold sif coin
4. See difference in background colour

## Expected behavior
A whole black background, instead of grey and black
## Screenshots

<img width="576" alt="Screenshot 2022-06-16 at 14 37 54" src="https://user-images.githubusercontent.com/67415638/174072378-52485170-72b9-4fbb-a1ed-045fedce6a71.png">
<img width="1270" alt="Screenshot 2022-06-16 at 14 45 41" src="https://user-images.githubusercontent.com/67415638/174072683-3594ccaa-ebee-485f-91bd-0c02a2e2dc04.png">

<img width="695" alt="Screenshot 2022-06-16 at 14 45 49" src="https://user-images.githubusercontent.com/67415638/174072708-244b1ddf-ca87-4c11-9e71-7791e9d01405.png">

**Comment by lufa23** [comment]
contacted design team to check if the issue can be solved by a background resizing and FE

**Comment by merkletreeibc** [comment]
Hey @bksifchain Who would be responsible for fixing this? We're getting close to launchings and having the dex look super snazzy is important for conversion

**Comment by bksifchain** [comment]
Hey @zadkiel88 - I'm actually not sure who provided these images in the first place ... we prob just need a new one without that weird artifact. Might be something that @sifmoon or Sebastian knows?

**Comment by merkletreeibc** [comment]
I'll ask Sebastian if he can help us 🙂

**Comment by sifmoon** [comment]
It was from John Kappa I believe. We may be able to reach him still if needed. Just let me know

**Comment by merkletreeibc** [comment]
Hey Brian, can you send me specs for this image? I think our graphic
designer can probably do this pretty easily

**Comment by merkletreeibc** [comment]
Closing this because @alanrsoares fixed it!

**Comment by merkletreeibc** [comment]
HI all, someone please send me specs for this image and I will have a new
one made. Citadel is trying to launch their dApp and it looks absolutely
awful. I would like get our graphic designer to do a new version of this
wallpaper for them.

https://sifchain.slack.com/archives/G01BX71QY1F/p1657523508559809
