### ISSUE TITLE
Swap bug ROWAN - UST, UST - ROWAN

### ISSUE THREAD

**Issue by egor2310** [Sifchain/Support-Tickets#396]
I did a simple swap for the test and noticed such a bug. I swapped 1 rowan per 0.58 UST (ERC-20) and swapped after 35 minutes 0.58 UST per 2.1 rowan

![image](https://user-images.githubusercontent.com/36264515/176221864-c157f20f-57e6-4dbe-97e5-2ec2e0cd9a32.png)
![image](https://user-images.githubusercontent.com/36264515/176221940-d0dfc7c6-b796-450a-9e50-aed592433be7.png)
![image](https://user-images.githubusercontent.com/36264515/176222367-e6ac5c49-451b-40a2-831a-4e85545c0967.png)

TxHash
3AA946C800E275AE7E3CB0C3E8E9943190B80F22D1F87687F0BD29B68C515157

TxHash
01CC5C0EFCF05C9A4A10DED59A6D9A1EE4B75A94353F157411A63FE60148EBA3

I don't know why it happened, but it didn't work again

**Comment by egor2310** [comment]
sif1npn394yu983mn7j9mu94ckdzn5vravmn2zets0

**Comment by lufa23** [comment]
hey @egor2310 , as volatility for UST has been quite high, it does not seem a bug but normal pool behaviour
