### ISSUE TITLE
Import / Export issuetransaction did not arrive

### ISSUE THREAD

**Issue by ANDREY0077** [Sifchain/Support-Tickets#398]
## Describ   TxHash
D90604D1E909DF771B6DDC5D6B874273578A28B5A15D495CDC0247B90A7B52ED                            e the bug

A Detailed description of the issue (what happened, token affected and token amount)

## How to Reproduce

4. See error "..."

## Expected behaviour
Please write a clear and detailed description of what you expected to happen.

## TX Hashes
Please provide links to transaction hashes of the import / export issues you are facing

## Addresses
Please provide links to your addresses (**both** of Sifchain and external chain)

## Error logs
Please provide links to your addresses (both of Sifchain and external chain)

## Screenshots

**Providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by lufa23** [comment]
hey, [the transaction failed](https://www.mintscan.io/sifchain/txs/D90604D1E909DF771B6DDC5D6B874273578A28B5A15D495CDC0247B90A7B52ED) as you tried to export slightly more Rowan than you actually had...

Which Web UI did you use to try the export? (Akash, RedStarling,ConsensusOne, Forbole..)

let us know if the issue persists
