### ISSUE TITLE
transaction did not arrive

### ISSUE THREAD

**Issue by ANDREY0077** [Sifchain/Support-Tickets#399]
**Describe the bug**
TxHash
F93D7150C66C11B2056CDBD53648862E00340FBC51291B0077EB3393EEDDEF2C
A Detailed description of the issue (what happened, token affected and token amount)

**How to Reproduce**

4. See error "..."

**Expected behavior**
<Please write a clear and detailed description of what you expected to happen.>

**TX Hashes** (if applicable)

Please provide links to transaction hashes of the import / export issues you are facing

**Addresses** (if applicable
<Please provide links to your addresses (both of Sifchain and external chain)>

**Error logs**
<Please provide links to your addresses (both of Sifchain and external chain)>

**Screenshots**

**Providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by ANDREY0077** [comment]
TxHash
D90604D1E909DF771B6DDC5D6B874273578A28B5A15D495CDC0247B90A7B52ED                     transaction did not arriv
![cd8b3ce5-2b0c-47f1-97db-4c754e68e12c](https://user-images.githubusercontent.com/108954373/179545990-5440512e-298b-4e99-b3c0-a9013140a289.jpg)
e

**Comment by lufa23** [comment]
hey,[ the transaction failed](https://www.mintscan.io/sifchain/txs/F93D7150C66C11B2056CDBD53648862E00340FBC51291B0077EB3393EEDDEF2C) as you tried to export slightly more Rowan than you actually had...

Which Web UI did you use to try the export?

let us know if the issue persists
