### ISSUE TITLE
Pool Stats Balance + Auto-Text Dropdowns

### ISSUE THREAD

**Issue by Saerithrael** [Sifchain/Support-Tickets#400]
Suggestion for adding auto textbox selection when pressing drop-down button on swap page to show token list. I instinctually move my hands to the kb once I hit the drop-down, many probably do to?
Also, what if we showed token balance in pool stats for accounts, that way users have more of an advantage for arb against bots.

Thanks

**Comment by lufa23** [comment]
thanks for the feedback! Gonna look into it

**Comment by lufa23** [comment]
assuming this to be fixed in FEv3
