### ISSUE TITLE
Cannot add liquidity with asymmetric ratio

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#401]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

Cannot add to pool ROWAN/UFO.   "There was an unknown error."  Error failed to execute message; message index: 0: Cannot add liquidity with asymmetric ratio.

**Comment by lufa23** [comment]
hey, can you try again? it's a known issue, and it's due to the fact that we disabled asymmetric adds

**Comment by lufa23** [comment]
this is the same issue as:
[395](https://github.com/Sifchain/Support-Tickets/issues/395) and [389](https://github.com/Sifchain/Support-Tickets/issues/389).

What's our strategy here? @bksifchain  (My understanding is that we won't re-enable asymmetric liquidity adds anytime soon)

**Comment by lufa23** [comment]
@hungng157 i have flagged this issue on the **eng-support** slack channel

**Comment by Stellar-tickets** [comment]
lufa23: <@&961371260003172402>

**Comment by Stellar-tickets** [comment]
sif_baldr: Hi <@299720068059627524>. Were you using a Ledger device?

**Comment by Stellar-tickets** [comment]
FrothyPint: No

**Comment by Stellar-tickets** [comment]
FrothyPint: Keplr using Brave browser

**Comment by Stellar-tickets** [comment]
sif_baldr: Ok. We are looking into this issue.

**Comment by Stellar-tickets** [comment]
sif_baldr: Hi <@299720068059627524>. So the issue is that the pool is very shallow at the moment and the current asymmentric threshold  is causing the issue. The team is working on a new asymmetric formula which will take a few weeks to implement which means the issue will persist until the new formula is implemented.

**Comment by Stellar-tickets** [comment]
sif_baldr: !!close
