### ISSUE TITLE
Eth not credited after export

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#402]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

I export from sifchain to ETH main net yesterday.
But still it's not arrived my ETH wallet.
what should I do ?

https://www.mintscan.io/sifchain/txs/911D921172C26C5E6BDE911B406987E65D5E47ED83372B15F2711E6BE63FB765

**Comment by lufa23** [comment]
hey, let us check

**Comment by lufa23** [comment]
Informal has been contacted to look into the stuck packet

**Comment by Stellar-tickets** [comment]
lufa23: <@&961371260003172402>

**Comment by hungng157** [comment]
already pinged and waiting responses from chainops team

**Comment by Stellar-tickets** [comment]
VJyou.eth//YuAyato: Hi, any update?

**Comment by Stellar-tickets** [comment]
karan.patel: <@&961371260003172402>

**Comment by Stellar-tickets** [comment]
hungng: Hi, we are working on the issue. We will notify you asap when there is any update

**Comment by Stellar-tickets** [comment]
sif_baldr: These tokens were transferred to the user's account approximately 8 minutes ago https://etherscan.io/tx/0x9d17f165938f1cc9244552716ea742a5fa53880ee0f8aa2d7ce146c9ddd1e1d7. There was an issue on our end which has been rectified.

**Comment by Stellar-tickets** [comment]
VJyou.eth//YuAyato: I checked it correctly arrived.
Thx guys.

**Comment by Stellar-tickets** [comment]
sif_baldr: !!close
