### ISSUE TITLE
Metis not credited after export

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#404]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

Hello, I tried to export Metis tokens, But I can’t receive it on my[ Ethereum address](https://etherscan.io/address/0x4e68eca9ec5620ef33a4a41cdb4772a3cee421c3#tokentxns).
The transition hash: [A3D0FA377D79C78F341D0F6F6D6FA7221CBAA8D906E3DAC2F3F28EAFCF298DE6](https://www.mintscan.io/sifchain/txs/A3D0FA377D79C78F341D0F6F6D6FA7221CBAA8D906E3DAC2F3F28EAFCF298DE6)

**Comment by Stellar-tickets** [comment]
lufa23: hey, let us look into it

**Comment by lufa23** [comment]
Contacted informal to unstuck the packet

**Comment by Stellar-tickets** [comment]
LarryShum: Hello devs, I exported UFO tokens to Ethereum network 3 hours ago, but I can’t receive the tokens. The Txhash is https://www.mintscan.io/sifchain/txs/2E69789056432F8E521431A5BB4D1B6DFCC030B3DA8B0AF1A7B9B8F151C17B5A

**Comment by Stellar-tickets** [comment]
Kym | Community Manager: kindly create separate ticket for your issues at <#943694093542912011>

**Comment by hungng157** [comment]
already pinged and waiting responses from chainops team

**Comment by Stellar-tickets** [comment]
sif_baldr: Our devs had worked on the problem and I am now seeing where these tokens were finally transferred to the user's account https://etherscan.io/tx/0x570167cf81554540de2131ae43439ffde8a6b10b7b2914457c8a09cb180f69f3.

**Comment by Stellar-tickets** [comment]
lufa23: !!close
