### ISSUE TITLE
Import / Export issue

### ISSUE THREAD

**Issue by Hazbless** [Sifchain/Support-Tickets#405]
## Describe the bug

A Detailed description of the issue (what happened, token affected and token amount)

## How to Reproduce

1. Go to 'main page'
2. Click on 'export'
3. Scroll down to 'metamas
4. See error "no tokens"

## Expected behaviour
I exported usdc to my metamask account , it has been 22 hours and the funds are nowhere to be found 

## TX Hashes

5E0A58DDD430EB3D3BBA152DC64E7B8702545FC724943E2E6393FFC96FC79BC4

## Addresses
Sifchain
sif1d6k5lqa9zygn5wxugnagjllk9lp55l9jfha0n5

Ethereum
0x7c8310A52247113Cc79B94D1397CE82caBFcF9B7

## Error logs
no error logs

## Screenshots
no screenshot needed

Please help me get the funds back 

**Providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by lufa23** [comment]
hey @Hazbless , is this issue fixed?

**Comment by Hazbless** [comment]
Yes
