### ISSUE TITLE
Export ETH tokens from Sif to Ethereum but got nothing from Ethereum side

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#406]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

Hello, exported ETH tokens from Sif to Ethereum.

But got nothing of Ethereum side 😦

Burn Tx at sif is https://www.mintscan.io/sifchain/txs/F95324FEFC6FE8FF4B9F727E01CFF2E4D6836FA88C2A13902313F42EA890AD0F

Please help

**Comment by Stellar-tickets** [comment]
hungng: <@&961371260003172402> <@476844095499796491>

**Comment by smartyalgo** [comment]
Don't think this is the right mintscan link, but the referenced tx is now successful. https://etherscan.io/tx/0xc673ebe3119ec71d29f0092a518cb52bcf598954172c93228cf349b6d93add67

**Comment by smartyalgo** [comment]
Reopening, Closing https://app.zenhub.com/workspaces/current-sprint---engineering-615a2e9fe2abd5001befc7f9/issues/sifchain/support-tickets/409 instead. Please update mintscan link

**Comment by Stellar-tickets** [comment]
sif_baldr: <@401377690231373835> the tokens have been transferred to your account https://etherscan.io/tx/0xc673ebe3119ec71d29f0092a518cb52bcf598954172c93228cf349b6d93add67

**Comment by Stellar-tickets** [comment]
s_oa_d: Thanks

**Comment by Stellar-tickets** [comment]
hungng: !!close
