### ISSUE TITLE
Cannot receive UFO tokens exported to Ethereum network

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#407]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

Hello devs, I exported UFO tokens to Ethereum network 3 hours ago, but I can’t receive the tokens. The Txhash is https://www.mintscan.io/sifchain/txs/2E69789056432F8E521431A5BB4D1B6DFCC030B3DA8B0AF1A7B9B8F151C17B5A

**Comment by hungng157** [comment]
pinged the chainops on eng-support and waiting for response

**Comment by smartyalgo** [comment]
Tx is successful. Token deposited on EVM side, see https://etherscan.io/tx/0xd24378e9c871fd478fe8b75c014dbdb848682b41ef9564d701c9112bdf9e7f52

**Comment by Stellar-tickets** [comment]
sif_baldr: <@919553377107582977> the tokens were transferred to your wallet about an hour ago https://etherscan.io/tx/0xd24378e9c871fd478fe8b75c014dbdb848682b41ef9564d701c9112bdf9e7f52

**Comment by Stellar-tickets** [comment]
lufa23: !!close
