### ISSUE TITLE
ZCX not credited after export

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#409]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

https://www.mintscan.io/sifchain/txs/E85D4DE81CE33FDFC3630B62463A95F2705D34DD4BF98FA9BD359F3C9A1FFAC7 still didnt recieve

**Comment by smartyalgo** [comment]
Referenced tx is now successful. https://etherscan.io/tx/0xc673ebe3119ec71d29f0092a518cb52bcf598954172c93228cf349b6d93add67

**Comment by Stellar-tickets** [comment]
sif_baldr: <@104082588687138816> your tokens are now in your wallet https://etherscan.io/tx/0x198393c915cf8329668f879aca74cfbfaea51a6de809e51cbae635ebac1dac11

**Comment by Stellar-tickets** [comment]
ski: thanks

**Comment by Stellar-tickets** [comment]
hungng: !!close
