### ISSUE TITLE
Bug Report - 30 - help in the javascript api used to exchange tokens for sifchain from the tutorial

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#410]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

Hello, I need help in the javascript api used to exchange tokens for sifchain from the tutorial at

https://sifchain.stoplight.io/docs/sifchain/xqqtiise8vszx-swap-one-token-for-another

Everything works for me, I can exchange tokens, but I cannot set the minimum acceptable number of tokens after the exchange, i.e. a slip, sometimes the exchange is very unfavorable in the web version and you can set a 0.5% or 1% slip

I found such a fragment in the code but I don't know how to configure it:

value: {

signer: firstAccount.address,

sentAsset: {symbol: rowan.denom.toString ()},

receivedAsset: {symbol: usdc.denom.toString ()},

// sentAmount: "1000000000000000000",

// minReceivingAmount: "4191",

sentAmount: Decimal.fromUserInput (rowanSwapAmount, rowan.decimals.toNumber ()). atomics,

minReceivingAmount: Decimal.fromUserInput (swap.minimumReceiving.toString (), usdc.decimals.toNumber ()). atomics,

**Comment by emperorjm** [comment]
The simulation done should give you the information you require:

```
const swap = await signingClient.simulateSwap(
        {
            denom: rowan.denom,
            amount: Decimal.fromUserInput(rowanSwapAmount, rowan.decimals.toNumber()).atomics,
        },
        { denom: usdc.denom },
        0.05,
    );
```
The 0.05 would be the slippage. So you can adjust the slippage there and therefore the minimum received value will be adjusted accordingly. If when executing the swap the minimum received is less then the swap would be reverted.

**Comment by Stellar-tickets** [comment]
Swype: And can I define in the code that, for example, I replace 20 frax and I want to receive 20 usdc if I were to receive less, i.e. 19.95 or 19.50, the transaction will be canceled ??

**Comment by Stellar-tickets** [comment]
sif_baldr: The transaction will be cancelled if the SWAP returned less tokens than the minimum received value set. The simulation function tries to calculate this value which you use in 

`minReceivingAmount: Decimal.fromUserInput(**swap.minimumReceiving.toString()**, usdc.decimals.toNumber()).atomics,`

You can set this to whatever value you want but the SWAP won't be successful unless you receive more than or equal to that amount.

**Comment by Stellar-tickets** [comment]
Swype: <@476844095499796491> where I have to enter two stars for the values that interest me??

**Comment by Stellar-tickets** [comment]
sif_baldr: Hi <@896817192803377192>. I'm not sure I understand the question.

**Comment by Stellar-tickets** [comment]
Swype: Where in the code you sent me should I enter the minimum number of tokens I want to exchange? where are the two stars?

**Comment by Stellar-tickets** [comment]
sif_baldr: The value "swap.minimumReceiving.toString()". The stars in the post above was used to try to bold the text in between so will remove that.

**Comment by Stellar-tickets** [comment]
Swype: Is it supposed to be like this?
if he wants to get no less than $ 20?

minReceivingAmount: Decimal.fromUserInput (swap.minimumReceiving.toString (20), usdc.decimals.toNumber ()). atomics,

**Comment by Stellar-tickets** [comment]
sif_baldr: If you want to not receive less than 20 then you would add 20.

`minReceivingAmount: Decimal.fromUserInput(20, usdc.decimals.toNumber()).atomics,`

I am not sure why you would want to hardcode a value though. As shown above you can set the slippage in the simulation function signingClient.simulateSwap to reduce the the amount you could loose in a swap.

**Comment by Stellar-tickets** [comment]
Swype: I am already testing it in various ways and I do not want to work for me, if I change the code and rigidly insert the value, the exchange does not take place, even if I exchange 2 usdc and set the minimum value to 1, it does not mention it either; /

**Comment by Stellar-tickets** [comment]
sif_baldr: Which is the reason why the simulation call is done to calculate as accurately as possible what the minimum receivable amount should be based on the slippage set.

**Comment by Stellar-tickets** [comment]
Swype: all the code looks like this

**Comment by Stellar-tickets** [comment]
Swype: even if I set the slip to something like 0.0005
sometimes transactions are lost a lot, maybe I have something wrong in the code when changing the default tokens to mine, i.e. usdc and frax ??

**Comment by Stellar-tickets** [comment]
sif_baldr: If the slippage is too low more than likely the swap will not go through. On the DEX the default is 1% and the lowest is 0.5% which is 0.005 which might be too low in most cases. Use the DEX as a guide and it's best to use the simulation call unless you definitely know what you are doing.

**Comment by Stellar-tickets** [comment]
Swype: I wanted to set the slip as low as possible so that the tokens were more or evenly and if it was to be less, the transaction would not take place, but from what I can see, the slip parameter, regardless of what value I put there, does not change anything for me, you can check if my code is correct, I only modified the exchangeable tokens there, but I did it by trial and error because I do not know coding;)

**Comment by Stellar-tickets** [comment]
sif_baldr: I have executed multiple swaps using the sample code provided in the docs. If the swap doesn't work try increasing the slippage.

**Comment by Stellar-tickets** [comment]
lufa23: hey <@896817192803377192> has the issue been solved?

**Comment by Stellar-tickets** [comment]
lufa23: !!close
