### ISSUE TITLE
User could not delegate Rowan to BlockEngine

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#411]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

Cannot delegate rowan to BlockNgine, it just spins the circle indefinitely

**Comment by Stellar-tickets** [comment]
hungng: Hi, can you see the transaction after you delegate ?

**Comment by ghuznee** [comment]
@hungng157 to review Kepler issue

**Comment by Stellar-tickets** [comment]
hungng: Hi, I think the issue may be with Keplr, since I can delegate to BlockNgine now. Please update to the latest version of Keplr wallet

**Comment by Stellar-tickets** [comment]
lufa23: !!close
