### ISSUE TITLE
Cannot Use Kelpr Wallet on Claiming reward/delegate/undelegate

### ISSUE THREAD

**Issue by NhatMinh77777** [Sifchain/Support-Tickets#412]
Hi Sifchain, I can not claim my staking reward. I tried for thousand times, even set the high gas. It still Inform "ERROR" on transaction. I nead a Help 

![image](https://user-images.githubusercontent.com/110441950/182287271-913cf669-0661-41de-b134-023b09c7d162.png)
 
I also check my claiming reward transaction and it inform me that the transaction was success. But I cant recieve it
My wallet address is sif1zkv0ktz97u0kr5gy0u2f8wv3uzv2dsfw8tjve3 and sif1xnadr806ewzarp698mgt60k7w5vcpwv8kxxvxc

**Comment by NhatMinh77777** [comment]
I also check my claiming reward transaction and it inform me that the transaction was success. But I cant recieve it

**Comment by Almorigi** [comment]
I have the same issue

**Comment by Almorigi** [comment]
Please answer to me too

**Comment by lufa23** [comment]
hey @Almorigi @NhatMinh77777 , is the issue fixed?

**Comment by Almorigi** [comment]
Yes, it's ok

Il lun 22 ago 2022, 12:38 lufa23 ***@***.***> ha scritto:
