### ISSUE TITLE
All UI requests to rpc.sifchain.finance unreliable since at least 03 Aug

### ISSUE THREAD

**Issue by antonymous-a** [Sifchain/Support-Tickets#415]
Hello team,

When the UI requests swap prices, balances, etc from rpc.sifchain.finance some of the responses are with old block height. It seems that some of the nodes in the load balancer set are lagging. This creates problems with swapping. LP providing, checking pool stats, etc.

1. Go to any of the dex urls - ie https://sifchain.akash.pro/#/swap?from=rowan&to=uatom&slippage=0.5
2. Click on swap rowan to atom and open developer console
3. Inspect a bunch of the POST requests to rpc.sifchain.finance
4. Some of them are returning the latest height, but many of them are returning info with old block height - at least up to 20,000 blocks off

**Screenshots**

![image](https://user-images.githubusercontent.com/2785577/182843871-4f29bc0a-68e5-4b58-999a-8a5d9b286e1d.png)
![image](https://user-images.githubusercontent.com/2785577/182844034-cea2d5bf-7992-4fec-ba9c-f60970f76679.png)
 
I have noted this behavior for at least a day or two.

Thanks!

**Comment by emperorjm** [comment]
Will forward this issue to the Devs

**Comment by lufa23** [comment]
hey, can we considered this issue fixed?

**Comment by antonymous-a** [comment]
I will close it and reopen it if I see this problem again,
