### ISSUE TITLE
Bug Report - 37: Import Eth to Sif doesn't work

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#417]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

Hello, import from Eth to Sif doesn't work.

Here is the TX in Eth network - https://etherscan.io/tx/0x717e1127ffeddebd043d9256cecfc3a04675861dcb81b2d7c87b1a529ca8889d

My wallet at Sif is sif15a5g72967828dqdh029eedk3t7hlqchyqv5lq6

There are more than 130 confirms at time of creating of ticket
Please help\

there are even TXs in Mintscan
but there were never Metis tokes at my wallet
( mean Metis tokens from this exact transfer from Ethereum (
https://www.mintscan.io/sifchain/txs/4CB4570E45342DAF49A7CA86D328216A58EB4ED17F5EC98339E18B432BF1ACB5

and
https://www.mintscan.io/sifchain/txs/4FE69E475D1F218865E557CE1C41064BE726A0B51947D714A6C97FC584B0F3E6

**Comment by Stellar-tickets** [comment]
sif_baldr: The team is working on the fix and once the tokens have been transferred I'll post here.

**Comment by Stellar-tickets** [comment]
s_oa_d: Hi, thanks for info.

Will they be transferred to Sif wallet? ( or back to Eth wallet? )

**Comment by Stellar-tickets** [comment]
s_oa_d: guys, I see incoming and outgoing TXs working ( it's visible at explorer, guy was sending and taking out USDC )

**Comment by Stellar-tickets** [comment]
s_oa_d: when will you solve my case?

**Comment by Stellar-tickets** [comment]
hungng: Have you received the token now ?

**Comment by Stellar-tickets** [comment]
s_oa_d: no, Meitis tokens are neither on Sifchain wallet, nor on Ethereum wallet

**Comment by Stellar-tickets** [comment]
s_oa_d: it's been almost 4 full days since TX

**Comment by smartyalgo** [comment]
need to rerun ethereum block  15277120

**Comment by ghost** [comment]
@smartyalgo - can you provide the ETH and Sif block ranges I should use?

**Comment by Stellar-tickets** [comment]
s_oa_d: anyone?

**Comment by smartyalgo** [comment]
@intl-man 
Ethereum starting block: 15277120
Ethereum ending block: 15277120

Sif Starting block: 8000263
Sif Ending block:   8006387

Please run this on validator Alice and Jenna

**Comment by Stellar-tickets** [comment]
sif_baldr: Hi <@401377690231373835>. I responded to your query in the private DMs. The team will be executing a replay of the transaction to have the tokens transferred to your account. I will let you know as soon as this is done.

**Comment by Stellar-tickets** [comment]
sif_baldr: You can see responses from the devs here https://github.com/Sifchain/Support-Tickets/issues/417

**Comment by Stellar-tickets** [comment]
sif_baldr: I spoke to the devs earlier and they said they executed the replay but there were some issues so they are looking to redo it today. Sorry for the inconvenience.

**Comment by Stellar-tickets** [comment]
s_oa_d: almost 24 hours since your message

still nothing...

**Comment by Stellar-tickets** [comment]
s_oa_d: --
one more day is gone

still nothing...

**Comment by Stellar-tickets** [comment]
Ducksquaddd: You will probably hear back monday, its the weekend my friend

**Comment by hungng157** [comment]
Hi @smartyalgo any update on this issue ?

**Comment by Stellar-tickets** [comment]
sif_baldr: Hi <@401377690231373835>. Sorry for the long delay. We are having some issues executing the replay to get the tokens to you and the last test was done yesterday. The devs are working on the issue and I am hoping for it to be resolved soon. I am really sorry for the inconvenience.

**Comment by Stellar-tickets** [comment]
sif_baldr: <@401377690231373835> you should now have access to your tokens. Please let me know if there are any other issues.

**Comment by Stellar-tickets** [comment]
s_oa_d: thanks, all is fine now👍

**Comment by Stellar-tickets** [comment]
hungng: !!close
