### ISSUE TITLE
Bug Report - 38: Imported ETH onto sifchain but now showing up on sifchain

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#418]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

I imported ETH onto sifchain, and it is not showing up on sifchain, despite being a successful transfer. The transaction ID is 0xa21091222745d449cdbeba5ab0f833b59066a0299d091085fb5ed7115cb1b6c7

https://etherscan.io/tx/0xa21091222745d449cdbeba5ab0f833b59066a0299d091085fb5ed7115cb1b6c7

**Comment by Stellar-tickets** [comment]
sif_baldr: The team is working on the fix and once the tokens have been transferred I'll post here.

**Comment by Stellar-tickets** [comment]
sif_baldr: <@753689919448285294> did you receive your tokens?

**Comment by Stellar-tickets** [comment]
adamzlegal: Good Morning, unfortunately no, the tokens are still missing from my account.

**Comment by Stellar-tickets** [comment]
adamzlegal: Any idea of when the issue will be resolved?

**Comment by Stellar-tickets** [comment]
sif_baldr: The Devs are currently working on it. It should be soon but I can't give an exact time.

**Comment by Stellar-tickets** [comment]
adamzlegal: Ok, thank you.

**Comment by smartyalgo** [comment]
Need to rerun for ethereum block 15279076

**Comment by ghost** [comment]
@smartyalgo - can you provide the ETH and Sif block ranges I should use?

**Comment by smartyalgo** [comment]
@intl-man 
Ethereum starting block: 15279076
Ethereum ending block: 15279076

Sif Starting block: 8004597
Sif Ending block: 8006387

Please run this on validator Alice and Jenna

**Comment by Stellar-tickets** [comment]
adamzlegal: Good morning, sorry to bother you, but just wanted to see if there was any update?

**Comment by Stellar-tickets** [comment]
sif_baldr: Hi <@753689919448285294>. Sorry for the long delay. It should be rectified today as the dev just need to replay the transaction.

**Comment by Stellar-tickets** [comment]
adamzlegal: Thank you!

**Comment by Stellar-tickets** [comment]
adamzlegal: Hi, sorry to bother you again; still haven't received the tokens.

**Comment by Stellar-tickets** [comment]
sif_baldr: I spoke to the devs earlier and they said they executed the replay but there were some issues so they are looking to redo it today. Sorry for the inconvenience.

**Comment by Stellar-tickets** [comment]
adamzlegal: Ok, thank you for the update, and I appreciate your help!

**Comment by Stellar-tickets** [comment]
adamzlegal: Good morning, any update? Kind of starting to lose hope.

**Comment by Stellar-tickets** [comment]
sif_baldr: Hi <@753689919448285294>. I am really sorry for the long delays. We have two other users waiting on their tokens as well. The Devs are having some issues executing the replay to get the tokens to you and the last test was done yesterday. They are however working on the issue and I am hoping for it to be resolved soon. I am really sorry for the inconvenience.

**Comment by Stellar-tickets** [comment]
adamzlegal: Ok, thank you for the update; I appreciate your help

**Comment by Stellar-tickets** [comment]
sif_baldr: <@753689919448285294>  you should now have access to your tokens. Please let me know if there are any other issues.

**Comment by Stellar-tickets** [comment]
adamzlegal: I’ll definitely check when I get home, hopefully it’s all good. Appreciate your help, thank you!

**Comment by Stellar-tickets** [comment]
lufa23: hey <@753689919448285294> can you confirm that the issue has been fixed?

**Comment by Stellar-tickets** [comment]
lufa23: !!close
