### ISSUE TITLE
Bug Report - 39: Lost asset when swapping from Mana to Atom

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#421]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

Hi guys
I did an exchange with rango exchange
And after fist step
Its stuck for more than 4hours
I canseled it 
My swap was MANA on Eth to Atom on cosmos
Fisrt step was swap to mana on sifchain
Now my asset lost
And its no where

Inbound tx : https://etherscan.io/tx/0xfed77655b7e2f6ab82fdf17e61e0fec06d28a51d6d90caa77929008a741b6de8

Outbound Tx  : https://www.mintscan.io/sifchain/txs/4B6ED9D0A5BE67517C6D2DE56F2DC530F6B945CD49FEB4986E3617419E27A389

**Comment by banshee** [comment]
From that ethereum transaction, destination sif account is sif1323uenwvychnv4gplx9895w43tcd66lufhqmq3

**Comment by banshee** [comment]
We need to replay block 15274867

**Comment by Stellar-tickets** [comment]
hungng: Hi, our devs are working on the issue. We will notify you asap

**Comment by Stellar-tickets** [comment]
hamidzzzzz: Hey , Thanks to u and devs 🙌🏼

**Comment by ghost** [comment]
@smartyalgo - can you provide the ETH and Sif block ranges I should use?

**Comment by smartyalgo** [comment]
@intl-man 
Ethereum starting block: 15274867
Ethereum ending block: 15274867

Sif Starting block: 7995293
Sif Ending block: 8006387

Please run this on validator Alice and Jenna

**Comment by Stellar-tickets** [comment]
sif_baldr: I spoke to the devs earlier and they said they executed the replay but there were some issues so they are looking to redo it today. Sorry for the inconvenience.

**Comment by Stellar-tickets** [comment]
hamidzzzzz: Is it will add to my sifchain network on keplr ? Or it will get complited exchange and come to my cosmos atom ? Or somwhere else could u clearfield me pls , thanks … ❤️

**Comment by Stellar-tickets** [comment]
hamidzzzzz: Any update guys ?!

**Comment by hungng157** [comment]
cc @smartyalgo

**Comment by Stellar-tickets** [comment]
hungng: Hi, I have pinged the dev ? It's weekend on their time so I will notify you any updates

**Comment by Stellar-tickets** [comment]
sif_baldr: Hi <@822106398183784460> . Sorry for the long delay. We are having some issues executing the replay to get the tokens to you and the last test was done yesterday. The devs are working on the issue and I am hoping for it to be resolved soon. I am really sorry for the inconvenience.

**Comment by Stellar-tickets** [comment]
hamidzzzzz: 🙌🏼

**Comment by Stellar-tickets** [comment]
sif_baldr: <@822106398183784460> you should now have access to your tokens

**Comment by Stellar-tickets** [comment]
sif_baldr: Please let me know if there are any other issues.

**Comment by Stellar-tickets** [comment]
hamidzzzzz: Thanks to u and dev team 🙌🏼 problem solved

**Comment by emperorjm** [comment]
Tokens received

**Comment by Stellar-tickets** [comment]
sif_baldr: !close

**Comment by Stellar-tickets** [comment]
sif_baldr: !!close
