### ISSUE TITLE
Executing multiple swaps in quick succession causes an error

### ISSUE THREAD

**Issue by emperorjm** [Sifchain/Support-Tickets#423]
If multiple swaps are done in a short period of time an error similar to the following is thrown:

**Broadcasting transaction failed with code 32 (codespace: sdk). Log: account sequence mismatch, expected 525, got 528: incorrect account sequence**'

<img width="1512" alt="Screenshot 2022-08-10 at 9 51 07 AM" src="https://user-images.githubusercontent.com/1245772/183936767-e96cd481-9858-409e-aa1b-804c49342b9e.png">

A community member TechStacker has been experiencing this issue constantly for the past few days.

**Comment by Jedi2002** [comment]
This is expected . If two transactions are submitted from the same same account before the block is committed the seq does not get updated 
You could potentially use the following flags to make things work 
--broadcast-mode async --sequence <add sequence > --account-number <account number here>

Just that the seq would need to be manually incremented on the client side . 


something like this 

```
#!/usr/bin/env bash
seq=1
sifnonded tx clp .... --broadcast-mode async --sequence seq --account-number <account number here>
seq=$((seq+1))
sifnonded tx clp .... --broadcast-mode async --sequence seq --account-number <account number here>
```
