### ISSUE TITLE
Balances keep fluctuating - Bug Report - 41

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#425]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

My balance on Sifchain oscillates wildly

**Comment by Stellar-tickets** [comment]
sif_baldr: Hi <@922698824223445033>. Thanks for creating this ticket. I will pass this on to the devs right now.

**Comment by emperorjm** [comment]
Video showing issue:

https://user-images.githubusercontent.com/1245772/184212109-e82e570c-be90-4977-bbc4-889db750fadb.mp4

**Comment by Stellar-tickets** [comment]
pandaslovetigers: Thanks

**Comment by Stellar-tickets** [comment]
pandaslovetigers: But my keplr wallet is also displaying an incorrect balance

**Comment by Stellar-tickets** [comment]
pandaslovetigers: Hi guys

**Comment by Stellar-tickets** [comment]
pandaslovetigers: Any updates?

**Comment by Stellar-tickets** [comment]
pandaslovetigers: It's been a few days that my balance disappeared, and I can do nothing on the DEX

**Comment by Stellar-tickets** [comment]
sif_baldr: Hi <@922698824223445033>. The report was made to the Devs and they are looking into the issue. I will bring it up to them again right now.

**Comment by Stellar-tickets** [comment]
pandaslovetigers: Thanks a lot

**Comment by Stellar-tickets** [comment]
pandaslovetigers: I'm itching to use the DEX again :)

**Comment by Jedi2002** [comment]
Hey , is your balance showing up correct via the cli ? 
To get access to the cli , follow these steps 
```
git clone https://github.com/Sifchain/sifnode.git
cd sifnode 
make install
```
Then run the following command 

```
sifnoded q bank balances <put you address here >
```

**Comment by Stellar-tickets** [comment]
sif_baldr: <@922698824223445033> are you still experiencing this issue now?

**Comment by Stellar-tickets** [comment]
pandaslovetigers: Dear @sif_baldr, right now I am at a conference, far from my computer. Can I let you know on Thursday, when I will get back?

**Comment by Stellar-tickets** [comment]
hungng: sure

**Comment by Stellar-tickets** [comment]
pandaslovetigers: Hi there

**Comment by Stellar-tickets** [comment]
pandaslovetigers: It looks that my balance disappeared

**Comment by Stellar-tickets** [comment]
pandaslovetigers: It doesn't oscillate anymore; just gone

**Comment by Stellar-tickets** [comment]
pandaslovetigers: To be more detailed:

**Comment by Stellar-tickets** [comment]
pandaslovetigers: I withdrew from two lp positions

**Comment by Stellar-tickets** [comment]
pandaslovetigers: Rowan-juno and rowan-atom

**Comment by Stellar-tickets** [comment]
pandaslovetigers: Exported the Juno and the atom

**Comment by Stellar-tickets** [comment]
pandaslovetigers: And spent half of the remaining Rowan

**Comment by Stellar-tickets** [comment]
pandaslovetigers: There remained a balance of around 20300 rowans

**Comment by Stellar-tickets** [comment]
pandaslovetigers: In trying to swap that, I ran into the issues portrayed in the video

**Comment by Stellar-tickets** [comment]
pandaslovetigers: Now there is only a balance of 6 rowan

**Comment by Stellar-tickets** [comment]
pandaslovetigers: Can you please point me to on-chain data so I can confirm that that's exactly what happened?

**Comment by Stellar-tickets** [comment]
pandaslovetigers:

**Comment by Stellar-tickets** [comment]
pandaslovetigers: This is the address

**Comment by Stellar-tickets** [comment]
pandaslovetigers: I can see on the Mintscan explorer things like "Unlock liquidity request", but I cannot follow the trail from the data here alone

**Comment by Stellar-tickets** [comment]
lufa23: hey, let us look into it

**Comment by Stellar-tickets** [comment]
pandaslovetigers: Thanks

**Comment by Stellar-tickets** [comment]
lufa23: hey quick question, are you still witnessing the issue?

What do you mean exactly with "Can you please point me to on-chain data so I can confirm that that's exactly what happened?"

Like which other information do you need that it is not available on mintscan?

**Comment by Stellar-tickets** [comment]
lufa23: ok it looks like this issue got solved, closing now

**Comment by Stellar-tickets** [comment]
lufa23: !!close
