### ISSUE TITLE
Import / Export issue

### ISSUE THREAD

**Issue by spaceh3ad** [Sifchain/Support-Tickets#427]
## Describe the bug

Imported 150 USDC from ETH but funds are not available

## How to Reproduce

1. Go to balances tab
2. Search for usdc
3. Click import
4. Approve all metamask norification
5. Wait 50 blocks and have no idea where funds are.

## Expected behaviour
I expected to have my USDC availavle on platform.

## TX Hashes
https://etherscan.io/tx/0xb0d97865c2502a414d652fac55a376d30be36e22da80b13e6ffbab3483635103

**Comment by emperorjm** [comment]
Hi @spaceh3ad. Can you also share your sifchain address that should receive the tokens?

**Comment by spaceh3ad** [comment]
Yep

`sif1sw9agstu0wfdmdj9nnnp7vlt3yzzgz5r2hsap3`

**Comment by smartyalgo** [comment]
@intl-man 
Please run replayEthereum on all relayers with following parameters

Ethereum Starting block: 15353714
Ethereum Ending block: 15353714

Sif Starting block: 8169540
Sif Ending block: 8173565

**Comment by emperorjm** [comment]
Hi @spaceh3ad. Your tokens have been transferred to your sif address. Please let us know if you have any other issues.
