### ISSUE TITLE
Issue sending UST and LUNA back to Terra Chain

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#428]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

I am trying to send UST and Luna back to the native Terra Network. When I do the IBC, it accepts my gas fee buts then says that there's an error.Import was easy. But attempting to export my funds is difficult. Worse is it is eating my Sif while attempting to send by token back to its native chain. tx hash: 0CC601870BBD12BD7085B91336B53BDF386B753132DCA03A3866887FF8E03973

**Comment by Stellar-tickets** [comment]
sif_baldr: Hi <@366262825456369664>. Terra Classic is what is currently integrated with Sifchain. You would need to export back to Terra Classic and then transfer from that chain to the new Terra chain.

**Comment by Stellar-tickets** [comment]
Hulkpool: <@476844095499796491> Yes, sorry. I meant Terra classic. I was trying to send my UST and LUNC back to Terra Classic and I kept getting an error. Any way to fix that?

**Comment by Stellar-tickets** [comment]
Hulkpool: I tried again to send 1800 UST to Terra Classic Network and it failed tx hash: DA972310C4CE32908B52EC702130C34B88746EFAEB8285531A02DC4C8205EC03

**Comment by Stellar-tickets** [comment]
sif_baldr: <@366262825456369664> are you doing this from the Frontend or manually setting up a channel within Keplr?

**Comment by Stellar-tickets** [comment]
sif_baldr: The issue has been reported to the Devs and they are looking into it.

**Comment by Stellar-tickets** [comment]
Hulkpool: <@476844095499796491> from the consensus dex

**Comment by Stellar-tickets** [comment]
lufa23: hey <@366262825456369664> has the issue been solved?

**Comment by lufa23** [comment]
as i see a successful transaction on the terra classic blockexplorer:
https://atomscan.com/terra/transactions/0407629A1DE183F897C7DB175FD0C4E1368C0B7A36E8B5D9689E31816796E1D6

**Comment by Stellar-tickets** [comment]
Hulkpool: <@694599887680962692> yes thank you for checking on me.

**Comment by Stellar-tickets** [comment]
lufa23: !!close
