### ISSUE TITLE
Exporting LUNA to Terra Classics timesout

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#429]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

Hello.

Export from Sif to Terra ( LUNC ) doesn't work.

Here is example of transaction at Sif:
https://www.mintscan.io/sifchain/txs/649D0FD7F3647B8C7733E58F2D747DBA57FEA82EFF45F3FA4F541DF35FA0EB55

It keeps being timed out.

Please help.

**Comment by Stellar-tickets** [comment]
sif_baldr: You are the second user reporting this issue. The issue has been reported to the Devs and they are looking into it.

**Comment by Stellar-tickets** [comment]
sif_baldr: <@401377690231373835> are you still experiencing this issue?

**Comment by lufa23** [comment]
it looks like the tx correctly went through by looking at the Terra Classic blockexplorer:
https://atomscan.com/terra/accounts/terra15a5g72967828dqdh029eedk3t7hlqchyr4pfd3

**Comment by Stellar-tickets** [comment]
lufa23: !!close
