### ISSUE TITLE
Import / Export issue

### ISSUE THREAD

**Issue by Edge10810** [Sifchain/Support-Tickets#430]
## Describe the bug

A Detailed description of the issue (what happened, token affected and token amount)

Trying to export 1000 Luna from sifchain to terra station wallet. IBC transfer has green tick for transfer but pending for received.

## How to Reproduce

4. See error "..."

## Expected behaviour
I expected Luna tokens to be available in my terra station wallet

## TX Hashes
Please provide links to transaction hashes of the import / export issues you are facing

F330F7529CFCF4A62DFD4AD526B4215B7E1C6C2C163E0350D8687D53E882058E

## Addresses
Please provide links to your addresses (**both** of Sifchain and external chain)

Sender
[sif1he3scpew47vdzmcvkkh7hzvx5nehj7gzyxhs5k](https://www.mintscan.io/sifchain/account/sif1he3scpew47vdzmcvkkh7hzvx5nehj7gzyxhs5k)

·  Receiver

terra1jhlhag2ur8lmehk2h9vzhc2jxcly5w4wx42n9q

## Error logs
Please provide links to your addresses (both of Sifchain and external chain)

## Screenshots

**Providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by lufa23** [comment]
hey, looking at the terra classic blockexplorer it looks like the transaction was correctly processed:
https://atomscan.com/terra/accounts/terra1jhlhag2ur8lmehk2h9vzhc2jxcly5w4wx42n9q
