### ISSUE TITLE
Can't transfer AKT token from ethereum to sifchain

### ISSUE THREAD

**Issue by tuthanden9999** [Sifchain/Support-Tickets#434]
Hi, I tried following [this guide](https://docs.google.com/document/d/161bXWtViU7R2K1UnicHVFnXhcNi00jT2pbFekruwMMM/edit?usp=sharing)

But I got error when excute transaction, when metamask dialog appear.
Please check the below infors and image:
Token: AKT (ERC20)
Token contract: 0xc727f87871ee12bbcedd2973746d1deb7529aad6
Ethereum address: 0xC7BD4F27fd0B802bC687AD4162ca31fd6b4c4465
Sifchain address: sif1qq3a83xxsaxwnlzv7pche8pjh4ktyj5ffx0yd6
Amount: 969.976323 AKT

So now I can't transfer AKT token from ethereum to sifchain. Please check and help me as soon as possible.
Thank you very much!

Detail error image:
![errAkt](https://user-images.githubusercontent.com/21007362/188358835-3cff3593-de59-4650-8842-e348ee096f92.PNG)

_Originally posted by @tuthanden9999 in https://github.com/Sifchain/Support-Tickets/issues/375#issuecomment-1236522841_

**Comment by emperorjm** [comment]
Hi @tuthanden9999. I am looking into this.

**Comment by emperorjm** [comment]
Hi @tuthanden9999. We are working on a simple tool to allow you to do the import. This should be ready very soon.

**Comment by emperorjm** [comment]
Hi @tuthanden9999. Our team created the following app to allow for importing cosmos bridged assets from Ethereum to Sifchain https://token-recovery-tool.vercel.app/. Currently, only cosmos bridged tokens are supported (for eg: atom, regen, xprt, iris and akt). You will get an error if you enter a non-cosmos bridged asset.

**Comment by tuthanden9999** [comment]
I will try it when needed.
Thank you! Have a nice day.
