### ISSUE TITLE
FE issues

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#436]
**Description:**
Balances in the FE takes long time to load, and some of them are inaccurate:

Sif Address:
[sif12r2mlzz097n5jhu9uf5gd2mflfn77xu83xvxma](https://www.mintscan.io/sifchain/account/sif12r2mlzz097n5jhu9uf5gd2mflfn77xu83xvxma)

The user witnesses two sepatate issues, both of them regarding balances. As it is not clear if the issues are related, only a support ticket has been created for now:

**FE issue 1:**

- Balance amount for LIKE token takes long time to show. Clearing cache didn't work
![649F4F74-4082-43C0-BDF0-42B9D65BC689](https://user-images.githubusercontent.com/67415638/191081933-4c98f730-227f-4f27-a0a7-02f747eb3dc2.jpg)

**FE issue 2:**

- Osmosis balance shows zero (while there are LIKE tokens in the wallet):
![DC6C0DE0-3F7C-4DF9-A50B-BC2057FE5285](https://user-images.githubusercontent.com/67415638/191082110-03971324-e878-4457-b0d9-7e4458aee3a7.jpg)

**DevTools logs:**

![1E1A9C04-6F24-4C34-BCF8-D8F4847CD162](https://user-images.githubusercontent.com/67415638/191082380-423b0c93-bff0-4968-9035-8cb5950237ab.jpg)

![89B24D35-CE48-4F96-A7C7-78A2F22E3177](https://user-images.githubusercontent.com/67415638/191082415-286bb503-6c02-492b-b8ff-d0af656347b2.jpg)

**Comment by lufa23** [comment]
hey, delays can happen when there are a lot of rpc requests at the same time..
Can you try again by using the developer tools and send us a screenshot?
<img width="704" alt="devtools" src="https://user-images.githubusercontent.com/67415638/189638443-70b15a17-4985-42f4-96f0-c6fe79733422.png">

**Comment by Stellar-tickets** [comment]
lufa23: hey i answered on github but i see that the message was not forwarded here..
is the issue persisting?

**Comment by Stellar-tickets** [comment]
Ducksquaddd: Hey, GitHub doesn't have any sort of websocket connection or a system to send me anything when a comment is made so it's only discord to GitHub and not GitHub to discord

**Comment by Stellar-tickets** [comment]
woodearthearth: Thanks for the comment

**Comment by Stellar-tickets** [comment]
woodearthearth: But I waited for whole day lol 🤣

**Comment by Stellar-tickets** [comment]
woodearthearth: Also this issue

**Comment by Stellar-tickets** [comment]
woodearthearth: 💙

**Comment by Stellar-tickets** [comment]
lufa23: mmm can you try clearing the cache?

And after you try, can you use the devtools and share the console logs?

**Comment by Stellar-tickets** [comment]
woodearthearth:

**Comment by Stellar-tickets** [comment]
woodearthearth: Enough information?

**Comment by Stellar-tickets** [comment]
woodearthearth:

**Comment by Stellar-tickets** [comment]
lufa23: great thanks!
So can you confirm that both issues still exist even after clearing the cache?

- balance amount takes long time to show
- Osmosis balance shows zero (while there are OSMO in the wallet)

also, can you share with me your address?

**Comment by Stellar-tickets** [comment]
woodearthearth: Yes.I confirm

**Comment by Stellar-tickets** [comment]
woodearthearth: sif12r2mlzz097n5jhu9uf5gd2mflfn77xu83xvxma

**Comment by Stellar-tickets** [comment]
lufa23: heya, issue should be fixed now, can you confirm?

**Comment by Stellar-tickets** [comment]
woodearthearth: Fixed likecoin chain but Osmo

**Comment by Stellar-tickets** [comment]
lufa23: <@908939794292297780> you are still having issues with Osmo?

**Comment by Stellar-tickets** [comment]
woodearthearth: Yep

**Comment by Stellar-tickets** [comment]
lufa23: hey, which of the two images taken from the devtools are regarding this issue?

**Comment by Stellar-tickets** [comment]
woodearthearth:

**Comment by lufa23** [comment]
just to mention again the pending issue:

Linkcoin balance on Osmosis network shows zero (while there are LIKE tokens in the wallet):

![F9E20196-6AAB-4A7B-86B6-2B917A50F536](https://user-images.githubusercontent.com/67415638/193634654-852cfae3-8a96-4243-b615-b4ea4f4654ac.jpg)
![1910821310-03971324-e878-4457-b0d9-7e4458aee3a7](https://user-images.githubusercontent.com/67415638/193634754-d9df89e1-f97f-476a-9f73-2d46353bd27a.jpeg)

**Comment by Stellar-tickets** [comment]
woodearthearth: Take it easy

**Comment by Stellar-tickets** [comment]
woodearthearth: I can withdraw to likechain first  to solve the problem.

**Comment by Stellar-tickets** [comment]
lufa23: !!close
