### ISSUE TITLE
Import / Export issue

### ISSUE THREAD

**Issue by hieudau94** [Sifchain/Support-Tickets#438]
I cant import Atom in my wallet on sifdex
It just loading!
![16634307195873884543343851121701](https://user-images.githubusercontent.com/113788787/190865970-7ad3b06a-cf24-4ae7-9c29-ad4952ad66af.jpg)
Please give me an answer soon
Many thanks

**Comment by lufa23** [comment]
hey, this has been fixed and packets are getting relayed
