### ISSUE TITLE
Import - Export

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#439]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

Import Token to Sifchain is taking a very long time to retrieve the token Balance, the circle just spins and spins.

**Comment by Stellar-tickets** [comment]
hungng: Hi our devs are currently looking into it. We will notify you asap

**Comment by Stellar-tickets** [comment]
hungng: Hi, we just fixed the IBC import/export, do you see any issues now ?

**Comment by Stellar-tickets** [comment]
srizbi84: Apologies, I just remembered about this ticket. I will check again once the chain is back up and running.

**Comment by lufa23** [comment]
hey, i assume that the issue has been fixed
Please let me know if this was not the case

**Comment by Stellar-tickets** [comment]
lufa23: !!close
