### ISSUE TITLE
Reached Liquidity Thresold

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#441]
failed to execute message; message index: 0: Unable to swap, reached maximum rowan liquidity threshold
<img width="1068" alt="Screenshot 2022-09-19 at 10 58 41" src="https://user-images.githubusercontent.com/67415638/190983296-24f843b5-ec51-44a4-9be0-6028238168d7.png">

https://www.mintscan.io/sifchain/txs/85712BB303136A81453DDE563225E6404FBAAAB564364B15E249DABDB016A8CC

**Comment by lufa23** [comment]
hey, did you check the [DEX Liquidity Protection specs](https://www.notion.so/sifchain/DEX-Liquidity-Protection-Functional-Doc-External-4525330ebfc34e029cb6e5f967704c77)?

**Comment by Stellar-tickets** [comment]
lufa23: hey, did you check the DEX Liquidity Protection specs?

**Comment by Stellar-tickets** [comment]
lufa23: https://www.notion.so/DEX-Liquidity-Protection-Functional-Doc-External-4525330ebfc34e029cb6e5f967704c77

**Comment by Stellar-tickets** [comment]
lufa23: close!!

**Comment by Stellar-tickets** [comment]
hungng: !!close
