### ISSUE TITLE
LUNA funds not credited

### ISSUE THREAD

**Issue by lufa23** [Sifchain/Support-Tickets#443]
**Description:**

User [sif14rtnr262smr8nyzrpvkprx8md6ng9xeyzlnc73](https://www.mintscan.io/sifchain/account/sif14rtnr262smr8nyzrpvkprx8md6ng9xeyzlnc73) tried to import Terra Classic into Sifchain through a successful transaction [afdaee9a957c2e68c5d503cadfe1835020c3160a5851261259d8d592902f7000](https://finder.terra.money/classic/tx/afdaee9a957c2e68c5d503cadfe1835020c3160a5851261259d8d592902f7000), which is still pending on Sifchain's side

**Comment by mgl2150** [comment]
The client is expired due to Sifchain halt incident, I have submitted a gov prop to revive it, the import issue will be solved once the prop passes:
https://www.mintscan.io/sifchain/proposals/119
