### ISSUE TITLE
LUNA import issue

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#444]
I attempted to send 22700 Luna to Sifchain for a trade. I got the prompt for transfer to begin. I did transfer. But when it went through it "timed out" the issue is that I never got my Luna back to my wallet.

also here's where the luna was sent https://finder.terra.money/classic/address/terra1r726yra3euctv92qqfxh45xztewgp2qjjqp649

I have the terra tx https://finder.terra.money/mainnet/tx/AFDAEE9A957C2E68C5D503CADFE1835020C3160A5851261259D8D592902F7000 but I'm still waiting on that to load.

**Comment by mgl2150** [comment]
The client is expired due to Sifchain halt incident, I have submitted a gov prop to revive it, the import issue will be solved once the prop passes:
https://www.mintscan.io/sifchain/proposals/119

**Comment by Stellar-tickets** [comment]
lufa23: hey, can you confirm that the issue has been solved? The Terra Classic IBC client has been restored with last governance proposal

**Comment by Stellar-tickets** [comment]
lufa23: !!close
