### ISSUE TITLE
Import - Export Terra Classic

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#445]
Description:
Issues with export to Terra classic is broken

Here is example:
https://www.mintscan.io/sifchain/txs/B4DAA3070243DCA2B7601F80C69053DB03E8C39731EE9A8B27A346D89983E709

Error is:
failed to execute message; message index: 0: cannot send packet using client (07-tendermint-42) with status Expired: client is not active

**Comment by lufa23** [comment]
hey, thanks for the report, we are looking into it

**Comment by Stellar-tickets** [comment]
s_oa_d: Hello, any updates on the issue?

**Comment by Stellar-tickets** [comment]
Ducksquaddd: Terra classic IBC channel's have been down since the Crash

**Comment by Stellar-tickets** [comment]
s_oa_d: Which crash do you mean?

If ust unpeg, then it's wrong.
IBC worked after it.

**Comment by Stellar-tickets** [comment]
Ducksquaddd: after the crash as a community they decided to closed the channels

**Comment by Stellar-tickets** [comment]
Ducksquaddd: and that have been down since

**Comment by Stellar-tickets** [comment]
s_oa_d: You are wrong, it's true only about Osmosis and maybe some other chains.

**Comment by Stellar-tickets** [comment]
s_oa_d: Ask colleagues for information

**Comment by Stellar-tickets** [comment]
s_oa_d: https://finder.terra.money/classic/tx/E528F248C65E2E5131C8A4AC7D9D2D5EC812053A28D54FDEF710B35683019557

**Comment by Stellar-tickets** [comment]
s_oa_d: Example of export from Sif.
Date is 19 September

**Comment by Stellar-tickets** [comment]
lufa23: hey, guys just as an heads up, Terra Classic IBC connection has been restored, meaning that now imports and exports should properly work

**Comment by Stellar-tickets** [comment]
s_oa_d: work now. thanks

**Comment by Stellar-tickets** [comment]
lufa23: !!close
