### ISSUE TITLE
LUNA Import / Exports

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#448]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

swap does not work in pairs with luna! writes to increase the gas limit, but the gas is already maximu
<#943694093542912011>

**Comment by lufa23** [comment]
hey, thanks for the feedback. we are looking into it

**Comment by Stellar-tickets** [comment]
lufa23: duplicated, closing

**Comment by Stellar-tickets** [comment]
lufa23: !!close

**Comment by mgl2150** [comment]
The client is expired due to Sifchain halt incident, I have submitted a gov prop to revive it, the import issue will be solved once the prop passes:
https://www.mintscan.io/sifchain/proposals/119
