### ISSUE TITLE
LUNA Import / Export

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#449]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

the bridge for luna and ust does not work in either direction
<#943694093542912011>

**Comment by lufa23** [comment]
hey, we are looking into it

**Comment by mgl2150** [comment]
The client is expired due to Sifchain halt incident, I have submitted a gov prop to revive it, the import issue will be solved once the prop passes:
https://www.mintscan.io/sifchain/proposals/119

**Comment by Stellar-tickets** [comment]
lufa23: hey, can you confirm that the issue has been solved? The Terra Classic IBC client has been restored with last governance proposal

**Comment by Stellar-tickets** [comment]
lufa23: !!close
