### ISSUE TITLE
Asymmetric adds glitch

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#456]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

When adding liquidity to a Pool, after inserting the number of $ROWAN, the other token number is filled in automatically. However, I received twice this error: failed to execute message; message index: 0: Cannot add liquidity with asymmetric ratio

**Comment by lufa23** [comment]
the issue was due to a UI glitch, and it should be fixed now. Can you clear the cache and tell us if the issue has been solved?

**Comment by Stellar-tickets** [comment]
Angelo: any feedback?

**Comment by Stellar-tickets** [comment]
lufa23: hey, the issue was due to a UI glitch, and it should be fixed now. Can you clear the cache and tell us if the issue has been solved?

**Comment by Stellar-tickets** [comment]
lufa23: !!close
