### ISSUE TITLE
Osmosis - IBC issue

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#457]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

can't ibc to osmo. Any ammount is returned minus the fee

**Comment by lufa23** [comment]
hey Osmosis chain has been halted

**Comment by Stellar-tickets** [comment]
lufa23: hey, Osmosis network was down and now it's up and running again. We are currently looking if there are stuck IBC packets. Can you confirm that the issue has been solved?

**Comment by Stellar-tickets** [comment]
lufa23: !!close
