### ISSUE TITLE
Discrepant amounts - ATOM pool - Reward issue 15 - Github issue 461

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#461]
Give a description of the rewards problem. Include your sifchain address, and what pools you are in

Hi admin
After recent update, my ATOM/ROWAN liquidity decreased. Is this a temporary problem?
I mean my original and real liquidity, not related to the increase by the bug.
Unfortunately, I Don’t have any screen shot before bug downs, but I am sure I had over 195000 ROWAN and over 90 of ATOM!! The last(bugs increased) and the new screen shot is attached.
I’m not talking about value in USD, decreased by number of ROWAN and ATOM. 
also,  that’s not balanced ROWAN/ATOM as well as already.

User Account: sif17jk9ze5xptlftyw43fx0ag9t3lkc45tw6c03kj

**Comment by Stellar-tickets** [comment]
lufa23: hey, it seems to be a UI glitch.. we are investigating

**Comment by Stellar-tickets** [comment]
lufa23: can you clear the cache and tell us if the issue persists?

**Comment by Stellar-tickets** [comment]
lufa23: also, are you seeing the issue on the  `your liquidity` section on the pools page?

**Comment by lufa23** [comment]
User is witnessing a continuous reduce in its liquidity. User took two screenshots, with the second screenshot being at 1 hour and 23 minutes after the first one. During this relatively short time, ROWAN reduced 121424 to 120265
![ss5](https://user-images.githubusercontent.com/67415638/194336532-a533e86f-ea51-483c-84da-b620e271e99e.jpg)

![ss6](https://user-images.githubusercontent.com/67415638/194336565-69cbdc66-c058-4563-b3df-a114d5f48caa.jpg)

**Comment by lufa23** [comment]
after answering to the user with the following:

> From the first screenshot and the second one:
> - you can notice that the Pool Value field (at the right), increased from 1356.95$ to 1368.30$, so your position actually accrued value during that 1hour and 23 minutes
> 
> 
> The reason why you see your Rowan amount decreasing, is because of LPD which takes out Rowan from your pool position and puts it back into your wallet
> 
> So if you check your wallet you should see the amount of Rowan that were in your pool position

The user is still concerned, as he can see now his Liquidity position having  lowered both on Rowan and Atom. He additionally sends this screenshot:
![ss7](https://user-images.githubusercontent.com/67415638/194577162-87242a46-5acb-41df-8927-2905c95b08fc.jpg)

**Comment by lufa23** [comment]
it has been asked to the user to provide calculations that shows that the combination of LPD + Impermanent Loss is not the cause of the current balance?

**Comment by lufa23** [comment]
btw, i suggest you to check the AMA that Jazear did yesterday:
https://www.youtube.com/watch?v=WqlFYi3MIFE
