### ISSUE TITLE
Discrepant Liquidity Withdraw amount - Rewards Calculation - 19

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#470]
Give a description of the rewards problem. Include your sifchain address, and what pools you are in

Hey! When I try to unbond my assets from an LP the external amount reduces

**Comment by lufa23** [comment]
User reports that when submitting the liquidity withdrawal request he noticed he had 36 atoms in that pool, and unbonding popup gives the estimate to be 36 atoms. Unboded ATOMs have decreased until reaching 28

<img width="446" alt="Screenshot 2022-10-12 at 15 38 05" src="https://user-images.githubusercontent.com/67415638/195357699-86d1dfb0-8dd9-47a8-9985-fc4e30ad514e.png">

**Comment by Stellar-tickets** [comment]
lufa23: hey, did you look at the LPD feature?
https://www.notion.so/sifchain/Liquidity-Provider-Distribution-Functional-Doc-External-49aba98724f84321ae84f3078ad07e00

**Comment by Stellar-tickets** [comment]
lufa23: !!close

**Comment by lufa23** [comment]
btw  i suggest you to check the AMA that Jazear did yesterday:
https://www.youtube.com/watch?v=WqlFYi3MIFE
