### ISSUE TITLE
Export issue: export ROWAN from sifchain to Ethereum

### ISSUE THREAD

**Issue by tuthanden9999** [Sifchain/Support-Tickets#471]
https://www.mintscan.io/sifchain/txs/E068FA6FB8588158E5D17443B1D18949EB8E95340BA26241D502C3AB80C36021

Please check above transaction. I export ROWAN from sifchain to ethereum but not received on ethereum.

Sifchain address:
sif1qq3a83xxsaxwnlzv7pche8pjh4ktyj5ffx0yd6

Ethereum address:
0xC7BD4F27fd0B802bC687AD4162ca31fd6b4c4465

Thanks!

**Comment by lufa23** [comment]
hey, this should be solved... can i close the issue?

**Comment by tuthanden9999** [comment]
I continue got stuck when export ROWAN from sifchain to ethereum.

Please check tx:
https://www.mintscan.io/sifchain/txs/6031A129A12FD086350D57919B1340E8B260C248CD2B6C378B3BF2BDFB96D78C

Sifchain address:
sif1qq3a83xxsaxwnlzv7pche8pjh4ktyj5ffx0yd6

Ethereum address:
0xC7BD4F27fd0B802bC687AD4162ca31fd6b4c4465

Many thanks!

**Comment by tuthanden9999** [comment]
Issues are both fixed. Many thanks!
