### ISSUE TITLE
Export ETH from SifChain "successful"  ETH did not arrive in my ETH wallet

### ISSUE THREAD

**Issue by petecraig1** [Sifchain/Support-Tickets#473]
Please assist with locating my ETH:

TxHash:  E1843900FB81E9F21A01B32CF679AFC088643CD4E9406C19E2FC033003F496B9

![17 ETH](https://user-images.githubusercontent.com/67651835/195683902-69d908d0-3399-493f-9894-31fc2c5feffb.png)

ETH was exported to proper wallet.  Does not show up in wallet.  

How can I locate this ETH?    Thank you.

**Comment by lufa23** [comment]
hey! bridge is active again now, can you confirm that the issue is solved?

**Comment by petecraig1** [comment]
Solved !  Thank you!
* Yours,*


*      Peter Craig*
     295-A Mahoney Dr. #1979
     Telluride, CO   81435

     Mobile:   *(970)708-4525*

**Comment by petecraig1** [comment]
Awesome, thanks!
* Yours,*


*      Peter Craig*
     295-A Mahoney Dr. #1979
     Telluride, CO   81435

     Mobile:   *(970)708-4525*
