### ISSUE TITLE
Import / Export issue

### ISSUE THREAD

**Issue by tiagsouza** [Sifchain/Support-Tickets#474]
## Describe the bug
I exported some ZCN tokens from SIFCHAIN to ERC-20. Transaction was successful, but I have not received my tokens

## TX Hashes
https://www.mintscan.io/sifchain/txs/6F87FA0E05D151EC3A6BD00047C6527EA5074B0F6FBD911EC4D2BE7743614EA0

## Addresses
sif1gkrr64n2h3q5vut67msrm33jep6rtxt24mp8km
0xFf9d38a54193d91859cd28575C76D1178B96BA00

**Comment by lufa23** [comment]
hey, the bridge is active again now..can you confirm that the issue has been solved?
