### ISSUE TITLE
Import export issue(Bug Report - 98)

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#480]
Give a description of the bug! Include things like how to reproduce it, what you expected to happen, and what actually happened.

I had exported METIS to Ethereum, But I can not receive it

**Comment by lufa23** [comment]
hey, can you confirm that the issue has been solved?

**Comment by Stellar-tickets** [comment]
LarryShum: I can’t receive it yet.

**Comment by Stellar-tickets** [comment]
LarryShum: Export RUNE and ENJ are not receive on Ethereum too.

**Comment by Stellar-tickets** [comment]
LarryShum: https://www.mintscan.io/sifchain/txs/5006C3B075D19E49A0423CB5D1EA341520FDA42A21E1D14F7074551ECCDC944E

**Comment by Stellar-tickets** [comment]
LarryShum: https://www.mintscan.io/sifchain/txs/589A284216F4262D098E7BEA4998AB6F3B72716B9BBEB9CD922F19CE78E75C35

**Comment by Stellar-tickets** [comment]
LarryShum: I got it now.

**Comment by Stellar-tickets** [comment]
hungng: !!close
