### ISSUE TITLE
Users having issues exporting/importing IRIS to and from from IRISnet

### ISSUE THREAD

**Issue by nagadau** [Sifchain/Support-Tickets#56]
Unable to Export IRIS from SifChain to IRISnet. Transaction always fail; it says "Failed to fetch". You can verify for yourself. IRIS network upgrade has also been completed two days ago.

approved by telegram user: : @saundersMcSifLane
requested by telegram user: @sb8911

**Comment by bksifchain** [comment]
Hey @lufa23 - is this still an issue? do we need the FE team to track this? if not, i will remove the label

**Comment by lufa23** [comment]
i just tried again, IRIS import and exports seem to correctly work.
Closing the issue
