### ISSUE TITLE
Problem with the rewards displaying

### ISSUE THREAD

**Issue by OlegEnthusiast** [Sifchain/Support-Tickets#67]
On the two red popups there are different messages: the up right one says dispensation on Saturday PST, the other one says Friday
![image](https://user-images.githubusercontent.com/92320396/143620311-1c8d4cdf-9316-4443-9fc9-42b0980134eb.png)

**Comment by lufa23** [comment]
closing as https://github.com/Sifchain/issues/issues/942 has been delivered
