### ISSUE TITLE
 IRIS import/export problem is NOT due to Keplr, as identified?

### ISSUE THREAD

**Issue by nagadau** [Sifchain/Support-Tickets#75]
Oleg explained to me yesterday that "The IrisNET import/export issue seems to be stemming from Keplr as they might not have updated their IrisNET node to the latest version which we have seen happened a few times in the past. A report has been made and we hope they can rectify this issue soon." However, I'm able to easily import and export IRIS using Keplr with no problem to Osmosis (https://www.mintscan.io/iris/txs/F5FB5EC5833ED2920522CA916F9ECC6559372F456BF0C5AC2B85F42EAF38B148 + https://www.mintscan.io/iris/txs/9B5F95A11D0A517B33BA4D77068270E5DAD522F51D8791FDB59C2D32B0771442 ). This means that Keplr not updating their "IrisNET node to the latest version" may not be the cause of the problem?

approved by telegram user: : @saundersMcSifLane

requested by telegram user: @sb8911
associated sifchain address: sif1ds47lphn8268u7q2qcz25wc3gtqf6frsrt3keu

**Comment by lufa23** [comment]
hey @stbeyer did the user reach out to you recently?

**Comment by lufa23** [comment]
i assume that the issue is related to [this one](https://github.com/Sifchain/Support-Tickets/issues/56)
cc @ajoslin @intl-man
